import { FigureShell } from "../content/FigureShell";
import React, { type ReactNode } from "react";

export type MLOpsVisualId =
  | "production-lifecycle" | "three-planes"
  | "pipeline-dag" | "feature-stores" | "training-serving-skew" | "point-in-time"
  | "experiment-lineage" | "run-gates" | "registry-lifecycle"
  | "inference-modes" | "latency-budget"
  | "test-layers" | "cicdct-flow" | "release-gate"
  | "monitoring-layers" | "psi-shift" | "retraining-decision"
  | "reliability-fallback" | "security-boundaries" | "cost-comparison"
  | "fraud-architecture" | "sync-async" | "degradation-routes";

type Tone = "slate" | "indigo" | "cyan" | "emerald" | "amber" | "rose" | "violet";

const toneClasses: Record<Tone, string> = {
  slate: "border-slate-300 bg-slate-50 text-slate-900",
  indigo: "border-indigo-300 bg-indigo-50 text-indigo-950",
  cyan: "border-cyan-300 bg-cyan-50 text-cyan-950",
  emerald: "border-emerald-300 bg-emerald-50 text-emerald-950",
  amber: "border-amber-300 bg-amber-50 text-amber-950",
  rose: "border-rose-300 bg-rose-50 text-rose-950",
  violet: "border-violet-300 bg-violet-50 text-violet-950",
};

function Node({ title, detail, tone = "slate", className = "" }: { key?: React.Key; title: string; detail?: string; tone?: Tone; className?: string }) {
  return <div className={`min-w-0 rounded-xl border-2 p-3 text-center shadow-sm sm:min-w-28 sm:flex-1 ${toneClasses[tone]} ${className}`}><strong className="block text-sm leading-tight">{title}</strong>{detail && <span className="mt-1 block text-xs leading-relaxed text-slate-600">{detail}</span>}</div>;
}

function Arrow({ label }: { key?: React.Key; label?: string }) {
  return <div className="flex shrink-0 items-center justify-center text-indigo-700" aria-hidden="true"><span className="hidden text-xl font-black sm:inline">→</span><span className="text-xl font-black sm:hidden">↓</span>{label && <span className="ml-1 text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</span>}</div>;
}

function Flow({ children, columns }: { children: ReactNode; columns?: string }) {
  return <div className={columns ? `grid items-center gap-2 ${columns}` : "grid items-center gap-2 sm:flex sm:flex-wrap sm:justify-center"}>{children}</div>;
}

const meta: Record<MLOpsVisualId, { title: string; question: string; caption: string }> = {
  "production-lifecycle": { title: "From a notebook result to an operating prediction system", question: "What must surround a trained model before people can rely on it?", caption: "The model artifact is one hand-off in a larger loop. Validated data creates features, evaluation controls promotion, serving produces predictions, and monitored outcomes become evidence for the next training decision." },
  "three-planes": { title: "Three connected planes of production ML", question: "Where do data, model-management, and live-serving responsibilities meet?", caption: "The planes have different jobs and failure modes, but they exchange versioned features, model artifacts, prediction records, and outcome feedback." },
  "pipeline-dag": { title: "A pipeline is a dependency graph, not merely a list", question: "Why may downstream work run only after its required inputs succeed?", caption: "The graph exposes dependencies. A failed validation blocks feature creation and training; a retry resumes from the failed task, while a backfill reruns an earlier time range deliberately." },
  "feature-stores": { title: "One feature definition, two serving needs", question: "How can training and live prediction use the same feature meaning?", caption: "Offline storage keeps historical, point-in-time feature values for training and batch scoring. Online storage serves the latest approved values quickly. Both should come from versioned feature logic." },
  "training-serving-skew": { title: "Training-serving skew changes the model input", question: "What happens when the same feature name is calculated differently?", caption: "Training counts eight completed orders in the prior 30 days; production counts only three mobile events. The model receives a different customer representation even though both systems call the field orders_last_30_days." },
  "point-in-time": { title: "Point-in-time joins prevent the future from leaking backward", question: "Which feature record was actually knowable when the prediction was made?", caption: "For a prediction at 10:00, the training row may use only facts available by 10:00. A chargeback reported two days later belongs to the label outcome, not the earlier feature set." },
  "experiment-lineage": { title: "A reproducible run has an evidence chain", question: "What must be connected to reproduce a result?", caption: "A metric without its code, data, feature, parameter, environment, and artifact versions is an orphaned number. Lineage records the exact inputs and outputs of the run." },
  "run-gates": { title: "Promotion uses eligibility gates before ranking", question: "Why does the highest accuracy run not automatically win?", caption: "Run A fails the recall requirement and Run C fails the latency requirement. Run B is the only production-eligible candidate, although its accuracy is not the highest." },
  "registry-lifecycle": { title: "A registry governs model versions through states", question: "How does a tested artifact become production—and roll back safely?", caption: "Registration does not equal approval. Evidence moves a candidate through review and controlled release; the previous known-good version remains available for rollback." },
  "inference-modes": { title: "Batch, online, and streaming inference solve different timing problems", question: "When is a prediction needed, and how does that shape the architecture?", caption: "Batch maximizes efficient bulk work, online answers one synchronous request within a latency target, and streaming continuously processes events with checkpointed recovery." },
  "latency-budget": { title: "An online response spends one shared latency budget", question: "Which sequential stages consume a 100 ms service target?", caption: "Network, validation, feature lookup, model inference, rules, and serialization all spend the same end-to-end budget. A fast model alone does not guarantee a fast endpoint." },
  "test-layers": { title: "ML tests protect more than application code", question: "Which different contracts can fail before a model reaches users?", caption: "Code, data, features, model behaviour, and integration each need targeted tests. Passing a schema test cannot prove that a new model still meets recall or slice requirements." },
  "cicdct-flow": { title: "CI, CD, and CT are related but distinct loops", question: "What is integrated, released, and retrained?", caption: "CI validates changes, CD moves an approved artifact through release stages, and CT creates a new candidate from justified fresh evidence. CT still returns to evaluation and approval." },
  "release-gate": { title: "A model regression test can stop an otherwise valid build", question: "What happens when data is valid but candidate performance declines?", caption: "The schema and range checks pass, training completes, but recall falls below the approved minimum. The gate rejects the candidate and keeps the current production version." },
  "monitoring-layers": { title: "Four monitoring layers answer four different questions", question: "Is the service healthy, is the input changing, is the model behaving differently, and are outcomes still good?", caption: "No single dashboard proves model health. Service, data, prediction, and delayed outcome signals must be connected by model and data versions." },
  "psi-shift": { title: "PSI summarizes movement across distribution bins", question: "Where does the illustrative PSI value come from?", caption: "Each bar compares the expected and current proportion for one bin. The contribution (current − expected) × ln(current / expected) is calculated per bin and then summed." },
  "retraining-decision": { title: "Drift starts an investigation—not an automatic retrain", question: "Which evidence justifies creating and releasing a new model?", caption: "First exclude broken pipelines and temporary events. Confirm persistent outcome degradation, then evaluate a candidate. Release only when the candidate clears the same quality and operational gates." },
  "reliability-fallback": { title: "Graceful degradation keeps failure bounded", question: "What should happen when the primary prediction path is unavailable?", caption: "Timeouts and bounded retries protect the caller. A circuit breaker stops repeated pressure; a safe fallback, queue, or human review replaces an unsafe guess." },
  "security-boundaries": { title: "Production ML crosses several trust boundaries", question: "Where must identity, secrets, data, and artifact integrity be enforced?", caption: "Users, services, storage, registries, and runtime workers receive only the permissions they need. Encryption and signed/versioned artifacts protect data and the model supply chain." },
  "cost-comparison": { title: "Higher hourly price can still mean lower unit cost", question: "How do utilization and throughput change cost per 1,000 predictions?", caption: "At full utilization, Design B serves more than three times the predictions per hour and has the lower toy unit cost. Real selection must also include latency, accuracy, burst capacity, and reliability." },
  "fraud-architecture": { title: "End-to-end real-time fraud detection system", question: "How do the live decision path and learning feedback loop connect?", caption: "The synchronous path produces an approve, review, or reject decision. Logged predictions and delayed fraud labels later build leakage-safe training data for an evaluated candidate release." },
  "sync-async": { title: "Keep the customer decision path short; move learning work off it", question: "Which operations must finish before the transaction response?", caption: "Validation, approved feature lookup, inference, and decision policy are synchronous. Durable logging, labels, training, evaluation, and release workflows are asynchronous." },
  "degradation-routes": { title: "Named failures lead to named safe routes", question: "How does the system avoid blindly approving when a dependency fails?", caption: "Feature-store failure, model timeout, and duplicate events have different responses. Versioned fallbacks, manual review, idempotency keys, and rollback preserve safety and traceability." },
};

function VisualBody({ id }: { id: MLOpsVisualId }) {
  switch (id) {
    case "production-lifecycle": return <Flow>{["Raw data", "Validate", "Features", "Train + evaluate", "Model artifact", "Registry", "Serve predictions", "Monitor outcomes"].flatMap((title, i, a) => [<Node key={title} title={title} tone={i < 3 ? "cyan" : i < 6 ? "violet" : "emerald"}/>, ...(i < a.length - 1 ? [<Arrow key={`${title}-a`}/>] : [])])}<div className="rounded-xl bg-slate-900 p-2 text-center text-xs font-bold text-white sm:col-span-full">Feedback and approved retraining return monitored evidence to the training pipeline ↺</div></Flow>;
    case "three-planes": return <div className="space-y-3"><div className="grid gap-3 lg:grid-cols-3"><Node title="1 · Data / feature plane" detail="ingest → validate → transform → historical and latest features" tone="cyan"/><Node title="2 · Training / management plane" detail="experiment → evaluate → artifact → registry approval" tone="violet"/><Node title="3 · Serving / monitoring plane" detail="request/event → prediction → logs → outcome signals" tone="emerald"/></div><div className="grid grid-cols-1 items-center gap-2 text-center text-xs font-bold text-indigo-800 sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><span>versioned features</span><span>⇄</span><span>approved artifact</span><span>⇄</span><span>prediction + feedback</span></div></div>;
    case "pipeline-dag": return <div className="space-y-4"><Flow columns="sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><Node title="Ingest day D" detail="batch or stream checkpoint" tone="cyan"/><Arrow/><Node title="Validate contract" detail="schema, ranges, duplicates" tone="amber"/><Arrow/><Node title="Create features" detail="only after validation passes" tone="violet"/></Flow><div className="mx-auto h-6 w-px bg-indigo-400"/><div className="grid gap-3 sm:grid-cols-2"><Node title="Train / batch score" detail="downstream dependency" tone="emerald"/><Node title="Failure branch" detail="retry task; alert; backfill dates D−3…D after repair" tone="rose"/></div></div>;
    case "feature-stores": return <div className="space-y-3"><Node title="Versioned feature definition" detail="orders_last_30_days(event_time, status='completed') · v4" tone="indigo"/><div className="mx-auto text-center text-2xl font-black text-indigo-700">↓</div><div className="grid gap-3 sm:grid-cols-2"><Node title="Offline feature store" detail="historical values by entity + event time → training and batch scoring" tone="cyan"/><Node title="Online feature store" detail="latest approved values by entity → low-latency live lookup" tone="emerald"/></div><p className="text-center text-xs font-bold text-slate-600">Same meaning and version; different storage and latency needs</p></div>;
    case "training-serving-skew": return <div className="grid gap-4 md:grid-cols-[1fr_auto_1fr]"><div className="space-y-2"><Node title="Training pipeline" detail="warehouse: completed web + mobile orders" tone="cyan"/><Node title="orders_last_30_days = 8" detail="customer C17 at cutoff time" tone="indigo"/></div><Arrow label="same name"/><div className="space-y-2"><Node title="Online pipeline" detail="mobile stream only; web source omitted" tone="amber"/><Node title="orders_last_30_days = 3" detail="same customer, incomplete calculation" tone="rose"/></div><div className="rounded-xl bg-slate-900 p-3 text-center text-xs font-bold text-white md:col-span-3">Different input → different churn probability → inconsistent customer action</div></div>;
    case "point-in-time": return <div className="space-y-4"><div className="relative grid grid-cols-3 gap-2 before:absolute before:left-[16%] before:right-[16%] before:top-6 before:h-1 before:bg-slate-300"><Node title="Day 0 · 10:00" detail="prediction cutoff" tone="indigo"/><Node title="Day 0 · 16:00" detail="new transaction" tone="cyan"/><Node title="Day 2" detail="chargeback label arrives" tone="rose"/></div><div className="grid gap-2 sm:grid-cols-2"><Node title="Correct training row" detail="features known by Day 0 10:00; later chargeback used only as outcome" tone="emerald"/><Node title="Leaking row" detail="uses Day 0 16:00 or Day 2 knowledge to predict at 10:00" tone="rose"/></div></div>;
    case "experiment-lineage": return <div className="space-y-3"><div className="grid gap-2 sm:grid-cols-3"><Node title="Code commit c41" tone="slate"/><Node title="Dataset snapshot d19" tone="cyan"/><Node title="Feature set v4" tone="cyan"/><Node title="Parameters" detail="depth=6, seed=42" tone="amber"/><Node title="Environment e7" detail="Python + dependency lock" tone="amber"/><Node title="Run R-204" detail="start/end, owner" tone="violet"/></div><div className="text-center text-2xl font-black text-indigo-700">↓ all identifiers recorded together</div><div className="grid gap-2 sm:grid-cols-2"><Node title="Artifact model-204.bin" detail="immutable checksum" tone="indigo"/><Node title="Metrics + slices" detail="accuracy, recall, latency" tone="emerald"/></div></div>;
    case "run-gates": return <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-3"><Node title="Run A" detail="accuracy .91 · recall .68 ✕ · 35 ms ✓" tone="rose"/><Node title="Run B" detail="accuracy .90 · recall .81 ✓ · 42 ms ✓" tone="emerald"/><Node title="Run C" detail="accuracy .92 · recall .79 ✓ · 125 ms ✕" tone="rose"/></div><Flow columns="sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><Node title="Gate 1" detail="recall ≥ .75" tone="amber"/><Arrow/><Node title="Gate 2" detail="latency ≤ 60 ms" tone="amber"/><Arrow/><Node title="Eligible candidate" detail="Run B" tone="emerald"/></Flow></div>;
    case "registry-lifecycle": return <Flow>{["Registered candidate", "Evidence attached", "Approved", "Canary release", "Production"].flatMap((title, i, a) => [<Node key={title} title={title} tone={i < 2 ? "violet" : i < 4 ? "amber" : "emerald"}/>, ...(i < a.length - 1 ? [<Arrow key={`${title}-a`}/>] : [])])}<div className="rounded-xl border-2 border-rose-300 bg-rose-50 p-3 text-center text-xs font-bold text-rose-950 sm:col-span-full">Failed canary → route traffic back to previous known-good version; retain audit history</div></Flow>;
    case "inference-modes": return <div className="grid gap-4 lg:grid-cols-3"><div><Node title="Batch" detail="10M customers overnight" tone="cyan"/><div className="my-2 text-center text-xl">↓</div><Node title="files/table → workers → scored table" detail="minutes or hours; restart by partition" tone="cyan"/></div><div><Node title="Online" detail="one transaction request" tone="violet"/><div className="my-2 text-center text-xl">↓</div><Node title="API → live features → model → response" detail="synchronous; milliseconds" tone="violet"/></div><div><Node title="Streaming" detail="continuous event stream" tone="emerald"/><div className="my-2 text-center text-xl">↓</div><Node title="broker → stateful processors → sink" detail="fresh events; offsets/checkpoints" tone="emerald"/></div></div>;
    case "latency-budget": return <div className="space-y-4"><div className="flex h-16 overflow-hidden rounded-xl border-2 border-slate-300 text-[10px] font-bold sm:text-xs"><span className="flex w-[10%] items-center justify-center bg-slate-200 text-center">10 ms<br/>network</span><span className="flex w-[10%] items-center justify-center bg-cyan-200 text-center">10 ms<br/>validate</span><span className="flex w-[25%] items-center justify-center bg-indigo-200 text-center">25 ms<br/>features</span><span className="flex w-[35%] items-center justify-center bg-violet-300 text-center">35 ms<br/>model</span><span className="flex w-[10%] items-center justify-center bg-amber-200 text-center">10 ms<br/>rules</span><span className="flex w-[10%] items-center justify-center bg-emerald-200 text-center">10 ms<br/>return</span></div><p className="text-center text-sm font-bold text-slate-700">Illustrative total = 10 + 10 + 25 + 35 + 10 + 10 = 100 ms SLA budget</p></div>;
    case "test-layers": return <div className="mx-auto max-w-3xl space-y-2"><Node title="Integration tests" detail="preprocessing + artifact load + endpoint contract" tone="violet"/><div className="mx-auto w-[88%]"><Node title="Model tests" detail="metric gate + slices + regression + golden cases" tone="indigo"/></div><div className="mx-auto w-[76%]"><Node title="Feature tests" detail="transformation + freshness + training/serving parity" tone="cyan"/></div><div className="mx-auto w-[64%]"><Node title="Data tests" detail="schema + ranges + missingness + duplicates" tone="amber"/></div><div className="mx-auto w-[52%]"><Node title="Code tests" detail="utilities + transformations + interface" tone="emerald"/></div></div>;
    case "cicdct-flow": return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Node title="CI · integrate" detail="change → code/data/feature tests → package" tone="cyan"/><Node title="CD · release" detail="approved artifact → shadow/canary → production" tone="emerald"/><Node title="CT · retrain" detail="justified trigger → train new candidate → evaluate" tone="violet"/></div><div className="rounded-xl bg-slate-900 p-3 text-center text-xs font-bold text-white">CT never skips evaluation, approval, or controlled release</div></div>;
    case "release-gate": return <Flow>{[<Node key="change" title="Code + data change" tone="slate"/>,<Arrow key="a1"/>,<Node key="data" title="Data tests PASS" detail="schema and ranges valid" tone="emerald"/>,<Arrow key="a2"/>,<Node key="train" title="Train candidate" tone="violet"/>,<Arrow key="a3"/>,<Node key="model" title="Model test FAIL" detail="recall .71 < required .75" tone="rose"/>,<Arrow key="a4"/>,<Node key="stop" title="STOP deployment" detail="production stays on v12" tone="amber"/>]}</Flow>;
    case "monitoring-layers": return <div className="grid gap-3 sm:grid-cols-2"><Node title="1 · Service" detail="rate, errors, latency, saturation, CPU/GPU, queue" tone="slate"/><Node title="2 · Data" detail="schema, missingness, freshness, distributions" tone="cyan"/><Node title="3 · Predictions" detail="scores, confidence, calibration, abstentions" tone="violet"/><Node title="4 · Outcomes" detail="delayed labels, errors, cost, business KPI" tone="emerald"/><div className="rounded-xl bg-indigo-900 p-3 text-center text-xs font-bold text-white sm:col-span-2">Join by request, model, feature, and data-source versions to diagnose causes</div></div>;
    case "psi-shift": return <div className="space-y-4"><div className="grid grid-cols-3 gap-3 text-center"><div><div className="flex h-28 items-end justify-center gap-1"><span className="w-7 bg-indigo-500" style={{height:"100%"}}/><span className="w-7 bg-amber-400" style={{height:"80%"}}/></div><b className="text-xs">Bin 1<br/>.50 → .40</b></div><div><div className="flex h-28 items-end justify-center gap-1"><span className="w-7 bg-indigo-500" style={{height:"60%"}}/><span className="w-7 bg-amber-400" style={{height:"70%"}}/></div><b className="text-xs">Bin 2<br/>.30 → .35</b></div><div><div className="flex h-28 items-end justify-center gap-1"><span className="w-7 bg-indigo-500" style={{height:"40%"}}/><span className="w-7 bg-amber-400" style={{height:"50%"}}/></div><b className="text-xs">Bin 3<br/>.20 → .25</b></div></div><div className="flex flex-wrap justify-center gap-4 text-xs font-bold"><span className="text-indigo-700">■ Expected</span><span className="text-amber-700">■ Current</span><span>PSI ≈ 0.0412</span></div></div>;
    case "retraining-decision": return <div className="space-y-3"><Flow columns="sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><Node title="Drift alert" tone="amber"/><Arrow/><Node title="Pipeline/data defect?" detail="repair and remeasure" tone="rose"/><Arrow/><Node title="Outcome degradation?" detail="wait for labels; inspect slices" tone="cyan"/></Flow><Flow columns="sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><Node title="Persistent and material?" detail="use-case evidence" tone="violet"/><Arrow/><Node title="Train + evaluate candidate" detail="quality and operations" tone="indigo"/><Arrow/><Node title="Release only if better" detail="canary + rollback" tone="emerald"/></Flow></div>;
    case "reliability-fallback": return <div className="space-y-3"><Flow>{["Caller", "Timeout", "Bounded retry + backoff", "Circuit breaker"].flatMap((title,i,a)=>[<Node key={title} title={title} tone={i===3?"rose":"slate"}/>,...(i<a.length-1?[<Arrow key={`${title}-a`}/>]:[])])}</Flow><div className="grid gap-3 sm:grid-cols-3"><Node title="Safe cached result" detail="only when freshness permits" tone="cyan"/><Node title="Queue for later" detail="asynchronous workloads" tone="amber"/><Node title="Rules / human review" detail="high-risk decision fallback" tone="emerald"/></div></div>;
    case "security-boundaries": return <div className="grid gap-3 lg:grid-cols-[1fr_auto_1fr_auto_1fr]"><Node title="User / producer" detail="authenticated identity; minimum input" tone="slate"/><Arrow/><div className="rounded-2xl border-2 border-dashed border-amber-400 bg-amber-50 p-3"><Node title="Service boundary" detail="least-privilege IAM; secret injection; encrypted traffic" tone="amber"/></div><Arrow/><div className="space-y-2"><Node title="Data + feature storage" detail="PII controls; encrypted at rest" tone="cyan"/><Node title="Registry + runtime" detail="checksums, signatures, dependency scan" tone="violet"/></div></div>;
    case "cost-comparison": return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Node title="Design A · $0.80/hour" detail="80/s × 3,600 = 288,000 predictions/hour · $0.00278 per 1,000" tone="cyan"/><Node title="Design B · $2.00/hour" detail="300/s × 3,600 = 1,080,000 predictions/hour · $0.00185 per 1,000" tone="emerald"/></div><div className="grid h-10 grid-cols-[60%_40%] overflow-hidden rounded-xl text-center text-xs font-bold text-white"><span className="flex items-center justify-center bg-cyan-600">A unit cost</span><span className="flex items-center justify-center bg-emerald-600">B is ≈33% lower</span></div></div>;
    case "fraud-architecture": return <div className="space-y-4"><Flow>{["Transaction", "Stream + validate", "Live features", "Model", "Threshold + rules", "Approve / review / reject"].flatMap((title,i,a)=>[<Node key={title} title={title} tone={i<2?"cyan":i<4?"violet":"emerald"}/>,...(i<a.length-1?[<Arrow key={`${title}-a`}/>]:[])])}</Flow><div className="rounded-xl border-2 border-dashed border-indigo-300 bg-indigo-50 p-3"><Flow>{["Prediction log", "Delayed fraud label", "Point-in-time dataset", "Train candidate", "Registry gates", "Canary → production"].flatMap((title,i,a)=>[<Node key={title} title={title} tone={i<3?"cyan":i<5?"violet":"emerald"}/>,...(i<a.length-1?[<Arrow key={`${title}-a`}/>]:[])])}</Flow></div></div>;
    case "sync-async": return <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border-2 border-rose-300 bg-rose-50 p-3"><p className="mb-3 text-center text-xs font-extrabold uppercase text-rose-800">Synchronous · customer waits</p><Flow>{["validate","feature lookup","infer","decision"].flatMap((title,i,a)=>[<Node key={title} title={title} tone="rose"/>,...(i<a.length-1?[<Arrow key={`${title}-a`}/>]:[])])}</Flow></div><div className="rounded-2xl border-2 border-cyan-300 bg-cyan-50 p-3"><p className="mb-3 text-center text-xs font-extrabold uppercase text-cyan-800">Asynchronous · durable background work</p><Flow>{["log","label join","train","evaluate + release"].flatMap((title,i,a)=>[<Node key={title} title={title} tone="cyan"/>,...(i<a.length-1?[<Arrow key={`${title}-a`}/>]:[])])}</Flow></div></div>;
    case "degradation-routes": return <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-3"><Node title="Feature store unavailable" detail="use approved fresh-enough cache; otherwise review" tone="amber"/><Node title="Model times out" detail="cancel; deterministic rules; manual review" tone="rose"/><Node title="Duplicate event" detail="same idempotency key → return prior decision" tone="cyan"/></div><div className="grid gap-3 sm:grid-cols-2"><Node title="Bad canary metrics" detail="route traffic back to known-good model" tone="violet"/><Node title="All paths record" detail="request, data, feature, model, rule, and outcome versions" tone="emerald"/></div></div>;
  }
}

export function MLOpsFigure({ id }: { key?: React.Key; id: MLOpsVisualId }) {
  const item = meta[id];
  return <FigureShell figureProps={{ "data-mlops-figure": id }} title={item.title} learningQuestion={item.question} caption={<><strong>How to read it: </strong>{item.caption}</>}><VisualBody id={id}/></FigureShell>;
}
