import { FigureShell } from "../content/FigureShell";
import React, { type ReactNode } from "react";

export type ProjectVisualId =
  | "churn-pipeline" | "churn-threshold-matrix" | "churn-feature-influence"
  | "credit-workflow" | "credit-error-cost" | "credit-prediction-explanation"
  | "sales-timeline" | "sales-forecast" | "sales-residuals"
  | "image-transfer" | "image-curves" | "image-confusion"
  | "genai-architecture" | "genai-validation" | "genai-retry"
  | "rag-architecture" | "rag-retrieval" | "rag-quality-grid"
  | "agent-bounded" | "agent-memory-flow" | "agent-trace"
  | "multi-topology" | "multi-handoff" | "multi-tradeoff";

type Tone = "indigo" | "cyan" | "emerald" | "amber" | "rose" | "slate" | "violet";

const tones: Record<Tone, string> = {
  indigo: "border-indigo-300 bg-indigo-50 text-indigo-950",
  cyan: "border-cyan-300 bg-cyan-50 text-cyan-950",
  emerald: "border-emerald-300 bg-emerald-50 text-emerald-950",
  amber: "border-amber-300 bg-amber-50 text-amber-950",
  rose: "border-rose-300 bg-rose-50 text-rose-950",
  slate: "border-slate-300 bg-white text-slate-950",
  violet: "border-violet-300 bg-violet-50 text-violet-950",
};

function DiagramNode({ title, detail, tone = "indigo" }: { title: string; detail?: string; tone?: Tone }) {
  return <div className={`min-w-0 flex-1 rounded-xl border-2 px-3 py-3 text-center shadow-sm ${tones[tone]}`}><div className="text-sm font-extrabold leading-tight">{title}</div>{detail && <div className="mt-1 text-xs leading-snug opacity-80">{detail}</div>}</div>;
}

function Arrow({ label }: { label?: string }) {
  return <div className="flex shrink-0 flex-col items-center justify-center text-indigo-600" aria-hidden="true">{label && <span className="mb-0.5 text-[11px] font-bold text-slate-500">{label}</span>}<span className="text-2xl font-black leading-none max-sm:rotate-90">→</span></div>;
}

function Flow({ items }: { items: Array<{ title: string; detail?: string; tone?: Tone; arrow?: string }> }) {
  return <div className="grid gap-2 sm:flex sm:items-stretch">{items.flatMap((item, index) => [<React.Fragment key={`node-${item.title}`}><DiagramNode {...item} /></React.Fragment>, ...(index < items.length - 1 ? [<React.Fragment key={`arrow-${item.title}`}><Arrow label={item.arrow} /></React.Fragment>] : [])])}</div>;
}

const meta: Record<ProjectVisualId, { title: string; question: string; caption: string }> = {
  "churn-pipeline": { title: "From customer records to a monitored churn decision", question: "Where is each transformation learned, and where is it applied?", caption: "The split happens before preprocessing. The imputer, encoder, scaler and model learn only from training rows; the held-out test rows are transformed with those saved rules." },
  "churn-threshold-matrix": { title: "A threshold changes who receives retention help", question: "Why can the same probability model produce different business outcomes?", caption: "At 0.50 the example finds 3 of 4 churners and contacts 4 customers. At 0.30 it finds all 4 churners but contacts 6 customers, increasing false positives and campaign cost." },
  "churn-feature-influence": { title: "Feature influence explains direction, not destiny", question: "Which signals push the churn score up or down in the fitted baseline?", caption: "Positive bars raise the log-odds of churn; negative bars lower them. Coefficients describe the fitted sample and should not be interpreted as causal effects." },
  "credit-workflow": { title: "A credit-risk model supports a controlled decision process", question: "How does a score become a review recommendation without becoming an automatic lending verdict?", caption: "The model estimates risk from validated application fields. Policy, fairness checks and human review remain outside the model and retain decision authority." },
  "credit-error-cost": { title: "Rare defaults make error costs asymmetric", question: "Why is accuracy an unsafe headline metric for credit risk?", caption: "In 100 applications with 10 defaults, predicting everyone as non-default is 90% accurate yet misses every default. Threshold choice must consider both missed-default loss and unnecessary-review burden." },
  "credit-prediction-explanation": { title: "Explain one score as contributions around a baseline", question: "Where did this applicant's risk score move, feature by feature?", caption: "The example begins at a 0.22 portfolio baseline. High debt ratio and recent late payments raise risk; stable income and longer employment lower it, producing a final illustrative score of 0.41." },
  "sales-timeline": { title: "Forecasting respects time: past trains, future tests", question: "Why must the split preserve chronological order?", caption: "Training ends before validation begins, and validation ends before the final test horizon. Random shuffling would let future seasonal patterns leak into model development." },
  "sales-forecast": { title: "Actual sales versus two reproducible forecasts", question: "Does the stronger model improve on the naive last-value baseline?", caption: "The seasonal model follows the repeating pattern more closely than the flat naive forecast. MAE and RMSE below the chart must be computed only on the held-out horizon." },
  "sales-residuals": { title: "Residuals reveal when the forecast is systematically wrong", question: "Are errors centered near zero, or do they form a pattern?", caption: "Residual = actual − forecast. Mostly balanced dots around zero suggest no obvious bias; the large positive error in month 6 is a business event worth investigating." },
  "image-transfer": { title: "Transfer learning reuses visual features and replaces the task head", question: "Which parameters begin pretrained, frozen and newly initialized?", caption: "The backbone begins with pretrained weights. A new ten-class head starts randomly initialized; train it first, then optionally unfreeze only later backbone blocks with a smaller learning rate." },
  "image-curves": { title: "Training and validation curves diagnose learning", question: "What does the widening gap after epoch 5 mean?", caption: "Training loss continues down while validation loss turns upward. That gap is evidence of overfitting and a reason to stop, regularize or strengthen augmentation." },
  "image-confusion": { title: "A confusion matrix exposes class-specific image errors", question: "Which classes does the model confuse even when overall accuracy looks reasonable?", caption: "Rows are true classes and columns are predicted classes. The off-diagonal cat→dog and truck→car cells show where more representative examples or targeted augmentation may help." },
  "genai-architecture": { title: "A provider-neutral GenAI application keeps control outside the model", question: "Which layers remain deterministic around probabilistic generation?", caption: "Application code builds the prompt, calls an interchangeable provider adapter, validates the returned schema, applies safety policy and records outcome, latency and cost." },
  "genai-validation": { title: "Structured output is accepted only after deterministic checks", question: "What happens between raw model text and trusted application data?", caption: "Parsing checks syntax; schema validation checks fields and types; business rules check allowed values. Only validated data crosses into the application." },
  "genai-retry": { title: "Failures follow a bounded retry, fallback and review path", question: "How does the app recover without retrying forever?", caption: "Retry only transient or repairable failures, cap attempts, and use a safe fallback or human review when validation or policy still fails." },
  "rag-architecture": { title: "Document Q&A has an indexing path and an answering path", question: "Which work happens once, and which work happens for every question?", caption: "Documents are extracted, chunked, embedded and indexed ahead of time. Each question is embedded, retrieved, assembled with sources and passed to the generator." },
  "rag-retrieval": { title: "Chunk, retrieve, rank and build a bounded context", question: "How do chunk size, overlap and top-k change the evidence packet?", caption: "Overlapping chunks protect facts near boundaries. Similarity retrieves candidates; optional reranking improves order; the context builder keeps only the strongest evidence that fits the token budget." },
  "rag-quality-grid": { title: "Retrieval quality and answer quality are separate axes", question: "Why can a fluent answer still be a failed RAG result?", caption: "Good generation cannot repair missing evidence reliably. Evaluate whether the right chunk was retrieved and whether the answer stayed faithful to that chunk." },
  "agent-bounded": { title: "A bounded support agent operates inside an application shell", question: "Who chooses the next action, and who enforces limits?", caption: "The model proposes an answer, tool call or abstention. Trusted code validates tool arguments, enforces the step budget, records state and stops the run." },
  "agent-memory-flow": { title: "Tools, state and memory serve different jobs", question: "What is temporary, what persists, and what may change the outside world?", caption: "State tracks the current run; durable memory stores approved facts for later retrieval; tools read or change external systems through validated schemas." },
  "agent-trace": { title: "A trajectory makes success and safe abstention inspectable", question: "What evidence should an evaluator see after the run?", caption: "The successful trace finds an order and answers with evidence. The unsupported request exhausts neither permissions nor budget: it stops with a clear abstention." },
  "multi-topology": { title: "A coordinator delegates bounded work to specialized roles", question: "Where are tasks split, verified and synthesized?", caption: "The coordinator owns the plan and shared state. Researchers return evidence, the verifier checks claims and the synthesizer writes only from accepted findings." },
  "multi-handoff": { title: "Every handoff carries ownership, evidence and acceptance criteria", question: "What prevents delegated work from becoming an ambiguous message chain?", caption: "A task envelope names the owner, inputs, expected output, deadline or budget and done condition. The receiver accepts, rejects or requests clarification before work begins." },
  "multi-tradeoff": { title: "More agents can improve coverage while increasing coordination cost", question: "When does parallelism stop paying for itself?", caption: "The illustrative frontier improves quickly from one to three agents, then flattens while latency and cost continue rising. Choose the smallest team that meets measured quality needs." },
};

function Confusion({ labels = ["Stay", "Churn"], values = [[4, 1], [1, 3]] }: { labels?: string[]; values?: number[][] }) {
  const colors = [["bg-emerald-100", "bg-rose-100"], ["bg-amber-100", "bg-indigo-100"]];
  return <div className="mx-auto grid max-w-md grid-cols-[5.5rem_repeat(2,minmax(0,1fr))] gap-2 text-center text-xs sm:text-sm"><div /><div className="font-bold">Predicted {labels[0]}</div><div className="font-bold">Predicted {labels[1]}</div>{values.flatMap((row, r) => [<div key={`l-${r}`} className="flex items-center justify-end pr-2 font-bold">True {labels[r]}</div>, ...row.map((v, c) => <div key={`${r}-${c}`} className={`rounded-xl border border-slate-200 p-4 ${colors[r][c]}`}><div className="text-2xl font-black">{v}</div><div className="mt-1 text-slate-600">{r === c ? "correct" : "error"}</div></div>)])}</div>;
}

function LineChart({ kind }: { kind: "sales" | "curves" | "residuals" | "tradeoff" }) {
  if (kind === "residuals") return <svg viewBox="0 0 760 260" className="h-auto w-full" role="img" aria-label="Residual dots distributed around a zero line"><line x1="55" y1="125" x2="725" y2="125" stroke="#64748b" strokeWidth="2" strokeDasharray="8 7"/><line x1="55" y1="25" x2="55" y2="225" stroke="#94a3b8"/><line x1="55" y1="225" x2="725" y2="225" stroke="#94a3b8"/><text x="12" y="130" fontSize="14">0</text><text x="315" y="252" fontSize="14">Forecast month</text>{[[110,95],[190,145],[270,112],[350,158],[430,106],[510,48],[590,139],[670,119]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="8" fill={i===5?"#f43f5e":"#4f46e5"}/><text x={x-5} y="245" fontSize="12">{i+1}</text></g>)}</svg>;
  if (kind === "tradeoff") return <svg viewBox="0 0 760 300" className="h-auto w-full" role="img" aria-label="Quality improves then plateaus while cost and latency continue rising"><line x1="65" y1="245" x2="720" y2="245" stroke="#64748b" strokeWidth="2"/><line x1="65" y1="35" x2="65" y2="245" stroke="#64748b" strokeWidth="2"/><polyline points="80,220 230,125 380,78 530,62 680,57" fill="none" stroke="#10b981" strokeWidth="7"/><polyline points="80,225 230,195 380,155 530,105 680,45" fill="none" stroke="#f43f5e" strokeWidth="7"/><text x="520" y="52" fontSize="14" fill="#047857" fontWeight="700">quality plateaus</text><text x="535" y="125" fontSize="14" fill="#be123c" fontWeight="700">cost + latency</text><text x="285" y="285" fontSize="14">number of collaborating agents</text>{[1,2,3,4,5].map((n,i)=><text key={n} x={76+i*150} y="264" fontSize="13">{n}</text>)}</svg>;
  const actual = kind === "sales" ? "70,205 150,165 230,178 310,115 390,145 470,95 550,120 630,70 710,92" : "70,215 150,175 230,140 310,108 390,82 470,63 550,48 630,38 710,31";
  const second = kind === "sales" ? "70,210 150,190 230,168 310,132 390,136 470,105 550,110 630,82 710,88" : "70,218 150,180 230,148 310,120 390,101 470,92 550,96 630,112 710,138";
  return <svg viewBox="0 0 760 280" className="h-auto w-full" role="img" aria-label={kind === "sales" ? "Actual sales and forecast lines" : "Training and validation loss curves"}><line x1="55" y1="235" x2="725" y2="235" stroke="#64748b"/><line x1="55" y1="25" x2="55" y2="235" stroke="#64748b"/><polyline points={actual} fill="none" stroke="#4f46e5" strokeWidth="6"/><polyline points={second} fill="none" stroke="#f59e0b" strokeWidth="6"/><text x="75" y="35" fontSize="14" fill="#4338ca" fontWeight="700">{kind === "sales" ? "actual" : "training loss"}</text><text x="75" y="57" fontSize="14" fill="#b45309" fontWeight="700">{kind === "sales" ? "seasonal forecast" : "validation loss"}</text><text x="330" y="268" fontSize="14">{kind === "sales" ? "held-out month" : "epoch"}</text></svg>;
}

function Bars({ items }: { items: Array<[string, number, Tone]> }) {
  return <div className="space-y-3">{items.map(([label,value,tone])=><div key={label} className="grid grid-cols-[8rem_1fr_3rem] items-center gap-3 text-sm"><span className="font-semibold text-slate-700">{label}</span><div className="h-7 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full border ${tones[tone]}`} style={{width:`${Math.abs(value)*10}%`}} /></div><span className="font-mono text-xs font-bold">{value>0?"+":""}{value.toFixed(1)}</span></div>)}</div>;
}

function Body({ id }: { id: ProjectVisualId }) {
  switch (id) {
    case "churn-pipeline": return <Flow items={[{title:"Telco rows",detail:"features + churn label",tone:"slate"},{title:"Split",detail:"train 80% / test 20%",tone:"amber"},{title:"Fit preprocessing",detail:"impute + encode",tone:"cyan"},{title:"Train models",detail:"logistic + tree",tone:"violet"},{title:"Evaluate",detail:"threshold + business cost",tone:"emerald"}]} />;
    case "churn-threshold-matrix": return <div className="grid gap-6 lg:grid-cols-2"><div><h4 className="mb-3 text-center text-sm font-extrabold">Threshold 0.50</h4><Confusion /></div><div><h4 className="mb-3 text-center text-sm font-extrabold">Threshold 0.30</h4><Confusion values={[[2,3],[0,4]]}/></div></div>;
    case "churn-feature-influence": return <Bars items={[["Month-to-month",2.1,"rose"],["High charges",1.5,"rose"],["Short tenure",1.2,"amber"],["Two-year plan",-1.8,"emerald"],["Tech support",-1.0,"cyan"]]} />;
    case "credit-workflow": return <Flow items={[{title:"Application",detail:"validated borrower fields",tone:"slate"},{title:"Risk model",detail:"probability of default",tone:"violet"},{title:"Explanation",detail:"feature contributions",tone:"cyan"},{title:"Policy + fairness",detail:"independent controls",tone:"amber"},{title:"Human decision",detail:"approve / review / decline",tone:"emerald"}]} />;
    case "credit-error-cost": return <div className="grid gap-5 md:grid-cols-2"><div className="rounded-xl border p-4"><div className="mb-3 font-extrabold">100 applications</div><div className="flex h-12 overflow-hidden rounded-lg"><div className="flex w-[90%] items-center justify-center bg-emerald-200 font-bold">90 repay</div><div className="flex w-[10%] items-center justify-center bg-rose-300 text-xs font-bold">10 default</div></div><p className="mt-3 text-sm">Predicting “repay” for all = 90% accuracy, 0% default recall.</p></div><Bars items={[["Missed default",8.0,"rose"],["Extra review",2.0,"amber"]]} /></div>;
    case "credit-prediction-explanation": return <div><div className="mb-4 flex items-center justify-between rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white"><span>Portfolio baseline: 0.22</span><span>Applicant score: 0.41</span></div><Bars items={[["Debt ratio",1.5,"rose"],["Late payments",1.2,"rose"],["Stable income",-0.7,"emerald"],["Employment length",-0.4,"cyan"]]} /></div>;
    case "sales-timeline": return <div><div className="grid grid-cols-12 overflow-hidden rounded-xl border text-center text-xs font-bold"><div className="col-span-7 bg-indigo-100 p-5">TRAIN<br/>months 1–24</div><div className="col-span-2 bg-amber-100 p-5">VALIDATE<br/>25–30</div><div className="col-span-3 bg-emerald-100 p-5">TEST<br/>31–36</div></div><div className="mt-3 flex justify-between text-xs text-slate-600"><span>oldest evidence</span><span>forecast horizon →</span><span>newest unseen months</span></div></div>;
    case "sales-forecast": return <LineChart kind="sales" />;
    case "sales-residuals": return <LineChart kind="residuals" />;
    case "image-transfer": return <Flow items={[{title:"32×32×3 image",detail:"CIFAR-10 tensor",tone:"slate"},{title:"Pretrained backbone",detail:"general edges → shapes",tone:"cyan"},{title:"Frozen features",detail:"no update in stage 1",tone:"amber"},{title:"New head",detail:"10 output logits",tone:"violet"},{title:"Fine-tune",detail:"small learning rate",tone:"emerald"}]} />;
    case "image-curves": return <LineChart kind="curves" />;
    case "image-confusion": return <Confusion labels={["Cat", "Dog"]} values={[[38,12],[9,41]]} />;
    case "genai-architecture": return <Flow items={[{title:"User input",detail:"bounded request",tone:"slate"},{title:"Prompt builder",detail:"instructions + data",tone:"cyan"},{title:"Provider adapter",detail:"mock or real model",tone:"violet"},{title:"Validator",detail:"JSON + schema + policy",tone:"amber"},{title:"Application result",detail:"typed and logged",tone:"emerald"}]} />;
    case "genai-validation": return <div className="grid gap-3"><Flow items={[{title:"Raw text",detail:"probabilistic",tone:"rose"},{title:"Parse JSON",detail:"syntax",tone:"amber"},{title:"Check schema",detail:"fields + types",tone:"cyan"},{title:"Business rules",detail:"allowed values",tone:"violet"},{title:"Accept",detail:"trusted object",tone:"emerald"}]} /><div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-center text-sm font-bold text-rose-900">Any failed gate → repair request, fallback, or review</div></div>;
    case "genai-retry": return <div className="mx-auto grid max-w-2xl gap-3"><DiagramNode title="Call provider" detail="attempt 1 of 2"/><div className="grid grid-cols-2 gap-3"><DiagramNode title="Valid + safe" detail="return structured result" tone="emerald"/><DiagramNode title="Malformed / transient" detail="classify failure" tone="amber"/></div><div className="grid grid-cols-2 gap-3"><DiagramNode title="One bounded retry" detail="repair hint + backoff" tone="violet"/><DiagramNode title="Still invalid" detail="safe fallback / human review" tone="rose"/></div></div>;
    case "rag-architecture": return <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4"><h4 className="mb-3 text-center font-extrabold">Index once</h4><Flow items={[{title:"Docs"},{title:"Chunks"},{title:"Embeddings"},{title:"Local index"}]} /></div><div className="rounded-2xl border border-violet-200 bg-violet-50 p-4"><h4 className="mb-3 text-center font-extrabold">Answer each question</h4><Flow items={[{title:"Query"},{title:"Retrieve"},{title:"Context"},{title:"Answer + citations"}]} /></div></div>;
    case "rag-retrieval": return <Flow items={[{title:"600-token chunks",detail:"80-token overlap",tone:"slate"},{title:"Similarity search",detail:"top-k = 5",tone:"cyan"},{title:"Rerank",detail:"keep strongest 3",tone:"violet"},{title:"Context",detail:"source labels retained",tone:"amber"},{title:"Grounded answer",detail:"or insufficient evidence",tone:"emerald"}]} />;
    case "rag-quality-grid": return <div className="mx-auto grid max-w-2xl grid-cols-[7rem_repeat(2,1fr)] gap-2 text-center text-sm"><div/><div className="font-bold">Answer faithful</div><div className="font-bold">Answer unfaithful</div><div className="flex items-center font-bold">Evidence found</div><div className="rounded-xl bg-emerald-100 p-5 font-extrabold">Grounded success</div><div className="rounded-xl bg-amber-100 p-5 font-extrabold">Generation failure</div><div className="flex items-center font-bold">Evidence missed</div><div className="rounded-xl bg-amber-100 p-5 font-extrabold">Helpful abstention</div><div className="rounded-xl bg-rose-100 p-5 font-extrabold">Hallucination risk</div></div>;
    case "agent-bounded": return <div className="rounded-[2rem] border-2 border-dashed border-indigo-300 bg-indigo-50/40 p-4 sm:p-6"><Flow items={[{title:"Goal + instructions",tone:"slate"},{title:"Model decision",tone:"violet"},{title:"Validated tool",tone:"cyan"},{title:"Observation",tone:"amber"},{title:"Stop / continue",tone:"emerald"}]} /><div className="mt-4 rounded-xl bg-slate-900 px-4 py-3 text-center text-sm font-bold text-white">Trusted shell: tool allowlist • max 5 steps • approval • audit trace</div></div>;
    case "agent-memory-flow": return <div className="grid gap-4 md:grid-cols-3"><DiagramNode title="Current state" detail="goal, step, observations; ends with run" tone="indigo"/><DiagramNode title="Durable memory" detail="approved preference; persists across runs" tone="violet"/><DiagramNode title="Tools" detail="validated reads/writes to external systems" tone="cyan"/><div className="md:col-span-3 rounded-xl border border-amber-300 bg-amber-50 p-3 text-center text-sm font-bold">Context builder selects only relevant state, memory and tool results for the next decision.</div></div>;
    case "agent-trace": return <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border-2 border-emerald-300 bg-emerald-50 p-4"><h4 className="font-extrabold text-emerald-950">Successful trace</h4><ol className="mt-3 space-y-2 text-sm"><li>1. plan: inspect order</li><li>2. tool: get_order(1042)</li><li>3. observe: shipped</li><li>4. answer with evidence</li></ol></div><div className="rounded-xl border-2 border-rose-300 bg-rose-50 p-4"><h4 className="font-extrabold text-rose-950">Safe abstention trace</h4><ol className="mt-3 space-y-2 text-sm"><li>1. plan: search approved docs</li><li>2. tool: no supporting result</li><li>3. verify: insufficient evidence</li><li>4. abstain and escalate</li></ol></div></div>;
    case "multi-topology": return <div className="mx-auto max-w-3xl"><DiagramNode title="Coordinator / planner" detail="owns plan, budgets and shared state" tone="indigo"/><div className="my-2 text-center text-2xl font-black text-indigo-600">↙ ↓ ↘</div><div className="grid grid-cols-3 gap-3"><DiagramNode title="Researcher A" detail="source set 1" tone="cyan"/><DiagramNode title="Researcher B" detail="source set 2" tone="cyan"/><DiagramNode title="Verifier" detail="claims + evidence" tone="amber"/></div><div className="my-2 text-center text-2xl font-black text-indigo-600">↘ ↓ ↙</div><DiagramNode title="Synthesizer" detail="writes only accepted findings" tone="emerald"/></div>;
    case "multi-handoff": return <Flow items={[{title:"Assign",detail:"owner + question",tone:"indigo"},{title:"Accept",detail:"inputs understood",tone:"cyan"},{title:"Work",detail:"evidence + trace",tone:"violet"},{title:"Verify",detail:"criteria + conflicts",tone:"amber"},{title:"Close",detail:"result merged",tone:"emerald"}]} />;
    case "multi-tradeoff": return <LineChart kind="tradeoff" />;
  }
}

export function ProjectVisualFigure({ id }: { id: ProjectVisualId }) {
  const item = meta[id];
  return <FigureShell figureProps={{ "data-project-visual": id }} eyebrow="Project figure" title={item.title} learningQuestion={item.question} caption={item.caption}><Body id={id} /></FigureShell>;
}

export const projectVisualsByTopic: Record<string, ProjectVisualId[]> = {
  "project-customer-churn": ["churn-pipeline", "churn-threshold-matrix", "churn-feature-influence"],
  "project-credit-risk": ["credit-workflow", "credit-error-cost", "credit-prediction-explanation"],
  "project-sales-forecasting": ["sales-timeline", "sales-forecast", "sales-residuals"],
  "project-image-classification": ["image-transfer", "image-curves", "image-confusion"],
  "project-genai-app": ["genai-architecture", "genai-validation", "genai-retry"],
  "project-rag-document-qa": ["rag-architecture", "rag-retrieval", "rag-quality-grid"],
  "project-ai-agent": ["agent-bounded", "agent-memory-flow", "agent-trace"],
  "project-multi-agent-research": ["multi-topology", "multi-handoff", "multi-tradeoff"],
};
