import React from "react";
import { Link, useParams } from "react-router-dom";
import { CheckCircle2 } from "lucide-react";
import { MLOpsFigure, type MLOpsVisualId } from "../../components/diagrams/MLOpsDiagrams";
import { Callout } from "../../components/content/Callout";
import { CodeBlock as SharedCodeBlock, type CodeBlockType } from "../../components/content/CodeBlock";
import { DataTable } from "../../components/content/DataTable";
import { SummaryCard } from "../../components/lesson/SummaryCard";

type Row = string[];
type CodeKind = "RUNNABLE PYTHON" | "CONCEPTUAL PSEUDOCODE" | "ILLUSTRATIVE CONFIGURATION" | "ILLUSTRATIVE INFRASTRUCTURE FRAGMENT";
type Lesson = {
  opening: string[];
  objectives: string[];
  terms: Row[];
  conceptsTitle: string;
  concepts: string[];
  visuals: MLOpsVisualId[];
  tables: Array<{ title: string; headers: string[]; rows: Row[] }>;
  example: { title: string; given: string; steps: string[]; result: string };
  code: Array<{ title: string; kind: CodeKind; explanation: string; value: string }>;
  decisions: string[];
  failures: Row[];
  links: Array<[string, string, string]>;
  summary: string[];
};

const lessons: Record<string, Lesson> = {
  "ai-engineering-mlops": {
    opening: [
      "A notebook can prove that a model can learn from a saved dataset. It does not prove that tomorrow's data will have the same columns, that the correct feature values will be available during a live request, or that a failed release can be rolled back safely. AI engineering turns that promising calculation into an operating system around the model.",
      "Throughout this curriculum we will follow a customer-churn service. The business wants to identify customers who may cancel in the next 30 days so a retention team can offer help. The model is useful only when fresh customer data reaches it consistently, its prediction is delivered to the right workflow, and later outcomes reveal whether the intervention worked.",
      "MLOps is the set of engineering practices that makes the model lifecycle repeatable, testable, observable, and governed. AI engineering is broader product work: it connects models, data, software, people, and operating constraints into a useful AI capability. The names overlap in practice; the responsibilities matter more than the job title."
    ],
    objectives: ["Explain why model accuracy is only one production requirement", "Trace data from ingestion to a monitored prediction", "Distinguish data engineering, ML engineering, MLOps, and AI engineering", "Recognize the three planes of a production ML system", "Use the churn example to identify ownership and hand-offs"],
    terms: [["Data engineering", "Makes reliable, discoverable data available through ingestion, storage, quality checks, and transformations."], ["ML engineering", "Builds training and inference systems around models, features, evaluation, and software interfaces."], ["MLOps", "Applies automation, versioning, testing, release, monitoring, and governance across the ML lifecycle."], ["AI engineering", "Designs the whole AI-enabled product, including model choice, application logic, user experience, safety, cost, and operations."], ["Artifact", "An immutable output such as a trained model file, preprocessing object, or evaluation report."], ["Lineage", "The recorded chain connecting an output to the exact code, data, features, configuration, and environment that produced it."]],
    conceptsTitle: "The model is one component in a feedback system",
    concepts: [
      "For churn prediction, raw billing, product-usage, and support events first enter the data plane. Contracts check column names, types, ranges, timestamps, and duplicates before approved transformations calculate features such as monthly_spend and orders_last_30_days.",
      "The training plane joins historical features to known churn outcomes, trains candidate models, compares both predictive and operational metrics, and stores an immutable artifact. A registry records which candidate was reviewed and which version is allowed to serve—not merely where a file was saved.",
      "The serving plane obtains the same approved feature meanings, runs the production artifact, applies a decision policy, and records the prediction. Monitoring connects service health, input changes, prediction behaviour, and delayed churn outcomes. That evidence may justify a new training run, but it never bypasses evaluation and release gates.",
      "Governance crosses all three planes. It answers who owns the system, which data may be used, who can approve a model, which versions affected a decision, and who can stop or roll back the service during an incident."
    ],
    visuals: ["production-lifecycle", "three-planes"],
    tables: [
      { title: "Notebook prototype versus production AI system", headers: ["Concern", "Notebook prototype", "Production AI system"], rows: [["Input", "A saved, manually cleaned file", "Versioned batch/stream sources with contracts and freshness checks"], ["Features", "Calculated once in cells", "Shared, tested, versioned transformations for training and serving"], ["Model", "Object in memory or ad-hoc file", "Immutable artifact with lineage, metrics, approval state, and rollback"], ["Prediction", "Researcher calls predict()", "Batch job, API, or stream with an interface and latency/error contract"], ["Failure", "Rerun a cell", "Alert, retry, degrade safely, recover, and preserve evidence"], ["Quality", "One aggregate test score", "Slices, service metrics, data health, delayed outcomes, and business effect"], ["Ownership", "Notebook author", "Named owners for data, model, service, risk, release, and incident response"]] },
      { title: "Responsibilities overlap, but each lens asks a useful question", headers: ["Lens", "Primary question", "Churn example"], rows: [["Data engineering", "Can trusted data arrive on time?", "Billing and support events are complete and deduplicated."], ["ML engineering", "Can the model train and predict consistently?", "The same feature definitions work in historical and live contexts."], ["MLOps", "Can versions be tested, released, observed, and recovered?", "Candidate v13 is gated, canaried, monitored, and reversible."], ["AI engineering", "Does the complete product solve the user problem responsibly?", "The retention action is useful, timely, affordable, and governed."]] }
    ],
    example: { title: "Follow customer C17 from event to feedback", given: "Customer C17 has falling weekly usage, two recent support tickets, and an upcoming renewal. The current production artifact is churn-model v12.", steps: ["Validated source events create feature-set v4 for C17; the records keep event timestamps and source versions.", "The online service retrieves those approved values and model v12 returns churn probability 0.76.", "A reviewed business rule sends probabilities at or above 0.70 to the retention queue. The threshold is a product decision, not a fact learned by the model.", "The system records request ID, feature-set v4, model v12, probability 0.76, threshold 0.70, and the resulting action.", "Thirty days later the observed churn outcome is joined to the earlier prediction by customer and prediction time. It becomes monitoring evidence and, after point-in-time checks, possible training data."], result: "The prediction is reproducible because its data, feature, model, and policy versions are recorded. The business can now ask whether v12 helped customers like C17 rather than merely whether the endpoint returned HTTP 200." },
    code: [{ title: "Represent a prediction contract", kind: "ILLUSTRATIVE CONFIGURATION", explanation: "A production contract travels with the artifact. The values below are examples chosen by the team; they are not universal defaults.", value: `model_version: churn-v12\nfeature_set_version: churn-features-v4\ninput_schema: churn-request-v3\noutput:\n  probability: number_between_0_and_1\n  decision_threshold: 0.70\nowners:\n  model: retention-ml-team\n  service: customer-platform\nrollback_target: churn-v11` }],
    decisions: ["Start with the decision and user workflow, then choose the simplest model and serving mode that meet it.", "Assign ownership for every plane and every cross-plane contract; shared responsibility must not mean missing responsibility.", "Version data, features, code, environment, artifact, and decision policy together so an outcome can be reconstructed.", "Treat evaluation, release, monitoring, and rollback as product requirements before the first deployment."],
    failures: [["High offline accuracy, poor live decisions", "Feature skew, leakage, stale data, or a mismatched threshold", "Trace one live request through data, feature, model, and policy versions"], ["Predictions stop after a schema change", "Upstream contract changed without compatibility handling", "Block incompatible data; evolve schema deliberately; backfill after repair"], ["Cannot reproduce last month's result", "Missing code/data/environment lineage", "Make each run reference immutable inputs and outputs"], ["Bad model cannot be removed quickly", "No known-good version or traffic control", "Keep rollback target and exercise the rollback path"]],
    links: [["ML lifecycle", "/learn/ml-lifecycle", "Review the learning-stage lifecycle before adding production controls."], ["Customer churn project", "/learn/project-customer-churn", "See the modelling workflow that becomes this curriculum's running service."], ["Saving and deploying deep models", "/learn/saving-deploying-deep-models", "Compare general production concerns with neural-network artifact handling."]],
    summary: ["A good notebook result is evidence for a model idea, not proof of a reliable production system.", "Production quality depends on data, features, software, release controls, monitoring, people, and governance as well as accuracy.", "The data/feature, training/model-management, and serving/monitoring planes exchange versioned contracts and artifacts.", "AI engineering connects the whole product; MLOps makes the model lifecycle repeatable, testable, observable, and governable.", "A registry governs approved model versions and rollback state rather than acting as an ordinary file folder.", "Monitoring closes the loop by connecting service, data, predictions, delayed outcomes, and business effect.", "The churn example is reproducible only when data, feature, model, threshold, action, and outcome versions remain traceable."]
  },
  "ml-data-feature-pipelines": {
    opening: ["A model cannot correct a missing column, a duplicated payment event, or a feature that means one thing during training and another during prediction. Production data pipelines make inputs dependable; feature pipelines turn those inputs into consistent model-ready values.", "A pipeline is a dependency graph—a directed acyclic graph, or DAG—whose tasks run only when their required upstream outputs are ready. It also records time ranges, versions, attempts, and outcomes so failed work can be retried or historical periods can be backfilled safely."],
    objectives: ["Trace batch and streaming ingestion through validation and transformations", "Explain schema contracts, evolution, retries, and backfills", "Distinguish offline and online feature storage", "Diagnose training-serving skew with actual values", "Build point-in-time training rows without future leakage"],
    terms: [["Batch ingestion", "Moves a bounded collection on a schedule, such as yesterday's billing records."], ["Streaming ingestion", "Processes an ongoing sequence of timestamped events, usually with offsets or checkpoints."], ["Schema contract", "The agreed field names, types, null rules, ranges, and compatibility expectations."], ["Feature freshness", "How old a feature value is relative to the decision that needs it."], ["Backfill", "A deliberate rerun for a past time interval after logic or source data is repaired."], ["Point-in-time correctness", "Using only information that was available at the historical prediction time."], ["Training-serving skew", "A difference between how a feature is calculated or supplied during training and live inference."]],
    conceptsTitle: "Reliable features require meaning, time, and lineage",
    concepts: ["Ingestion identifies a source, event time, arrival time, and unique event key. Validation then checks schema, allowed categories, numeric ranges, missingness, timestamp sanity, and duplicates. A compatible optional column may be accepted; silently changing age from an integer in years to a string in months is not compatible evolution.", "Transformations clean and aggregate approved records. Each feature definition needs an owner, entity key, event-time rule, source lineage, version, freshness expectation, and safe missing-value behaviour. The field name alone is not a contract.", "An offline feature store retains historical values for training and batch scoring. An online store prioritizes fast access to the latest approved values for a live entity. A feature-store product is optional; the important concept is consistent, reusable feature definitions with different retrieval needs.", "Orchestration records dependencies. If validation fails, downstream feature and training tasks stay blocked. A transient task may retry with bounded backoff; a broken contract needs repair, not endless retry. A backfill explicitly recomputes dates or partitions affected by corrected logic."],
    visuals: ["pipeline-dag", "feature-stores", "training-serving-skew", "point-in-time"],
    tables: [{ title: "Offline and online feature serving", headers: ["Property", "Offline", "Online"], rows: [["Purpose", "Historical training, evaluation, and bulk scoring", "Low-latency features for one live entity"], ["Typical access", "Large scans and point-in-time joins", "Key lookup such as customer_id=C17"], ["Time coverage", "Many historical versions", "Latest approved value, sometimes short history"], ["Priority", "Correct history and throughput", "Freshness, latency, and availability"], ["Consistency control", "Same versioned feature definition", "Same versioned feature definition"], ["Failure response", "Stop/backfill affected partitions", "Use approved fallback, stale limit, or review path"]] }, { title: "Pipeline operations are not interchangeable", headers: ["Operation", "Use when", "Do not use when"], rows: [["Retry", "A transient request or worker failure is safe to repeat", "The schema or transformation logic is wrong"], ["Backfill", "Past partitions must be recomputed after a known repair", "You cannot identify the affected time range"], ["Skip", "An optional branch has an explicit policy", "A required validation failed"], ["Downstream run", "All required upstream contracts passed", "An input is incomplete merely because a timeout expired"]] }],
    example: { title: "Calculate skew and prevent future leakage", given: "Feature orders_last_30_days is defined for customer C17 at 1 June 10:00. Training reads completed web and mobile orders and counts 8. The online job accidentally reads only the mobile stream and counts 3.", steps: ["Training definition: count all completed orders with event time in the preceding 30-day window. The historical result is 8.", "Serving implementation: count mobile events only. Five valid web orders are missing, so the live result is 3.", "If a toy churn model uses score = 0.80 − 0.05 × orders_last_30_days, training-like input gives 0.80 − 0.05 × 8 = 0.40.", "The skewed live input gives 0.80 − 0.05 × 3 = 0.65. With a decision threshold of 0.60, the same customer changes from no alert to alert.", "For the historical row at 1 June 10:00, join only features known by that cutoff. A chargeback reported on 3 June may supply the later outcome label but must not enter the earlier features."], result: "The 0.25 score difference came from inconsistent data logic, not a changing model. Shared versioned feature code and parity tests reduce skew; event-time-aware joins prevent unrealistically good training results caused by future information." },
    code: [{ title: "Validate a small input contract", kind: "RUNNABLE PYTHON", explanation: "This transparent example rejects missing fields, impossible values, and duplicate event IDs before feature logic runs.", value: `REQUIRED = {"event_id", "customer_id", "event_time", "amount"}\n\ndef validate_event(event, seen_ids):\n    missing = REQUIRED - event.keys()\n    assert not missing, f"missing fields: {sorted(missing)}"\n    assert event["amount"] >= 0, "amount must be non-negative"\n    assert event["event_id"] not in seen_ids, "duplicate event"\n    seen_ids.add(event["event_id"])\n    return event\n\nseen = set()\nvalidate_event({"event_id":"e1", "customer_id":"C17",\n                "event_time":"2026-06-01T09:40:00Z", "amount":24.0}, seen)` }, { title: "Express point-in-time feature logic", kind: "CONCEPTUAL PSEUDOCODE", explanation: "The cutoff belongs to each training example. The join filters by event time before aggregating.", value: `for training_row in prediction_times:\n    eligible = orders.where(\n        order.customer_id == training_row.customer_id\n        and training_row.cutoff - 30_days <= order.event_time\n        and order.event_time <= training_row.cutoff\n        and order.status == "completed"\n    )\n    training_row.orders_last_30_days = count(eligible)` }],
    decisions: ["Use batch ingestion when bounded delay is acceptable; use streaming only when event freshness changes the decision enough to justify state and recovery complexity.", "Define compatibility rules for schema evolution rather than accepting or rejecting every change uniformly.", "Keep event time separate from arrival time so late events and point-in-time joins can be handled explicitly.", "Set feature freshness and missing-value policies from the decision risk; do not allow accidental framework defaults."],
    failures: [["Live score differs from replay", "Training-serving skew", "Compare raw inputs and feature versions for the same entity/time"], ["Offline metric is implausibly high", "Future leakage in join or split", "Rebuild rows using prediction-time cutoffs"], ["Count increases after retry", "Duplicate events are not idempotent", "Deduplicate by stable event key before aggregation"], ["Backfill corrupts new data", "Unbounded or non-versioned rewrite", "Write versioned output for an explicit range, validate, then promote"]],
    links: [["Feature engineering", "/learn/feature-engineering", "Review how raw variables become useful model inputs."], ["Handling missing data", "/learn/handling-missing-data", "Choose explicit missing-data strategies before production defaults."], ["Batch versus online learning", "/learn/batch-vs-online", "Separate model update cadence from prediction serving mode."]],
    summary: ["A production pipeline is a versioned dependency graph with contracts, run state, retries, and deliberate backfills.", "Batch and streaming ingestion differ in freshness, state, failure recovery, and complexity.", "Feature definitions require entity keys, time rules, sources, versions, freshness, and missing-value behaviour—not only names.", "Offline features preserve point-in-time history; online features serve approved current values with low latency.", "Training-serving skew occurs when the same feature meaning is implemented differently and can change the final decision.", "Point-in-time correctness prevents future facts from leaking into historical training inputs.", "Validation blocks bad inputs before downstream work; it does not prove that a statistically valid feature remains useful."]
  },
  "experiment-tracking-model-registry": {
    opening: ["Training a model creates a claim: with these exact inputs and settings, this artifact produced these measured results. Experiment tracking preserves the evidence behind that claim. A model registry then controls how an immutable candidate moves toward—or away from—production.", "A filename such as model_final_v2_really_final.pkl cannot answer which data, feature logic, dependency versions, random seed, or evaluation slices produced it. Renaming files is not model management."],
    objectives: ["Distinguish an experiment, run, artifact, metadata, and lineage", "Record enough evidence to reproduce a result", "Compare candidates with eligibility gates", "Use a registry as lifecycle governance", "Plan promotion, canary release, and rollback"],
    terms: [["Experiment", "A question or objective investigated through one or more runs."], ["Run", "One execution with fixed recorded inputs, parameters, outputs, timing, and status."], ["Parameter", "A developer-chosen training setting such as depth, regularization, or seed."], ["Metric", "A measured result such as recall, latency, or error rate."], ["Artifact", "A stored output such as model weights, preprocessing pipeline, plots, or report."], ["Metadata", "Descriptive facts—owner, time, versions, tags, status—attached to a run or artifact."], ["Registry", "A governed catalog of model versions, evidence, approval state, deployment state, and rollback relationships."]],
    conceptsTitle: "Reproducibility means reconstructing the complete run",
    concepts: ["A useful run record connects code version, immutable dataset snapshot, feature version, parameters, random seeds, dependency/environment lock, artifact checksum, metrics, and evaluation slices. Recording only parameters and a headline score leaves hidden variables uncontrolled.", "A random seed makes supported random operations repeatable, but it is not a magic guarantee. Hardware kernels, concurrency, external data, and library changes can still alter results. Reproducibility is an evidence discipline, not a single function call.", "Lineage lets an investigator move backward from a production prediction to model version and training run, then to feature definitions, data snapshot, code, and environment. It also moves forward: a bad source partition can reveal every candidate or prediction it affected.", "A registry is not merely object storage. It names lifecycle states and authorized transitions—registered candidate, evaluated, approved, canary, production, retired—and records who made each decision from which evidence."],
    visuals: ["experiment-lineage", "run-gates", "registry-lifecycle"],
    tables: [{ title: "Compare three tracked experiment runs", headers: ["Run", "Accuracy", "Recall", "Latency", "Eligibility"], rows: [["A", "0.91", "0.68", "35 ms", "Fail: recall < 0.75"], ["B", "0.90", "0.81", "42 ms", "Pass both gates"], ["C", "0.92", "0.79", "125 ms", "Fail: latency > 60 ms"]] }, { title: "Storage and registry answer different questions", headers: ["Capability", "Artifact storage", "Model registry"], rows: [["Keep model bytes", "Yes", "References or contains them"], ["Attach run lineage", "Optional metadata", "Required promotion evidence"], ["Lifecycle states", "Folder names at best", "Explicit governed states"], ["Approval history", "Not inherent", "Reviewer, time, evidence, decision"], ["Production identity", "Ambiguous latest file", "Named immutable version and deployment relationship"], ["Rollback", "Manually locate file", "Known-good predecessor with audit history"]] }],
    example: { title: "Select a production-eligible churn candidate", given: "The team requires recall ≥ 0.75 because missed churners are costly, and p95 inference latency ≤ 60 ms because predictions occur inside an interactive workflow. Runs A, B, and C have the table values above.", steps: ["Run A: recall 0.68 is below 0.75, so it fails even though latency 35 ms passes.", "Run B: recall 0.81 is at least 0.75 and latency 42 ms is at most 60 ms, so it is eligible.", "Run C: recall 0.79 passes, but latency 125 ms exceeds 60 ms, so it fails.", "Only Run B clears both hard constraints. Comparing accuracy among ineligible runs cannot override the requirements.", "Register Run B's immutable artifact with its complete lineage and evidence. Approval and a successful canary are still required before production."], result: "Run B—not the 0.92-accuracy Run C—is the eligible candidate. Selection translates product requirements into explicit gates before optimizing a preferred metric." },
    code: [{ title: "Record one vendor-neutral run manifest", kind: "RUNNABLE PYTHON", explanation: "A plain dictionary illustrates the minimum evidence connection. A tracking tool may store it, but the concepts do not depend on a vendor.", value: `run = {\n  "run_id": "R-204",\n  "code_version": "c41",\n  "dataset_version": "d19",\n  "feature_version": "v4",\n  "parameters": {"max_depth": 6, "seed": 42},\n  "environment_lock": "sha256:env-e7",\n  "artifact": {"uri": "models/churn/R-204.bin", "sha256": "..."},\n  "metrics": {"accuracy": 0.90, "recall": 0.81, "p95_ms": 42}\n}\neligible = run["metrics"]["recall"] >= 0.75 and run["metrics"]["p95_ms"] <= 60\nprint(eligible)  # True` }],
    decisions: ["Define experiment intent and acceptance criteria before running a large parameter search.", "Store immutable references or checksums, not mutable labels such as latest.csv.", "Apply hard safety, quality, and operational gates before ranking eligible candidates.", "Keep the production version and prior known-good version explicit so rollback is a tested transition."],
    failures: [["Metric cannot be reproduced", "Data, feature, code, seed, or environment version missing", "Make the run manifest complete and immutable"], ["Best aggregate metric harms a segment", "No slice evaluation", "Attach required cohort metrics to the promotion gate"], ["Registry says approved but evidence changed", "Mutable report or artifact", "Use checksums and immutable evaluation records"], ["Rollback loads incompatible preprocessing", "Model stored without its input contract", "Package/version preprocessing and schema with the artifact"]],
    links: [["Hyperparameter tuning", "/learn/hyperparameter-tuning", "Connect search trials to reproducible run records."], ["Model evaluation", "/learn/confusion-matrix", "Review why recall and error types can outweigh accuracy."], ["LLMOps", "/learn/llmops", "See application-level prompt, retrieval, and model versioning for LLM systems."]],
    summary: ["An experiment contains runs; each run connects fixed inputs and parameters to artifacts and measured outputs.", "Reproducibility requires code, data, features, parameters, environment, seed, artifact, and metrics—not a descriptive filename.", "A seed controls supported randomness but cannot compensate for changing data, dependencies, hardware behaviour, or hidden state.", "Lineage supports backward diagnosis and forward impact analysis across versions.", "Production eligibility gates encode minimum quality and operational constraints before candidates are ranked.", "The highest accuracy run may be ineligible when recall, latency, fairness, or reliability requirements fail.", "A model registry governs evidence, approval, release state, production identity, retirement, and rollback rather than only storing files."]
  },
  "batch-online-inference": {
    opening: ["Training creates a model artifact; inference uses that artifact to produce predictions. The correct inference architecture depends first on when predictions are needed: in bulk by a deadline, during one waiting request, or continuously as events arrive.", "Serving mode is separate from learning mode. A model may retrain weekly yet serve online every millisecond, or retrain daily and write one batch of scores nightly."],
    objectives: ["Compare batch, online, and streaming inference", "Separate training and inference pipelines", "Distinguish synchronous and asynchronous prediction", "Calculate throughput and completion time", "Allocate an end-to-end latency budget"],
    terms: [["Latency", "Elapsed time from a request or event becoming ready to its prediction becoming available."], ["Throughput", "Predictions completed per unit of time."], ["Synchronous", "The caller waits for the prediction before continuing."], ["Asynchronous", "The caller submits work and receives or reads the result later."], ["Queue", "A durable buffer that separates incoming work rate from worker processing rate."], ["SLA", "A service commitment; in this lesson, 100 ms is a chosen example target, not a universal number."]],
    conceptsTitle: "Serving architecture follows the timing contract",
    concepts: ["Batch inference reads a bounded input, partitions it across workers, writes versioned outputs, and records which partitions succeeded. It suits overnight churn scoring because the business needs all scores by morning, not one response per waiting user.", "Online inference usually sits behind an API. It validates one request, obtains fresh features, runs the model, applies decision logic, and responds within a stated latency target. Every synchronous dependency consumes the same end-to-end budget.", "A deployable inference unit combines the trained model artifact, its preprocessing or feature contract, compatible runtime dependencies, and the serving code and configuration. Packaging these pieces together makes dependency versions repeatable, prevents model/runtime incompatibility, and lets a release or rollback restore one known bundle. A container is one common packaging mechanism for keeping that environment consistent, but containers are not mandatory for every architecture and containerization is not the definition of MLOps.", "Streaming inference consumes an unbounded event stream. It may maintain state such as counts over a time window, track offsets, checkpoint progress, and write predictions continuously. Streaming is not simply a very frequent batch job; recovery and event ordering are explicit concerns.", "Queues allow asynchronous callers and absorb short bursts, but they do not create capacity. When arrival rate remains above processing rate, queue depth and waiting time keep growing. Backpressure slows or rejects producers before overload becomes uncontrolled."],
    visuals: ["inference-modes", "latency-budget"],
    tables: [{ title: "Choose an inference mode from the operating need", headers: ["Dimension", "Batch", "Online", "Streaming"], rows: [["Example", "Score all customers overnight", "Score one transaction during API request", "Score each event from a continuous topic"], ["Latency", "Minutes/hours by deadline", "Milliseconds/seconds per request", "Low event-to-result delay"], ["Throughput", "High bulk efficiency", "Handles concurrent requests", "Sustained event rate"], ["Freshness", "Snapshot at run time", "Latest available request/features", "Continuous event/state updates"], ["Scaling", "More partitions/workers", "Replicas, load balancing, autoscaling", "Partitions and stateful consumers"], ["Recovery", "Retry failed partitions", "Timeout, retry policy, fallback", "Offsets, checkpoint, replay, deduplication"], ["Consistency risk", "Snapshot/version mismatch", "Feature and model mismatch", "Ordering, late, or duplicate events"], ["Complexity/cost", "Often simplest per prediction", "Pays for ready capacity", "Highest state/operations complexity"]] }, { title: "Training and inference pipelines have different outputs", headers: ["Pipeline", "Consumes", "Produces", "Success means"], rows: [["Training", "Historical features + labels", "Evaluated candidate artifact", "Reproducible evidence and eligible model"], ["Inference", "Approved current inputs + production artifact", "Prediction + metadata", "Correct contract within freshness/latency/reliability target"]] }],
    example: { title: "Estimate a 10-million-row batch", given: "There are 10,000,000 predictions. Average model compute is 4 ms = 0.004 seconds per prediction. Assume 20 workers are identical, perfectly utilized, and work divides evenly. Ignore data loading, network, startup, writing, failures, and coordination.", steps: ["Sequential compute = 10,000,000 × 0.004 seconds = 40,000 seconds.", "With 20 perfectly utilized parallel workers, ideal wall time = 40,000 ÷ 20 = 2,000 seconds.", "Convert seconds: 2,000 ÷ 60 = 33.333... minutes, or approximately 33 minutes 20 seconds.", "This is an optimistic compute-only lower bound. Real elapsed time adds input/output, startup, skewed partitions, retries, and spare capacity.", "An online 100 ms SLA asks a different question: one request's complete dependency chain must finish within 0.100 seconds. A high-throughput batch worker that waits to fill large batches may violate that per-request target."], result: "The toy batch can finish model compute in about 33 minutes 20 seconds under ideal assumptions. The same design is not automatically appropriate for an online endpoint because bulk throughput and individual latency optimize different goals." },
    code: [{ title: "Score batch partitions with restartable outputs", kind: "CONCEPTUAL PSEUDOCODE", explanation: "Each partition records input, model, feature, and output versions so a failed partition can be retried without rescoring successful work.", value: `for partition in uncompleted_partitions(run_id):\n    rows = read_snapshot(input_version, partition)\n    features = transform(rows, feature_version)\n    scores = model.predict(features)\n    write_atomic(run_id, partition, scores, model_version)\n    mark_complete(run_id, partition)` }, { title: "Make the online contract explicit", kind: "ILLUSTRATIVE CONFIGURATION", explanation: "The total is an application target allocated across dependencies. Teams measure actual percentiles and revise these budgets.", value: `endpoint: POST /v1/churn-score\ntotal_sla_ms: 100\ntimeouts_ms:\n  feature_lookup: 30\n  model_inference: 40\n  total_internal: 90\nfallback: manual_review\nlog_versions: [request_schema, features, model, policy]` }],
    decisions: ["Use the least complex mode that satisfies prediction freshness and response timing.", "Keep work asynchronous when no user or transaction must wait for it.", "Measure p50, p95, and p99 latency; an average can hide slow requests that violate the experience.", "Plan overload behaviour—queue, shed, degrade, or scale—before traffic exceeds capacity."],
    failures: [["Batch misses deadline", "I/O, skew, retries, or insufficient workers ignored", "Measure stage times; repartition; add bounded capacity"], ["Online p95 exceeds target", "Slow feature dependency or cold model", "Break down the latency budget by span"], ["Streaming duplicates decisions", "Replay without idempotency", "Use event IDs and deterministic output keys"], ["Queue grows continuously", "Arrival rate exceeds service rate", "Apply backpressure, increase safe capacity, or reduce work"]],
    links: [["Batch versus online learning", "/learn/batch-vs-online", "Do not confuse update cadence with inference serving mode."], ["Efficient LLM serving", "/learn/efficient-llm-serving", "See token-generation-specific serving techniques."], ["GenAI deployment", "/learn/genai-deployment", "Compare hosted and self-hosted generative application serving."]],
    summary: ["Training produces an evaluated artifact; inference applies an approved artifact to current inputs.", "Batch inference optimizes bulk completion by a deadline, online inference optimizes waiting-request latency, and streaming inference continuously handles events and state.", "Synchronous callers wait for a result; asynchronous work can be queued and completed later.", "Latency measures elapsed response time, while throughput measures completed predictions per unit time.", "Twenty ideal workers reduce 40,000 seconds of compute to 2,000 seconds—about 33 minutes 20 seconds—under deliberately simplified assumptions.", "A 100 ms online SLA covers validation, feature lookup, inference, policy, network, and serialization, not only model compute.", "Queues absorb temporary bursts but sustained overload requires backpressure, scaling, reduced work, or controlled rejection."]
  },
  "ml-cicd-continuous-training": {
    opening: ["Ordinary software tests whether code behaves as expected. ML systems also depend on changing data, feature meaning, statistical behaviour, artifact compatibility, and delayed outcomes. A deployment can therefore have perfectly valid code and still produce a worse model.", "CI, CD, and CT automate different parts of the lifecycle. Continuous integration validates changes; continuous delivery or deployment moves an approved release; continuous training produces a new candidate when an approved trigger justifies it. None of them means releasing every change automatically."],
    objectives: ["Design code, data, feature, model, and integration tests", "Separate CI, CD, and CT responsibilities", "Trace an evaluated release pipeline", "Stop deployment when a model regression test fails", "Explain why drift alone must not trigger blind retraining"],
    terms: [["CI", "Continuous Integration: merge small changes frequently and run automated validation on the integrated code."], ["Continuous Delivery", "Keep an approved release ready for a deliberate production decision."], ["Continuous Deployment", "Automatically promote a release that passes every required control."], ["CT", "Continuous Training: run a repeatable candidate-training workflow from an approved trigger."], ["Regression test", "Checks that a new change has not broken previously accepted behaviour."], ["Golden example", "A stable input with an expected deterministic or bounded output used to detect unintended change."], ["Canary", "A release exposed to a small controlled portion of traffic before broader rollout."]],
    conceptsTitle: "Testing creates gates across the entire ML contract",
    concepts: ["Code tests cover transformations, utility functions, and the inference interface. Data tests cover schema, ranges, missingness, category membership, timestamps, and duplicates. They answer different questions: correct function logic versus acceptable input.", "Feature tests verify expected calculations, freshness, and parity between historical and serving paths. Model tests enforce minimum metrics, slice requirements, regression limits, and deterministic examples where appropriate. Integration tests load the real preprocessing and artifact together and exercise the endpoint contract.", "A complete release path is code or approved data change → tests → train candidate → evaluate → register → approve → shadow or canary → production → monitor. Each transition records evidence and retains the current production artifact until the new one proves safe.", "CT may start on a schedule, enough new labelled data, measured performance decay, or an approved drift investigation. Drift alone says the input distribution changed; retraining on corrupt, biased, or unlabelled data can make the system worse."],
    visuals: ["test-layers", "cicdct-flow", "release-gate"],
    tables: [{ title: "Each test layer protects a different contract", headers: ["Test type", "Example assertion", "Failure means"], rows: [["Code", "normalize_age(40) returns expected value", "Function or interface logic changed"], ["Data", "age exists, is numeric, and is within reviewed bounds", "Incoming data violates its contract"], ["Feature", "historical and live orders_last_30_days agree for a replay case", "Feature meaning or freshness diverged"], ["Model", "recall ≥ 0.75 overall and required slices do not regress", "Candidate behaviour is not release-eligible"], ["Integration", "preprocessor v4 loads with model v13 and endpoint schema v3", "Combined artifact/service contract is broken"]] }, { title: "CI, CD, and CT have different outputs", headers: ["Practice", "Starts from", "Produces", "Must not imply"], rows: [["CI", "Code/configuration change", "Validated package and test evidence", "The model is good enough for production"], ["CD", "Approved release candidate", "Controlled delivery/deployment and rollback evidence", "Every passing build gets all traffic"], ["CT", "Approved schedule/data/performance trigger", "Evaluated new model candidate", "Drift automatically retrains and releases"]] }],
    example: { title: "A valid dataset still produces a rejected candidate", given: "The incoming data passes schema, range, missingness, and duplicate checks. The current production model has recall 0.78 on the fixed release set. The candidate has recall 0.71; the required minimum is 0.75 and regression beyond 0.02 is prohibited.", steps: ["Data gate passes: the records are structurally acceptable. This says nothing yet about candidate quality.", "Training completes and produces a loadable artifact with recorded lineage.", "Minimum metric gate: 0.71 < 0.75, so the candidate fails.", "Regression check: 0.78 − 0.71 = 0.07 decline, which is greater than the allowed 0.02. It fails again.", "The pipeline records the failed evidence, does not promote the candidate, and leaves the current production version serving."], result: "Deployment stops even though data validation and training succeeded. Layered tests prevent one kind of success from being mistaken for complete release readiness." },
    code: [{ title: "Write separate data and model assertions", kind: "RUNNABLE PYTHON", explanation: "These checks show why a passing data contract cannot override a failed model gate.", value: `def validate_rows(rows):\n    assert rows, "dataset is empty"\n    assert all(0 <= r["age"] <= 120 for r in rows)\n    assert len({r["event_id"] for r in rows}) == len(rows)\n\ndef validate_candidate(metrics, production_metrics):\n    assert metrics["recall"] >= 0.75\n    assert production_metrics["recall"] - metrics["recall"] <= 0.02\n\nvalidate_rows([{"event_id":"e1", "age":41}])       # passes\nvalidate_candidate({"recall":0.71}, {"recall":0.78}) # fails` }, { title: "Describe an evidence-driven CT trigger", kind: "CONCEPTUAL PSEUDOCODE", explanation: "The drift alert begins diagnosis. Candidate training starts only after evidence and approval satisfy the policy.", value: `on drift_alert:\n    verify pipeline and source health\n    wait for sufficient outcome labels\n    compare production performance and required slices\n    if persistent material degradation is confirmed and retraining is approved:\n        train candidate\n        run all release tests\n        register and canary only if every gate passes` }],
    decisions: ["Choose tests from plausible failures and product risk, not only from easy-to-measure functions.", "Keep fixed release sets and golden cases versioned; refresh them through review rather than silently.", "Separate candidate creation from approval and traffic release.", "Automate reversible low-risk steps first; keep explicit approval where consequences or evidence uncertainty are high."],
    failures: [["All unit tests pass, endpoint crashes", "Artifact/preprocessor contract untested", "Add integration load and request/response tests"], ["Aggregate metric passes, region fails", "No slice gate", "Require relevant segment thresholds and sample support"], ["Every drift alert retrains", "CT trigger confuses change with degradation", "Investigate, wait for outcomes, and evaluate candidate"], ["Canary is bad but rollout continues", "No automatic stop/rollback criteria", "Predefine guardrail metrics and traffic reversal"]],
    links: [["Train/test split", "/learn/train-test-split", "Protect release evidence from training contamination."], ["Model evaluation", "/learn/roc-auc", "Select metrics that match error costs."], ["LLM evaluation", "/learn/llm-evaluation", "See additional testing concerns for probabilistic language systems."]],
    summary: ["ML testing covers code, data, features, model behaviour, and integration because each can fail independently.", "A passing data contract proves structural acceptability, not that a trained candidate meets quality requirements.", "CI validates integrated changes, CD controls an approved release, and CT creates a newly trained candidate.", "Candidate creation, evaluation, approval, canary release, and production promotion are separate governed transitions.", "Drift is an investigation signal; automatic retraining on unverified data can amplify defects or bias.", "A candidate with recall 0.71 is correctly blocked when the minimum is 0.75, even though its data and artifact are valid.", "Every release pipeline needs explicit stop conditions, preserved evidence, a known-good production version, and tested rollback."]
  },
  "ml-monitoring-drift": {
    opening: ["A production model can return fast, valid responses while becoming less useful. Monitoring must therefore look beyond server uptime to the data arriving, the predictions produced, and the real outcomes that may arrive days or months later.", "Drift means a distribution changed. It is a clue, not a verdict. A seasonal customer mix can drift while model quality remains acceptable; a stable-looking aggregate can hide severe decay for one region or device."],
    objectives: ["Monitor service, data, predictions, and outcomes separately", "Distinguish covariate, label/prior, and concept drift", "Calculate a small illustrative PSI", "Use delayed labels and slices responsibly", "Follow an evidence-driven retraining decision"],
    terms: [["Covariate/data drift", "The distribution of input X changes, such as monthly_spend shifting."], ["Label/prior drift", "The frequency of outcome y changes, such as the churn rate rising."], ["Concept drift", "The relationship P(y|X) changes, so the same inputs imply a different outcome risk."], ["Calibration", "Whether predicted probabilities match observed frequencies; among predictions near 0.7, roughly 70% should be positive when calibrated."], ["Delayed label", "A ground-truth outcome observed after the prediction, such as churn 30 days later."], ["Slice", "A meaningful subgroup such as region, device, customer segment, or model version."], ["PSI", "Population Stability Index, a binned distribution-change summary used here only as an illustrative diagnostic."]],
    conceptsTitle: "Four layers prevent one signal from telling the whole story",
    concepts: ["Service monitoring asks whether requests can be served: rate, error, latency, saturation, CPU/GPU/memory, and queue depth. Data monitoring asks whether inputs satisfy schema, missingness, ranges, categories, freshness, and expected distributions.", "Operational freshness adds useful investigation signals: record the age of the serving model, the timestamp of the last successful approved training run, the last successful required data or feature refresh, and any stalled pipeline or run status. Model or pipeline age does not prove quality degradation and does not automatically justify retraining. A recent model may be bad and an older model may still perform correctly, so decisions still require actual data, outcome, quality, and release-evaluation evidence.", "Prediction monitoring observes score distributions, confidence, calibration estimates, abstentions, and predicted class balance. It can detect sudden behaviour before labels arrive, but it cannot prove correctness without outcomes.", "Outcome monitoring joins later labels to the original prediction and calculates accuracy, precision, recall, calibration, false-positive/false-negative cost, and business KPIs. The join must use prediction time and recorded versions; using a later feature snapshot would confuse diagnosis.", "Slice monitoring repeats important measures by region, customer segment, device, model version, and data-source version. A small slice needs uncertainty and sample-count context; noisy variation must not trigger unsupported conclusions."],
    visuals: ["monitoring-layers", "psi-shift", "retraining-decision"],
    tables: [{ title: "Drift types answer different questions", headers: ["Type", "What changed", "Example", "What it does not prove"], rows: [["Covariate/data", "P(X)", "More customers have high monthly_spend", "That predictions are now wrong"], ["Label/prior", "P(y)", "Churn prevalence rises from 8% to 13%", "Why prevalence changed"], ["Concept", "P(y|X)", "The same usage pattern now implies greater churn risk", "That input distributions must also move"]] }, { title: "Monitoring layers and responses", headers: ["Layer", "Signals", "First question"], rows: [["Service", "rate, errors, latency, saturation, resources, queue", "Can the system serve correctly and on time?"], ["Data", "schema, missingness, ranges, categories, freshness, drift", "Did the input or pipeline change?"], ["Prediction", "score/class distribution, confidence, calibration proxy, abstention", "Is model behaviour changing before labels arrive?"], ["Outcome", "quality metrics, error cost, business KPI", "Did usefulness actually degrade when truth became known?"]] }],
    example: { title: "Calculate an illustrative three-bin PSI", given: "Expected proportions are [0.50, 0.30, 0.20]. Current proportions are [0.40, 0.35, 0.25]. For each bin use contribution = (current − expected) × ln(current / expected), then sum. All proportions are non-zero.", steps: ["Bin 1: (0.40 − 0.50) × ln(0.40/0.50) = −0.10 × ln(0.80) = −0.10 × −0.2231 ≈ 0.02231.", "Bin 2: (0.35 − 0.30) × ln(0.35/0.30) = 0.05 × ln(1.1667) = 0.05 × 0.1542 ≈ 0.00771.", "Bin 3: (0.25 − 0.20) × ln(0.25/0.20) = 0.05 × ln(1.25) = 0.05 × 0.2231 ≈ 0.01116.", "PSI ≈ 0.02231 + 0.00771 + 0.01116 = 0.04118, rounded to 0.0412.", "Interpret the value against a baseline, sample size, binning method, seasonality, and use-case-calibrated alert policy. Do not treat one copied threshold as universal."], result: "The positive contributions summarize movement across these bins. PSI detects distribution difference; it does not identify the cause or prove that predictive performance declined." },
    code: [{ title: "Calculate PSI transparently", kind: "RUNNABLE PYTHON", explanation: "The code exposes each contribution. Production implementations must define bin edges from an approved reference and handle zero proportions deliberately.", value: `from math import log\n\nexpected = [0.50, 0.30, 0.20]\ncurrent = [0.40, 0.35, 0.25]\ncontributions = []\nfor e, c in zip(expected, current):\n    assert e > 0 and c > 0\n    contributions.append((c - e) * log(c / e))\n\nprint([round(x, 5) for x in contributions])\nprint(round(sum(contributions), 4))\n# [0.02231, 0.00771, 0.01116]\n# 0.0412` }],
    decisions: ["Alert on sustained, material changes with sample-size context rather than every noisy fluctuation.", "Use outcome metrics when labels arrive; use data and prediction signals as earlier but weaker evidence.", "Calibrate thresholds by feature, population, seasonality, error cost, and response capability.", "Record model, feature, data-source, policy, and monitoring versions beside every prediction and outcome."],
    failures: [["Latency healthy, model harms users", "Only infrastructure is monitored", "Add predictions, outcomes, slices, and business cost"], ["Drift alert causes needless retrain", "Change treated as proof of decay", "Investigate pipeline, persistence, and labelled performance"], ["Overall metric stable, one group degrades", "Aggregate hides slices", "Monitor meaningful segments with sample counts"], ["Outcome join is wrong", "Delayed label linked to latest instead of original prediction", "Join by entity and prediction/cutoff time with version lineage"]],
    links: [["Data visualization", "/learn/data-visualization", "Review distributions before constructing monitoring views."], ["Bias–variance", "/learn/bias-variance", "Connect generalization error with changing production data."], ["Agent observability", "/learn/agent-observability-deployment", "See trace-level monitoring for multi-step agents."]],
    summary: ["Production monitoring combines service, data, prediction, and delayed outcome evidence.", "Covariate drift changes P(X), label drift changes P(y), and concept drift changes P(y|X); the terms are not interchangeable.", "Drift is evidence of distribution change, not automatic proof that model performance failed.", "Delayed labels must be joined to the original prediction time and recorded versions before outcome metrics are trustworthy.", "Slices can reveal regional, segment, device, model-version, or source-version failures hidden by aggregates.", "The illustrative three-bin PSI is about 0.0412, and its meaning depends on reference, bins, sample size, seasonality, and use case.", "Retraining is justified only after diagnosis, persistent degradation evidence, candidate evaluation, and controlled release gates."]
  },
  "production-ai-reliability": {
    opening: ["A production AI system must remain predictable when dependencies slow down, inputs are duplicated, traffic spikes, secrets rotate, or a new artifact fails. Reliability means controlling failure—not pretending failure will never happen.", "Security, cost, and governance are architectural concerns. A cheap service that exposes personal data is unacceptable; a secure model with no rollback owner is incomplete; an accurate endpoint that collapses during bursts is not reliable."],
    objectives: ["Explain SLI, SLO, and SLA at beginner level", "Design timeout, retry, backpressure, and fallback behaviour", "Map trust and supply-chain boundaries", "Calculate cost per 1,000 predictions", "Connect ownership, approval, audit, incident response, and rollback"],
    terms: [["SLI", "Service Level Indicator: a measured value such as successful-response rate or p95 latency."], ["SLO", "Service Level Objective: an internal target for an SLI over a defined window."], ["SLA", "Service Level Agreement: a commitment with users/customers, often including consequences."], ["Backoff", "Increasing or spaced delay between bounded retries to avoid amplifying an outage."], ["Backpressure", "Signals or limits that slow/reject new work when downstream capacity is saturated."], ["Idempotency", "Repeating the same logical request does not create an additional side effect."], ["Risk tier", "A classification that determines required review, evidence, controls, and monitoring."]],
    conceptsTitle: "Reliability has a safe path for overload and dependency failure",
    concepts: ["Availability is the fraction of intended time or requests that the service can fulfill. Redundancy removes a single point of failure, but duplicate capacity alone is not enough: traffic routing, health checks, data consistency, and recovery must also work.", "Every external call needs a timeout. Retry only transient operations that are safe to repeat, use bounded attempts with backoff and jitter, and preserve idempotency for side effects. A circuit breaker stops repeatedly calling a dependency already known to be failing.", "Queues smooth short bursts and support asynchronous recovery. Backpressure caps producers or rejects low-priority work when consumers cannot keep up. Graceful degradation returns a safer reduced service—cached eligible results, deterministic rules, or human review—instead of silently guessing.", "Security applies least privilege to people and services, keeps secrets outside code and client bundles, encrypts sensitive data in transit and at rest, and protects artifact integrity. Checksums, signatures, dependency inventories, and controlled registries reduce model supply-chain risk.", "Governance records intended use, owner, risk tier, training lineage, evaluation, approval, model card/documentation, deployed version, incidents, and rollback responsibility. Compliance requirements depend on jurisdiction and use; they must be identified with qualified organizational guidance."],
    visuals: ["reliability-fallback", "security-boundaries", "cost-comparison"],
    tables: [{ title: "SLI, SLO, and SLA in one example", headers: ["Term", "Meaning", "Illustrative churn-service example"], rows: [["SLI", "What is measured", "Percentage of valid requests completed in ≤100 ms"], ["SLO", "Internal target over a window", "99.5% meet 100 ms over 30 days"], ["SLA", "External commitment", "Contractual availability/response promise and remedy"]] }, { title: "Failure needs an explicit bounded response", headers: ["Failure", "Unsafe reaction", "Designed response"], rows: [["Feature service timeout", "Wait forever or guess missing values", "Deadline; approved cache if fresh; otherwise review/fallback"], ["Transient model worker error", "Unbounded immediate retries", "Small idempotent retry budget with backoff"], ["Sustained overload", "Accept everything until collapse", "Backpressure, priority, scaling, or controlled rejection"], ["Bad release", "Patch in place without evidence", "Stop rollout and route to immutable known-good version"], ["Regional outage", "Assume replica is reachable", "Tested failover/recovery plan and reconciled state"]] }],
    example: { title: "Compare toy cost per 1,000 predictions", given: "Assume full utilization for one hour. Design A costs $0.80/hour and serves 80 predictions/second. Design B costs $2.00/hour and serves 300 predictions/second. Ignore storage, network, idle time, failures, and other services.", steps: ["Design A throughput per hour = 80 × 3,600 = 288,000 predictions.", "Design A cost per 1,000 = $0.80 ÷ (288,000/1,000) = $0.80 ÷ 288 ≈ $0.00278.", "Design B throughput per hour = 300 × 3,600 = 1,080,000 predictions.", "Design B cost per 1,000 = $2.00 ÷ (1,080,000/1,000) = $2.00 ÷ 1,080 ≈ $0.00185.", "Under these toy assumptions B has the lower unit compute cost, despite the higher hourly price. Actual cost depends on utilization, idle capacity, autoscaling, batches, storage, data transfer, and recovery capacity."], result: "Cost per prediction is a rate, not the instance price. Design B is cheaper per 1,000 at full utilization, but architecture selection still includes accuracy, latency, reliability, hardware availability, burst traffic, and risk." },
    code: [{ title: "Route a timed-out prediction safely", kind: "CONCEPTUAL PSEUDOCODE", explanation: "Fallback order is a reviewed product policy. It never converts a missing prediction into blind approval.", value: `try:\n    prediction = model_service.predict(request, timeout_ms=60)\n    return apply_policy(prediction)\nexcept Timeout:\n    open_circuit_after_repeated_failures()\n    if approved_cache.is_fresh_for(request.entity):\n        return apply_policy(approved_cache.get(request.entity))\n    if deterministic_rules.can_decide(request):\n        return deterministic_rules.decide(request)\n    return route_to_manual_review(reason="model unavailable")` }],
    decisions: ["Choose SLOs from user impact and measurable service behaviour; do not copy a fashionable percentage.", "Reserve capacity and fallbacks according to risk, traffic bursts, and recovery time rather than theoretical average load.", "Calculate cost per accepted useful prediction, including idle and failure overhead—not only raw model calls.", "Assign named owners for data, artifact, release, security, business policy, incident command, and rollback."],
    failures: [["Retry storm worsens outage", "Immediate unbounded retries", "Bound attempts; backoff/jitter; circuit break"], ["Duplicate request charges twice", "No idempotency key", "Persist logical request key and prior receipt"], ["Model artifact is altered", "Integrity not verified", "Immutable checksum/signature and controlled registry"], ["Incident stalls", "No owner or rollback authority", "Document roles, escalation, runbook, and exercises"]],
    links: [["GenAI deployment", "/learn/genai-deployment", "Apply these system principles to generative applications."], ["Agent security", "/learn/agent-security", "Study tool and instruction risks specific to agents."], ["Agent observability", "/learn/agent-observability-deployment", "See trace, latency, and cost evidence for multi-step execution."]],
    summary: ["Reliability controls failure through redundancy, deadlines, bounded retries, backpressure, fallbacks, and tested recovery.", "An SLI is a measurement, an SLO is an internal target, and an SLA is an external commitment.", "Retries require transient failure classification, backoff, bounded attempts, and idempotency so they do not amplify harm.", "Least privilege, secret management, encryption, PII controls, and artifact integrity protect the production trust chain.", "At full toy utilization, Design A costs about $0.00278 and Design B about $0.00185 per 1,000 predictions.", "Unit cost alone cannot decide an architecture because accuracy, latency, burst capacity, reliability, and risk also matter.", "Governance makes ownership, intended use, lineage, approval, audit, incident response, and rollback responsibility explicit."]
  },
  "ml-system-design": {
    opening: ["System design turns business requirements into data paths, service boundaries, failure behaviour, and measurable contracts. The goal is not to draw the most boxes; it is to explain what must happen, when it must happen, what can fail, and how evidence returns to improve the system.", "Our synthesis system scores card transactions for fraud in real time. It must respond quickly without treating every model score as a final truth. A decision policy combines prediction, threshold, deterministic business rules, and a manual-review path."],
    objectives: ["Translate functional and non-functional requirements into architecture", "Separate synchronous decisions from asynchronous learning", "Design feature, model, duplicate-event, and timeout fallbacks", "Prevent leakage with delayed fraud labels", "Calculate capacity and plan release/rollback lineage"],
    terms: [["Functional requirement", "What the system must do, such as return approve, review, or reject for each transaction."], ["Non-functional requirement", "How well it must operate: latency, throughput, availability, security, cost, recovery, or auditability."], ["Decision policy", "Reviewed logic that converts model evidence and business constraints into an action."], ["Headroom", "Capacity above expected load for bursts, failures, maintenance, and estimation error."], ["Idempotency key", "Stable identity for one logical transaction so retries or duplicate delivery reuse the prior decision."], ["Canary release", "A candidate receives limited traffic while guardrails are compared with the current version."], ["Rollback", "Route traffic back to a known-good immutable version when release criteria fail."]],
    conceptsTitle: "Start with the decision deadline, then attach the learning loop",
    concepts: ["The synchronous path validates the transaction, deduplicates its identity, reads fresh real-time features, obtains a model score, and applies threshold plus business rules. Only these operations belong on the customer-facing deadline because the approve/review/reject result cannot be returned without them.", "Prediction logging is initiated on the live path but written durably without making slow analytics block the response. Monitoring, delayed fraud labels, training-dataset construction, candidate training, evaluation, registry approval, canary analysis, and broad release are asynchronous.", "If the online feature store is unavailable, use only a reviewed fallback: a fresh-enough cache with recorded age, a model designed for a reduced feature set, deterministic high-risk rules, or manual review. If the model times out, do not blindly approve; cancel it and follow the degraded decision policy.", "Stream duplicates are handled with a stable transaction/idempotency key and a stored prior outcome. Delayed labels join to the original transaction and prediction timestamp. Features for a historical row are cut off at that time; the later fraud report is the label, never an earlier feature.", "A candidate release records code, training data, feature definitions, environment, artifact, metrics, threshold, rules, and runtime versions. Shadow or canary evidence decides promotion. Rollback changes traffic to the previous known-good bundle while preserving the incident trail."],
    visuals: ["fraud-architecture", "sync-async", "degradation-routes"],
    tables: [{ title: "Requirements become measurable design decisions", headers: ["Requirement", "Design response", "Evidence"], rows: [["Low decision latency", "Short synchronous path; dependency deadlines", "End-to-end and per-stage p95/p99"], ["2,000 requests/sec peak", "Replicas, load balancing, headroom, backpressure", "Load test and saturation curve"], ["Fresh behavioural features", "Event-time stream aggregation + online lookup", "Feature age and source checkpoint"], ["No duplicate side effect", "Transaction idempotency key and prior receipt", "Duplicate/replay test"], ["Delayed fraud truth", "Versioned prediction log + later label join", "Join coverage, delay distribution, label version"], ["Safe model release", "Eligibility gates, canary, known-good rollback", "Release and rollback traces"], ["Auditable decision", "Record feature/model/policy versions and reason", "Reconstruct one transaction end to end"]] }, { title: "Ten system-design questions answered", headers: ["Question", "Answer for this system"], rows: [["1 · What is synchronous?", "Validation, deduplication lookup, online features, inference, and decision policy."], ["2 · What is asynchronous?", "Analytics logs, labels, monitoring, training, evaluation, and release workflows."], ["3 · Feature store unavailable?", "Approved fresh cache or reduced-feature/rule path; otherwise review."], ["4 · Model times out?", "Cancel; apply deterministic safety rules or manual review—never blind approval."], ["5 · Stream duplicates?", "Reuse transaction idempotency key and stored outcome."], ["6 · Delayed labels joined?", "Join to transaction/prediction event time and immutable identifiers."], ["7 · Leakage prevented?", "Point-in-time feature cutoff; later fraud report is label only."], ["8 · Candidate released?", "Offline gates → registry approval → shadow/canary → gradual traffic."], ["9 · Rollback?", "Route to prior immutable model-feature-policy bundle."], ["10 · Versions recorded?", "Code, data, feature, environment, model, schema, threshold, rules, and runtime."]] }],
    example: { title: "Calculate minimum theoretical serving capacity", given: "Peak traffic is 2,000 requests/second. One model instance safely handles 250 requests/second under the approved latency target. Assume perfect balancing and no failed or unavailable instance for the theoretical calculation.", steps: ["Required theoretical count = peak rate ÷ safe per-instance rate.", "2,000 ÷ 250 = 8 instances.", "Check: 8 × 250 = 2,000 requests/second, exactly equal to the stated peak.", "Eight leaves no capacity for a burst above forecast, one failed instance, deployment replacement, maintenance, or estimation error. Losing one leaves 7 × 250 = 1,750 requests/second.", "Production therefore provisions more than the theoretical minimum or defines controlled load shedding. The amount of headroom is chosen from failure tolerance, burst data, scaling delay, SLO, and cost—not a universal percentage."], result: "Eight is the minimum mathematical count under ideal assumptions, not a safe production plan. Capacity design includes redundancy, scaling time, overload policy, and validated latency at load." },
    code: [{ title: "Make the fraud decision path explicit", kind: "CONCEPTUAL PSEUDOCODE", explanation: "The model produces evidence; trusted policy produces the action. Every branch writes a versioned reason and uses the transaction key idempotently.", value: `def decide(transaction):\n    prior = decisions.get(transaction.idempotency_key)\n    if prior:\n        return prior\n    validated = validate(transaction)\n    features = feature_service.get(validated.card_id, deadline_ms=25)\n    if not features:\n        return persist_and_review(validated, "features_unavailable")\n    score = model.predict(features, deadline_ms=35)\n    if score is None:\n        return apply_reviewed_fallback(validated)\n    action = policy.apply(score, validated, threshold_version="t7")\n    return persist_once(action, versions=current_versions())` }, { title: "Describe the release bundle", kind: "ILLUSTRATIVE CONFIGURATION", explanation: "Rollback must restore compatible components, not only model bytes.", value: `release: fraud-v23\nmodel_artifact: model-v23\nfeature_contract: fraud-features-v8\nrequest_schema: transaction-v5\ndecision_policy: policy-v7\nthreshold: 0.82\nruntime_image: sha256:runtime-19\nrollback_bundle: fraud-v22\ncanary_guardrails: [p95_latency, error_rate, review_rate, confirmed_loss]` }],
    decisions: ["Write functional and non-functional requirements, traffic assumptions, data availability, and error costs before choosing components.", "Keep the synchronous path minimal and time-bounded; make durable learning work asynchronous.", "Define a safe degraded result for every critical dependency and test it under realistic load.", "Record compatible bundles of model, features, schema, policy, threshold, and runtime so release and rollback remain coherent."],
    failures: [["Fraudulent transaction approved during timeout", "No safe degradation policy", "Rules/manual review; never default high-risk absence to approval"], ["Duplicate transaction creates two actions", "No idempotency record", "Stable key, atomic prior-decision lookup/write"], ["Offline test is unrealistically high", "Delayed label or future event leaked into features", "Point-in-time dataset builder and temporal split"], ["Rollback still errors", "Old model paired with new incompatible features", "Version and restore a complete compatible release bundle"], ["Eight instances overload after one failure", "Theoretical minimum treated as capacity plan", "Provision evidence-based headroom and load shedding"]],
    links: [["Customer churn project", "/learn/project-customer-churn", "Apply the lifecycle to a classical ML project."], ["RAG project", "/learn/project-rag-document-qa", "Compare retrieval and evidence failures in a generative system."], ["Multi-agent project", "/learn/project-multi-agent-research", "Compare multi-step coordination and observability trade-offs."]],
    summary: ["System design begins with the user decision, functional requirements, non-functional requirements, and explicit assumptions.", "Real-time validation, deduplication, feature lookup, inference, and decision policy form the synchronous fraud path.", "Logging, delayed labels, monitoring, dataset creation, training, evaluation, and release belong to durable asynchronous workflows.", "Feature or model failure must route to reviewed cache, reduced capability, deterministic rules, or manual review—not blind approval.", "Point-in-time joins keep delayed fraud labels out of earlier features and preserve leakage-safe training data.", "Eight instances are the theoretical minimum for 2,000 requests/second at 250 each, but production needs evidence-based failure and burst headroom.", "Safe release and rollback require lineage for the compatible model, feature, schema, threshold, policy, data, code, environment, and runtime bundle."]
  }
};

function Table({ title, headers, rows }: { key?: React.Key; title: string; headers: string[]; rows: Row[] }) {
  return <DataTable title={title} caption={title} headers={headers} rows={rows} />;
}

function Cards({ items }: { items: string[] }) { return <div className="not-prose grid gap-3 md:grid-cols-2">{items.map(item=><div key={item} className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-indigo-600"/><span className="text-sm leading-relaxed text-slate-700">{item}</span></div>)}</div>; }

function CodeBlock({ title, kind, explanation, value }: { key?: React.Key; title: string; kind: CodeKind; explanation: string; value: string }) {
  const type: CodeBlockType = kind === "RUNNABLE PYTHON"
    ? "runnable"
    : kind === "CONCEPTUAL PSEUDOCODE"
      ? "pseudocode"
      : "config";
  return <section><h3 className="mb-2 text-xl font-extrabold text-slate-900">{title}</h3><p className="mb-4 leading-relaxed text-slate-700">{explanation}</p><div data-code-kind={kind}><SharedCodeBlock title={title} type={type} typeLabel={kind} language={kind === "RUNNABLE PYTHON" ? "Python" : undefined} code={value} /></div></section>;
}

export function MLOpsContent() {
  const { topicId = "" } = useParams<{ topicId: string }>();
  const lesson = lessons[topicId];
  if (!lesson) return null;
  const firstVisuals = lesson.visuals.slice(0, 2);
  const remainingVisuals = lesson.visuals.slice(2);
  return <div className="space-y-12" data-mlops-lesson={topicId}>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why This Topic Exists</h2><div className="space-y-4">{lesson.opening.map(p=><p key={p} className="text-lg leading-relaxed text-slate-700">{p}</p>)}</div></section>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What You Will Be Able to Explain</h2><Cards items={lesson.objectives}/></section>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Terms Before the Architecture</h2><p className="mb-5 leading-relaxed text-slate-700">These terms name different responsibilities. Read the meaning before following them through the diagrams and worked example.</p><Table title="Core vocabulary" headers={["Term", "Meaning in this lesson"]} rows={lesson.terms}/></section>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">{lesson.conceptsTitle}</h2><div className="space-y-4">{lesson.concepts.map(p=><p key={p} className="leading-relaxed text-slate-700">{p}</p>)}</div>{firstVisuals.map(id=><MLOpsFigure key={id} id={id}/>)}</section>
    <section><h2 className="mb-5 text-2xl font-bold text-indigo-800">Compare the Design Choices</h2><div className="space-y-7">{lesson.tables.map(table=><Table key={table.title} {...table}/>)}</div></section>
    <section data-mlops-worked-example><h2 className="mb-4 text-2xl font-bold text-indigo-800">Worked Example: {lesson.example.title}</h2><div className="not-prose rounded-2xl border border-indigo-200 bg-indigo-50/50 p-5 sm:p-6"><p className="font-semibold leading-relaxed text-slate-800"><strong className="text-indigo-900">Given: </strong>{lesson.example.given}</p><ol className="mt-5 space-y-3">{lesson.example.steps.map((step,index)=><li key={step} className="grid grid-cols-[2rem_minmax(0,1fr)] gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600 text-sm font-bold text-white">{index+1}</span><span className="pt-1 text-sm leading-relaxed text-slate-700">{step}</span></li>)}</ol><p className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 leading-relaxed text-slate-700"><strong className="text-emerald-900">Result and interpretation: </strong>{lesson.example.result}</p></div></section>
    {remainingVisuals.length>0&&<section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Use the Evidence to Make the Next Decision</h2><p className="leading-relaxed text-slate-700">The following figures turn the example into an operational decision. Follow every branch and note which state is recorded before work continues.</p>{remainingVisuals.map(id=><MLOpsFigure key={id} id={id}/>)}</section>}
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Practical Implementation</h2><p className="mb-6 leading-relaxed text-slate-700">The label above each block states what it is. Runnable Python can be executed as shown with the standard library; pseudocode and configuration communicate architecture and require adaptation to a real platform.</p><div className="space-y-8">{lesson.code.map(block=><CodeBlock key={block.title} {...block}/>)}</div></section>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Production Decisions to Make Explicit</h2><Cards items={lesson.decisions}/><Callout role="tip" className="mt-5"><p>A tool or platform can automate a chosen policy, but it cannot decide the correct latency, freshness, quality, risk, ownership, or fallback policy for your product.</p></Callout></section>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Failure Analysis and Recovery</h2><Table title="Observed failure → likely cause → controlled response" headers={["Observed failure", "Likely cause", "Response"]} rows={lesson.failures}/><Callout role="mistake" className="mt-5"><p>Do not hide missing evidence behind a fluent prediction. Stop, degrade, retry, roll back, or request review according to a pre-approved policy and record the reason.</p></Callout></section>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Connect to Earlier Lessons</h2><div className="not-prose grid gap-3 md:grid-cols-3">{lesson.links.map(([label,route,detail])=><Link key={route} to={route} className="rounded-xl border border-indigo-200 bg-indigo-50 p-4 hover:bg-indigo-100"><strong className="block text-sm text-indigo-900">{label}</strong><span className="mt-1 block text-xs leading-relaxed text-slate-600">{detail}</span></Link>)}</div></section>
    <div data-mlops-summary><SummaryCard items={lesson.summary} className="mt-0" /></div>
  </div>;
}

export const mlopsLessonIds = Object.keys(lessons);
