import React from "react";

function AutoencoderArchitectureFigure() {
  const input = ["x₁","x₂","x₃","x₄","x₅","x₆"];
  const latent = ["z₁","z₂"];
  const output = ["x̂₁","x̂₂","x̂₃","x̂₄","x̂₅","x̂₆"];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">An autoencoder learns an input → code → reconstruction journey</p><p className="mt-1 text-sm text-slate-600">Only the reconstruction is compared with the target during basic training.</p></div><div className="overflow-x-auto p-5 md:p-7"><div className="flex min-w-[850px] items-center justify-center gap-8"><div><p className="mb-3 text-center text-xs font-bold uppercase text-blue-700">input x</p><div className="grid grid-cols-2 gap-2">{input.map(v=><span key={v} className="rounded-lg bg-blue-100 px-4 py-3 text-center font-mono font-bold text-blue-900">{v}</span>)}</div></div><div className="text-center"><p className="mb-2 text-xs font-bold text-slate-500">encoder f<sub>θ</sub></p><p className="text-4xl font-black text-indigo-400">→</p><p className="mt-2 text-xs text-slate-500">compress useful structure</p></div><div className="rounded-3xl border-2 border-violet-500 bg-violet-100 p-6"><p className="mb-3 text-center text-xs font-bold uppercase text-violet-800">latent code z</p><div className="flex gap-2">{latent.map(v=><span key={v} className="rounded-full bg-violet-700 p-4 font-mono font-bold text-white">{v}</span>)}</div><p className="mt-3 text-center text-xs text-violet-800">bottleneck</p></div><div className="text-center"><p className="mb-2 text-xs font-bold text-slate-500">decoder g<sub>φ</sub></p><p className="text-4xl font-black text-indigo-400">→</p><p className="mt-2 text-xs text-slate-500">reconstruct the input</p></div><div><p className="mb-3 text-center text-xs font-bold uppercase text-emerald-700">output x̂</p><div className="grid grid-cols-2 gap-2">{output.map(v=><span key={v} className="rounded-lg bg-emerald-100 px-4 py-3 text-center font-mono font-bold text-emerald-900">{v}</span>)}</div></div></div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">The encoder converts x into latent representation z=f<sub>θ</sub>(x). The decoder reconstructs x̂=g<sub>φ</sub>(z). Parameters θ and φ are updated together to reduce reconstruction error.</figcaption></figure>;
}

function DenoisingFigure() {
  const clean = [0,0,1,1,1,0,0];
  const noisy = [0.2,0.1,0.9,0.6,1,0.25,0.1];
  const rebuilt = [0.05,0.08,0.88,0.91,0.86,0.12,0.04];
  const Row = ({values,color}:{values:number[]; color:string}) => <div className="flex gap-1">{values.map((v,i)=><div key={i} className="h-12 flex-1 rounded border border-slate-300" style={{backgroundColor:`rgba(${color},${0.08+v*0.85})`}}><span className="flex h-full items-center justify-center font-mono text-[10px] font-bold text-slate-800">{v}</span></div>)}</div>;
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">A denoising autoencoder receives corruption but targets clean data</p><div className="mt-5 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr] md:items-center"><div><p className="mb-2 text-xs font-bold uppercase text-rose-700">noisy input x̃</p><Row values={noisy} color="244,63,94" /></div><span className="text-center text-3xl font-black text-slate-400">→</span><div className="rounded-xl bg-indigo-800 p-5 text-center font-bold text-white">encoder<br /><span className="text-indigo-200">+</span><br />decoder</div><span className="text-center text-3xl font-black text-slate-400">→</span><div><p className="mb-2 text-xs font-bold uppercase text-emerald-700">reconstruction x̂</p><Row values={rebuilt} color="16,185,129" /></div></div><div className="mt-5"><p className="mb-2 text-xs font-bold uppercase text-blue-700">clean training target x</p><Row values={clean} color="59,130,246" /></div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">Loss compares the reconstruction with the clean target, not with the corrupted input. The corruption process should resemble noise the deployed system must handle without removing important signal.</figcaption></figure>;
}

function AnomalyFigure() {
  const normal = [0.03,0.06,0.08,0.11,0.13,0.16,0.18];
  const anomalies = [0.25,0.31,0.37,0.44];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">Reconstruction error can become an anomaly score</p><div className="relative mt-8 h-40 rounded-xl border-b-2 border-slate-400 bg-slate-50"><div className="absolute inset-y-0 border-l-2 border-dashed border-amber-500" style={{left:"47%"}}><span className="absolute -left-12 -top-6 whitespace-nowrap text-xs font-bold text-amber-700">threshold τ=0.22</span></div>{normal.map((v,i)=><div key={`n-${i}`} className="absolute bottom-8 h-5 w-5 rounded-full border-2 border-blue-700 bg-blue-200" style={{left:`${8+v*100}%`,bottom:`${25+(i%3)*25}px`}} title={String(v)} />)}{anomalies.map((v,i)=><div key={`a-${i}`} className="absolute bottom-8 h-5 w-5 rotate-45 border-2 border-rose-700 bg-rose-300" style={{left:`${8+v*100}%`,bottom:`${35+(i%2)*30}px`}} title={String(v)} />)}<span className="absolute bottom-1 left-3 text-xs font-bold text-blue-700">lower reconstruction error</span><span className="absolute bottom-1 right-3 text-xs font-bold text-rose-700">higher error</span></div><div className="mt-3 flex gap-5 text-xs"><span className="text-blue-800">● validation normal</span><span className="text-rose-800">◆ known anomaly</span></div><figcaption className="mt-4 text-sm leading-relaxed text-slate-600">Choose the threshold on held-out representative data according to false-alarm and missed-anomaly costs. Training loss alone cannot choose a safe operating point.</figcaption></figure>;
}

function VAEFigure() {
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">A variational autoencoder encodes a distribution, then samples</p></div><div className="overflow-x-auto p-5 md:p-6"><div className="flex min-w-[840px] items-center gap-4"><div className="rounded-xl bg-blue-100 p-5 text-center font-bold text-blue-950">input x</div><span className="text-2xl font-black text-slate-400">→</span><div className="rounded-xl bg-indigo-100 p-5 text-center text-indigo-950"><strong>encoder</strong><br /><span className="text-xs">q<sub>φ</sub>(z|x)</span></div><span className="text-2xl font-black text-slate-400">→</span><div className="space-y-2"><p className="rounded-lg bg-violet-100 px-5 py-3 font-mono font-bold text-violet-950">μ(x)</p><p className="rounded-lg bg-violet-100 px-5 py-3 font-mono font-bold text-violet-950">log σ²(x)</p></div><span className="text-2xl font-black text-slate-400">→</span><div className="rounded-full border-2 border-fuchsia-500 bg-fuchsia-100 p-5 text-center font-mono font-bold text-fuchsia-950">z=μ+σ⊙ε<br /><span className="text-xs">ε~N(0,I)</span></div><span className="text-2xl font-black text-slate-400">→</span><div className="rounded-xl bg-emerald-100 p-5 text-center text-emerald-950"><strong>decoder</strong><br /><span className="text-xs">p<sub>θ</sub>(x|z)</span></div><span className="text-2xl font-black text-slate-400">→</span><div className="rounded-xl bg-amber-100 p-5 text-center font-bold text-amber-950">x̂</div></div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">The reparameterization writes randomness as ε while μ and σ remain differentiable functions of the input. Training balances reconstruction with a KL term that regularizes the approximate posterior toward the chosen prior.</figcaption></figure>;
}

const variants = [
  ["Undercomplete", "Latent dimension smaller than input", "Compression/feature learning baseline", "May discard task-relevant detail"],
  ["Sparse", "Penalty encourages few active code units", "Interpretable-ish specialized features", "Sparsity strength needs tuning"],
  ["Denoising", "Corrupted input, clean target", "Noise removal and robust representation", "Learns only corruption represented in training"],
  ["Convolutional", "Spatial convolutions in encoder/decoder", "Images and spatial signals", "Upsampling can create artifacts"],
  ["Sequence", "RNN/Transformer encoder and decoder", "Time series or sequential reconstruction", "Masking and length handling are critical"],
  ["Variational (VAE)", "Distribution parameters and latent sampling", "Smooth probabilistic generation/representation", "Reconstructions may be blurrier; posterior collapse"],
] as const;

export function AutoencodersContent() {
  return <div className="prose prose-lg max-w-none text-slate-700">
    <section className="not-prose mb-10 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-violet-950 to-fuchsia-800 px-6 py-10 text-white shadow-xl md:px-10 md:py-12"><p className="mb-3 text-sm font-extrabold uppercase tracking-[0.18em] text-fuchsia-200">Deep Learning · Representation Learning</p><p className="mt-5 max-w-4xl text-lg leading-relaxed text-violet-50 md:text-xl">An autoencoder learns to reconstruct data through an internal representation. That simple objective can support compression, denoising, feature learning and anomaly detection—but only when the architecture or training task prevents meaningless copying. We will calculate reconstruction loss, compare bottlenecks and regularization, set up anomaly scoring, and derive the sampling and KL terms that turn a deterministic autoencoder into a variational one.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Learning Without a Separate Class Label</h2><p className="text-lg leading-relaxed">Imagine thousands of machine-vibration windows but no labels saying which internal patterns matter. We can create a training target from the data itself: present a window x and ask a network to reproduce it as x̂. The labels are therefore not human classes; the target is the original signal or a clean version of it.</p><p className="text-lg leading-relaxed">The <strong>encoder</strong> maps input x to a latent code z. The <strong>decoder</strong> maps z back to reconstruction x̂. If the code or training task is constrained appropriately, reconstruction forces z to preserve regular structure in the data.</p><AutoencoderArchitectureFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Reconstruction Loss Measures What Was Lost</h2><p className="text-lg leading-relaxed">For continuous, scaled features, mean squared error (MSE) is a common starting reconstruction loss. It subtracts each reconstructed value from its original, squares the difference so positive and negative errors cannot cancel, then averages so examples with different feature counts remain comparable. The output activation and loss must match the data range and likelihood assumption; binary cross-entropy is not automatically correct merely because pixels were scaled to [0,1].</p><div className="not-prose rounded-2xl bg-slate-950 p-5 text-white md:p-6"><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-fuchsia-300">Mean squared reconstruction error</p><p className="mt-2 overflow-x-auto whitespace-nowrap font-mono text-xl font-bold">L<sub>recon</sub> = (1/d) Σ<sub>j=1</sub><sup>d</sup>(x<sub>j</sub> − x̂<sub>j</sub>)²</p><p className="mt-3 text-sm leading-relaxed text-slate-200">d is the number of reconstructed values; x<sub>j</sub> comes from the training example, x̂<sub>j</sub> is produced by the decoder, and the loss is calculated from them—not selected by the developer.</p></div><div className="not-prose mt-5 rounded-2xl border border-indigo-200 bg-indigo-50 p-5 md:p-6"><h3 className="text-xl font-bold text-indigo-950">A three-feature reconstruction</h3><p className="mt-2 text-slate-700">Use teaching input x=[1.0,0.5,0.0] and a hypothetical decoder output x̂=[0.8,0.4,0.1]. In a real run, x comes from the dataset and x̂ changes as training changes the network weights.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><p className="rounded-lg bg-white p-4 font-mono text-sm">errors<br />[1−0.8, .5−.4, 0−.1]<br />= [0.2,0.1,−0.1]</p><p className="rounded-lg bg-white p-4 font-mono text-sm">squared errors<br />[0.04,0.01,0.01]<br />sum = 0.06</p><p className="rounded-lg bg-white p-4 font-mono text-sm">MSE = 0.06/3<br />= <strong>0.02</strong></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> the average squared reconstruction miss is 0.02 on this scale. Whether that is good requires comparison with validation data and a task baseline.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why a Powerful Autoencoder Can Learn to Copy</h2><p className="text-lg leading-relaxed">If encoder and decoder have enough capacity and an unconstrained code, the easiest solution can approach an identity function: pass every detail through without discovering reusable structure. Low training reconstruction error alone therefore does not prove that the latent code is meaningful.</p><div className="not-prose grid gap-4 md:grid-cols-3">{[["Narrow bottleneck","Use fewer latent dimensions so the code cannot carry every raw value.","Too narrow can underfit."],["Sparse activity","Add a penalty so only a small subset of latent units activates per example.","Penalty strength controls the trade-off."],["Denoising task","Corrupt the input but reconstruct the clean target, so copying noise is not rewarded.","Corruption must preserve the desired content."]].map(([title,body,caution])=><div key={title} className="rounded-xl border border-violet-200 bg-violet-50 p-5"><p className="font-bold text-violet-950">{title}</p><p className="mt-2 text-sm leading-relaxed text-violet-900">{body}</p><p className="mt-3 text-xs font-bold text-rose-700">{caution}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Denoising Changes the Learning Question</h2><p className="text-lg leading-relaxed">A denoising autoencoder learns “recover the clean structure from a corrupted observation,” not simply “copy the input.” For scanned documents, corruption might simulate speckle, fading or sensor noise. The noisy version is the network input x̃, while the original clean item remains the target x.</p><DenoisingFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Anomaly Detection Uses Error Carefully</h2><p className="text-lg leading-relaxed">If an autoencoder is trained mostly on normal machine behavior, it may reconstruct familiar patterns well and unfamiliar patterns poorly. A reconstruction score can then flag unusual windows. This is a heuristic, not a law: a high-capacity model may reconstruct anomalies too, and harmless distribution shift may raise error.</p><div className="not-prose rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="font-mono text-base font-bold text-amber-950">score(x) = (1/d) Σ(x<sub>j</sub> − x̂<sub>j</sub>)²</p><p className="mt-2 font-mono text-sm text-amber-900">flag anomaly if score(x) &gt; τ</p><p className="mt-3 text-sm leading-relaxed text-amber-900">τ is an operational threshold chosen on held-out normal and, when available, representative anomaly examples.</p></div><AnomalyFigure /><p className="text-lg leading-relaxed">Evaluate precision–recall and alert burden across thresholds. Split time-series data chronologically or by equipment unit to avoid near-duplicate windows crossing train and test sets.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Autoencoder Variants Solve Different Constraints</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[980px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Variant</th><th className="p-3 text-left">Main constraint/change</th><th className="p-3 text-left">Useful starting scenario</th><th className="p-3 text-left">Important limitation</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{variants.map(([name,change,use,limit])=><tr key={name} className="align-top"><td className="p-3 font-bold text-indigo-800">{name}</td><td className="p-3">{change}</td><td className="p-3 text-emerald-800">{use}</td><td className="p-3 text-rose-800">{limit}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Variational Autoencoder Learns a Distribution</h2><p className="text-lg leading-relaxed">An ordinary autoencoder maps each input to one code. Empty regions between training codes may decode unpredictably, so arbitrary sampling is not guaranteed to produce plausible data. A Variational Autoencoder (VAE) asks the encoder for parameters of a distribution—commonly mean μ and diagonal variance σ²—then samples a latent z for the decoder.</p><VAEFigure /><div className="not-prose rounded-2xl bg-slate-950 p-5 text-white md:p-6"><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-fuchsia-300">VAE objective for one example</p><p className="mt-2 overflow-x-auto whitespace-nowrap font-mono text-lg font-bold">L = L<sub>reconstruction</sub> + β D<sub>KL</sub>(q<sub>φ</sub>(z|x) ‖ p(z))</p><p className="mt-3 text-sm leading-relaxed text-slate-200">The reconstruction term rewards explaining x from z. The KL term measures how far the encoder&apos;s distribution q<sub>φ</sub> is from a chosen prior p(z), often N(0,I); adding it discourages isolated, irregular latent regions. β is a developer-chosen hyperparameter that multiplies this regularization before addition. β=1 gives the usual VAE objective; larger or smaller values change the reconstruction–regularity trade-off.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Sampling and KL Divergence With Numbers</h2><div className="not-prose rounded-2xl border border-fuchsia-200 bg-fuchsia-50 p-5 md:p-6"><h3 className="text-xl font-bold text-fuchsia-950">One latent dimension</h3><p className="mt-2 text-slate-700">For a visible calculation, assume the encoder produced μ=0.5 and σ=0.8, then use one illustrative random draw ε=0.25 from N(0,1). In real training μ and σ are network outputs for each input, while ε is freshly sampled by the framework.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-lg bg-white p-4"><p className="font-bold text-fuchsia-900">Reparameterized sample</p><p className="mt-2 font-mono text-sm leading-7">z=μ+σε<br />=0.5+(0.8×0.25)<br />=<strong>0.70</strong></p><p className="mt-2 text-xs leading-relaxed text-slate-600">Multiply to scale unit noise, then add μ to shift its centre.</p></div><div className="rounded-lg bg-white p-4"><p className="font-bold text-fuchsia-900">KL to N(0,1)</p><p className="mt-2 font-mono text-sm leading-7">KL=½(μ²+σ²−1−ln σ²)<br />=½(0.25+0.64−1−ln 0.64)<br />≈½(0.336)=<strong>0.168</strong></p><p className="mt-2 text-xs leading-relaxed text-slate-600">This closed form compares the shifted, scaled encoder distribution with the unit-normal prior.</p></div></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> z remains random, but gradients can flow through μ and σ because ε contains the sampling randomness. The positive KL cost reflects that N(0.5,0.8²) differs from the unit-normal prior.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Small Denoising Autoencoder in PyTorch</h2><p className="text-lg leading-relaxed">This example assumes 28×28 grayscale inputs scaled to [0,1]. Gaussian noise creates x̃; the clean batch x is the target. The final sigmoid matches the chosen [0,1] output range, while MSE measures pixel reconstruction.</p><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">denoising_autoencoder.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`import torch
from torch import nn

class DenoisingAutoencoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 128), nn.ReLU(),
            nn.Linear(128, 32),
        )
        self.decoder = nn.Sequential(
            nn.Linear(32, 128), nn.ReLU(),
            nn.Linear(128, 28 * 28), nn.Sigmoid(),
        )

    def forward(self, x):
        z = self.encoder(x)
        return self.decoder(z).view(-1, 1, 28, 28)

model = DenoisingAutoencoder()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = nn.MSELoss()

for clean_images, _ in train_loader:
    noisy_images = (clean_images + 0.25 * torch.randn_like(clean_images)).clamp(0, 1)
    reconstructed = model(noisy_images)
    loss = loss_fn(reconstructed, clean_images)  # clean target

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()`}</pre></div><div className="not-prose mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold text-blue-950">Where the numbers come from</p><p className="mt-2 text-sm leading-relaxed text-blue-900">28×28 and one channel come from the image data, so flattening calculates 784 input values. The 128 hidden units, 32-value code, noise scale 0.25 and learning rate 0.001 are developer-selected hyperparameters to validate—not universal defaults.</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold text-emerald-950">What the operations do</p><p className="mt-2 text-sm leading-relaxed text-emerald-900"><code>randn_like</code> samples Gaussian noise with the image shape; multiplying controls its strength, adding corrupts the input, and <code>clamp</code> restores the valid [0,1] range. The model receives noisy pixels but MSE compares its reconstruction with clean pixels, so training rewards noise removal.</p></div></div><p className="mt-4 text-sm leading-relaxed text-slate-600">For images, a convolutional encoder/decoder usually preserves spatial structure better than flattening; this dense network keeps the first implementation easy to trace.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Diagnose the Representation, Not Just the Loss</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[980px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Symptom</th><th className="p-3 text-left">Likely cause</th><th className="p-3 text-left">What to try</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Near-perfect reconstructions but useless codes","Identity-like copying through excessive capacity","Narrow/regularize the code, add denoising, evaluate downstream utility"],["Everything reconstructs as an average","Underfitting, wrong output/loss, or optimization problem","Inspect scale and activations; overfit a tiny clean set; increase capacity carefully"],["Anomaly detector flags a new machine type","Normal validation data misses deployment diversity","Retrain/condition by domain and set thresholds per justified group"],["Anomalies reconstruct too well","Decoder generalizes or copies too broadly","Reduce capacity, use robust representation objectives, compare one-class alternatives"],["VAE ignores z","Posterior collapse; decoder too powerful or KL pressure too strong","Monitor per-dimension KL, anneal β, weaken decoder or use free-bits-style methods"],["Generated samples are poor despite low reconstruction loss","Deterministic latent gaps or VAE trade-off imbalance","Use a generative objective and evaluate sample quality separately"]].map(([symptom,cause,fix])=><tr key={symptom} className="align-top"><td className="p-3 font-bold text-slate-900">{symptom}</td><td className="p-3 text-rose-800">{cause}</td><td className="p-3 text-indigo-800">{fix}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What an Autoencoder Can—and Cannot—Promise</h2><p className="text-lg leading-relaxed">Reconstruction preserves what the chosen loss rewards. Pixel MSE may prioritize average colour over perceptual sharpness; feature MSE may preserve different properties. A low-dimensional code is not automatically interpretable, independent or useful for a downstream task. Neural compression also includes model storage and inference cost, not just code width.</p><p className="text-lg leading-relaxed">Treat denoising, anomaly scoring, dimensionality reduction and generation as separate objectives with separate validation. An architecture called “autoencoder” does not make one model good at all four.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Complete Autoencoder Picture</h2><div className="not-prose rounded-2xl border border-violet-200 bg-violet-50 p-6"><ul className="m-0 space-y-2 pl-5 text-violet-950"><li>The encoder creates z; the decoder reconstructs x̂; both learn from reconstruction error.</li><li>A bottleneck, sparsity penalty or denoising task is needed to discourage unhelpful copying.</li><li>Reconstruction loss, data scale and output activation must describe the data appropriately.</li><li>Anomaly detection requires held-out threshold selection and must account for distribution shift.</li><li>A VAE encodes μ and σ, samples with z=μ+σε, and balances reconstruction with KL regularization.</li><li>Judge representations by the real downstream goal, not training loss alone.</li></ul></div></section>

    <section><h2 className="mb-4 border-b pb-2 text-2xl font-bold text-indigo-800">Continue Learning</h2><div className="not-prose mb-10 grid gap-4 md:grid-cols-2"><a href="/learn/transformers-deep-learning" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Previous concept</p><p className="m-0 font-bold text-slate-900">Transformers for Deep Learning</p></a><a href="/learn/transfer-learning" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Next concept</p><p className="m-0 font-bold text-slate-900">Transfer Learning and Fine-Tuning</p></a></div></section>
  </div>;
}
