import React from "react";

function arrowHead(x: number, y: number, color: string, reverse = false) {
  return reverse
    ? <polygon points={`${x + 10},${y - 6} ${x},${y} ${x + 10},${y + 6}`} fill={color} />
    : <polygon points={`${x - 10},${y - 6} ${x},${y} ${x - 10},${y + 6}`} fill={color} />;
}

function NetworkPassDiagram({ backward = false }: { backward?: boolean }) {
  const color = backward ? "#e11d48" : "#4f46e5";
  const input = [[95, 75], [95, 155], [95, 235]];
  const hidden = [[330, 80], [330, 155], [330, 230]];
  const output = [560, 155];
  return (
    <figure className="not-prose m-0">
      <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <svg viewBox="0 0 690 315" className="w-full min-w-[600px]" role="img" aria-label={backward ? "Backward pass through a neural network" : "Forward pass through a neural network"}>
          <rect x="2" y="2" width="686" height="311" rx="18" fill={backward ? "#fff1f2" : "#eef2ff"} />
          <text x="345" y="31" textAnchor="middle" fontSize="19" fontWeight="800" fill={backward ? "#9f1239" : "#3730a3"}>{backward ? "BACKWARD PASS: error responsibility moves left" : "FORWARD PASS: values move right"}</text>
          {input.flatMap(([x1, y1], i) => hidden.map(([x2, y2], j) => <g key={`ih-${i}-${j}`}><line x1={backward ? x2 - 31 : x1 + 31} y1={backward ? y2 : y1} x2={backward ? x1 + 37 : x2 - 37} y2={backward ? y1 : y2} stroke={color} strokeWidth="2" opacity="0.7" />{arrowHead(backward ? x1 + 34 : x2 - 34, backward ? y1 : y2, color, backward)}</g>))}
          {hidden.map(([x1, y1], i) => <g key={`ho-${i}`}><line x1={backward ? output[0] - 36 : x1 + 31} y1={backward ? output[1] : y1} x2={backward ? x1 + 37 : output[0] - 42} y2={backward ? y1 : output[1]} stroke={color} strokeWidth="2.5" />{arrowHead(backward ? x1 + 34 : output[0] - 39, backward ? y1 : output[1], color, backward)}</g>)}
          {input.map(([x, y], i) => <g key={`i-${i}`}><circle cx={x} cy={y} r="31" fill="#fef3c7" stroke="#d97706" strokeWidth="2" /><text x={x} y={y + 5} textAnchor="middle" fontSize="15" fontWeight="800" fill="#92400e">x{i + 1}</text></g>)}
          {hidden.map(([x, y], i) => <g key={`h-${i}`}><circle cx={x} cy={y} r="31" fill="#dcfce7" stroke="#059669" strokeWidth="2" /><text x={x} y={y + 5} textAnchor="middle" fontSize="15" fontWeight="800" fill="#065f46">h{i + 1}</text></g>)}
          <circle cx={output[0]} cy={output[1]} r="37" fill="#dbeafe" stroke="#2563eb" strokeWidth="2" /><text x={output[0]} y={output[1] + 5} textAnchor="middle" fontSize="15" fontWeight="800" fill="#1e40af">ŷ</text>
          <rect x="615" y="117" width="58" height="76" rx="14" fill="white" stroke="#e11d48" strokeWidth="2" /><text x="644" y="149" textAnchor="middle" fontSize="13" fontWeight="800" fill="#9f1239">LOSS</text><text x="644" y="170" textAnchor="middle" fontSize="12" fill="#9f1239">L</text>
          <line x1={backward ? 615 : 597} y1="155" x2={backward ? 603 : 609} y2="155" stroke={color} strokeWidth="3" />{arrowHead(backward ? 603 : 609, 155, color, backward)}
          <text x="95" y="286" textAnchor="middle" fontSize="13" fontWeight="800" fill="#475569">Input values</text>
          <text x="330" y="286" textAnchor="middle" fontSize="13" fontWeight="800" fill="#475569">Hidden calculations</text>
          <text x="580" y="286" textAnchor="middle" fontSize="13" fontWeight="800" fill="#475569">Prediction → Loss</text>
        </svg>
      </div>
      <figcaption className="mt-3 text-center text-sm text-slate-600">{backward ? "Figure 2: Starting from the loss, the chain rule calculates how much each earlier weight affected the mistake." : "Figure 1: Input values travel through weighted calculations to create a prediction and a loss."}</figcaption>
    </figure>
  );
}

function ComputationGraph() {
  const nodes = [[50, 120, "x = 2", "known input", "#f59e0b"], [50, 205, "w = 0.5", "trainable", "#7c3aed"], [50, 290, "b = 1", "trainable", "#7c3aed"], [250, 160, "w × x", "0.5 × 2 = 1", "#2563eb"], [410, 205, "+ b", "1 + 1 = 2", "#059669"], [560, 205, "ŷ = 2", "prediction", "#059669"], [690, 120, "y = 4", "target", "#f59e0b"], [690, 260, "L = 2", "½(ŷ−y)²", "#e11d48"]] as const;
  return <figure className="not-prose my-7"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><svg viewBox="0 0 800 360" className="w-full min-w-[720px]" role="img" aria-label="Computation graph for a one-weight model"><rect x="2" y="2" width="796" height="356" rx="18" fill="#f8fafc" />
    <defs><marker id="cg-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#64748b" /></marker></defs>
    {[[115,120,195,160],[115,205,195,174],[305,160,345,195],[115,290,345,220],[475,205,500,205],[610,205,650,245],[690,157,690,215]].map((line,i)=><line key={i} x1={line[0]} y1={line[1]} x2={line[2]} y2={line[3]} stroke="#64748b" strokeWidth="2.5" markerEnd="url(#cg-arrow)" />)}
    {nodes.map(([x,y,label,detail,color])=><g key={label}><rect x={x-60} y={y-32} width="120" height="64" rx="14" fill="white" stroke={color} strokeWidth="2.5" /><text x={x} y={y-3} textAnchor="middle" fontSize="15" fontWeight="800" fill="#0f172a">{label}</text><text x={x} y={y+18} textAnchor="middle" fontSize="10" fill="#64748b">{detail}</text></g>)}
    <path d="M675 302 C560 342 178 342 91 310" fill="none" stroke="#e11d48" strokeWidth="3" strokeDasharray="8 5" markerEnd="url(#cg-arrow)" /><text x="400" y="333" textAnchor="middle" fontSize="12" fontWeight="800" fill="#be123c">backward calculation follows these dependencies in reverse</text>
  </svg></div><figcaption className="mt-3 text-center text-sm text-slate-600">Figure 3: A computation graph stores small operations and their dependencies; automatic differentiation applies derivative rules to this graph.</figcaption></figure>;
}

function ScalarGradientFlowFigure() {
  return (
    <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">The same graph is read in two directions</p></div>
      <div className="overflow-x-auto p-5 md:p-6"><div className="min-w-[820px] space-y-5"><div className="grid grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] items-center gap-3 text-center"><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-bold uppercase text-amber-700">known values</p><p className="mt-2 font-mono font-black">x=2, w=0.5, b=1</p></div><span className="text-2xl text-indigo-500">→</span><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-700">multiply + add</p><p className="mt-2 font-mono font-black">ŷ=0.5×2+1=2</p></div><span className="text-2xl text-indigo-500">→</span><div className="rounded-xl border border-violet-200 bg-violet-50 p-4"><p className="text-xs font-bold uppercase text-violet-700">compare with y=4</p><p className="mt-2 font-mono font-black">ŷ−y=−2</p></div><span className="text-2xl text-indigo-500">→</span><div className="rounded-xl border border-rose-200 bg-rose-50 p-4"><p className="text-xs font-bold uppercase text-rose-700">loss</p><p className="mt-2 font-mono font-black">½(−2)²=2</p></div></div><div className="flex items-center justify-center rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">Backward pass starts here and moves right to left ↓</div><div className="grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-3 text-center"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-bold uppercase text-emerald-700">weight gradient</p><p className="mt-2 font-mono font-black">∂L/∂w=−2×2=−4</p></div><span className="text-2xl text-rose-500">←</span><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-bold uppercase text-amber-700">local effect of w</p><p className="mt-2 font-mono font-black">∂ŷ/∂w=x=2</p></div><span className="text-2xl text-rose-500">←</span><div className="rounded-xl border border-rose-200 bg-rose-50 p-4"><p className="text-xs font-bold uppercase text-rose-700">local loss effect</p><p className="mt-2 font-mono font-black">∂L/∂ŷ=−2</p></div></div></div></div>
      <figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">Forward values answer “what did the model predict?” Backward derivatives answer “how strongly did each earlier value influence the loss?” The data itself does not travel backward.</figcaption>
    </figure>
  );
}

function Step({ number, title, children, result }: { number: string; title: string; children: React.ReactNode; result: string }) {
  return <div className="not-prose grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-[48px_1fr]"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-600 text-lg font-extrabold text-white">{number}</span><div><h3 className="mb-2 text-lg font-extrabold text-slate-900">{title}</h3><div className="text-sm leading-relaxed text-slate-700">{children}</div><p className="mt-3 mb-0 overflow-x-auto rounded-lg bg-slate-900 px-4 py-3 font-mono text-sm font-bold text-white">{result}</p></div></div>;
}

export function BackpropagationContent() {
  return <div className="space-y-10">
    <header className="mb-8"><p className="mb-2 text-sm font-bold uppercase tracking-widest text-indigo-600">Deep Learning · Beginner Lesson</p><h2 className="mb-3 text-4xl font-extrabold text-slate-900">Backpropagation: How a Neural Network Learns From One Mistake</h2><p className="mb-0 text-lg leading-relaxed text-slate-600">A neural network may contain millions of adjustable weights. After it makes a wrong prediction, backpropagation calculates how much each weight contributed to that mistake. An optimizer then uses those calculations to make a small correction. This lesson follows both journeys—forward to the prediction and backward to the weights—using one complete numerical example.</p></header>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Learning Problem</h2><p className="text-lg leading-relaxed">Suppose a network predicts 2, but the correct answer is 4. Knowing the final error is not enough. The network must answer three more questions:</p><div className="not-prose my-5 grid gap-4 md:grid-cols-3">{[["Which weights?", "Which connections helped produce the wrong answer?"], ["Which direction?", "Should each weight become larger or smaller?"], ["How sensitive?", "Would a tiny change have a large or small effect on the loss?"]].map(([title,text],i)=><div key={title} className="rounded-xl border border-slate-200 bg-white p-5"><span className="mb-3 flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-100 font-extrabold text-indigo-800">{i+1}</span><p className="mb-1 font-extrabold text-slate-900">{title}</p><p className="m-0 text-sm leading-relaxed text-slate-600">{text}</p></div>)}</div><p className="text-lg leading-relaxed"><strong>Backpropagation</strong> answers those questions efficiently. It starts at the final loss and works backward through the calculations. At every step it uses a derivative—a number that describes how sensitive one value is to a small change in another.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">First Journey: The Forward Pass</h2><p className="text-lg leading-relaxed">The <strong>forward pass</strong> is simply the calculation that makes a prediction. Input values enter the network, each layer performs its weighted calculations and activations, and the output layer produces the final answer. The loss function then compares that answer with the target.</p><NetworkPassDiagram /><div className="not-prose rounded-xl border border-indigo-200 bg-indigo-50 p-5"><p className="m-0 text-center font-mono text-sm font-bold text-indigo-950 md:text-lg">input → weighted sums → activations → prediction → loss</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Second Journey: The Backward Pass</h2><p className="text-lg leading-relaxed">The <strong>backward pass</strong> begins only after the loss is known. It asks how the loss would change if each earlier value changed slightly. This sensitivity is called a <strong>gradient</strong>. The information moves from the loss toward the output layer, hidden layers and earlier weights.</p><NetworkPassDiagram backward /><div className="not-prose rounded-xl border border-rose-200 bg-rose-50 p-5"><p className="m-0 text-center font-mono text-sm font-bold text-rose-950 md:text-lg">loss → output gradients → hidden gradients → weight gradients</p></div><p className="mt-5 text-lg leading-relaxed">The arrows do not mean that the training examples themselves run backward. Only derivative information moves backward. The actual weight change happens later, when the optimizer applies the learning rate.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Important Terms Before the Calculation</h2><div className="not-prose grid gap-4 sm:grid-cols-2">{[["Weight (w)", "An adjustable number that controls how strongly an input affects the next calculation."], ["Bias (b)", "An adjustable offset added after the weighted input."], ["Loss (L)", "The numerical penalty for the current prediction."], ["Derivative", "The sensitivity of one value to a tiny change in another value."], ["Gradient", "The set of derivatives for all trainable weights and biases."], ["Learning rate (η)", "A small multiplier that controls the size of an optimizer update."]].map(([term,text])=><div key={term} className="rounded-xl border border-slate-200 bg-white p-4"><p className="mb-1 font-mono font-bold text-indigo-800">{term}</p><p className="m-0 text-sm leading-relaxed text-slate-600">{text}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">One Complete Numerical Example</h2><p className="text-lg leading-relaxed">We will train the smallest useful model: one input, one weight and one bias. It predicts with <strong>ŷ = wx + b</strong>. To make differentiation simple, we use the squared loss <strong>L = ½(ŷ − y)²</strong>. The ½ is a teaching convenience: differentiating the square introduces a factor of 2, and ½×2 becomes 1.</p><div className="not-prose my-5 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Symbol</th><th className="p-3 text-left">Value</th><th className="p-3 text-left">Where it comes from</th><th className="p-3 text-left">Can training change it?</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Input x","2","A manually chosen training-example input","No"],["Target y","4","The known answer paired with this example","No"],["Weight w","0.5","A manually chosen starting parameter for the demonstration","Yes"],["Bias b","1","A manually chosen starting parameter for the demonstration","Yes"],["Learning rate η","0.1","A developer-chosen update-size hyperparameter","No; the optimizer uses it"]].map(([symbol,value,origin,learned])=><tr key={symbol}><td className="p-3 font-bold text-indigo-800">{symbol}</td><td className="p-3 font-mono">{value}</td><td className="p-3 text-slate-700">{origin}</td><td className="p-3 text-emerald-800">{learned}</td></tr>)}</tbody></table></div><ComputationGraph /><ScalarGradientFlowFigure />
      <div className="space-y-4">
        <Step number="1" title="Calculate the prediction" result="ŷ = wx + b = (0.5 × 2) + 1 = 2"><p className="m-0">Multiply the input by the current weight, then add the bias. The model predicts 2.</p></Step>
        <Step number="2" title="Calculate the loss" result="L = ½(ŷ − y)² = ½(2 − 4)² = ½ × 4 = 2"><p className="m-0">The target is 4, so the prediction is too small. The current loss is 2.</p></Step>
        <Step number="3" title="Find how loss changes with the prediction" result="∂L/∂ŷ = ŷ − y = 2 − 4 = −2"><p className="m-0">The symbol ∂ means “change in.” This derivative is negative, telling us that increasing the prediction would reduce the loss.</p></Step>
        <Step number="4" title="Follow the chain back to the weight" result="∂L/∂w = (∂L/∂ŷ)(∂ŷ/∂w) = (−2)(x) = (−2)(2) = −4"><p className="m-0">Because ŷ = wx + b, the prediction changes by x when w changes, so ∂ŷ/∂w = x = 2. Multiplying the connected derivatives is the <strong>chain rule</strong>.</p></Step>
        <Step number="5" title="Find the bias gradient" result="∂L/∂b = (∂L/∂ŷ)(∂ŷ/∂b) = (−2)(1) = −2"><p className="m-0">Adding one unit to the bias adds one unit to the prediction, so ∂ŷ/∂b = 1.</p></Step>
        <Step number="6" title="Let the optimizer update the parameters" result="w_new = 0.5 − 0.1(−4) = 0.9     b_new = 1 − 0.1(−2) = 1.2"><p className="m-0">Gradient descent subtracts the learning rate multiplied by each gradient. Subtracting a negative number makes both parameters larger.</p></Step>
        <Step number="7" title="Check the next prediction" result="ŷ_new = (0.9 × 2) + 1.2 = 3     L_new = ½(3 − 4)² = 0.5"><p className="m-0">The loss fell from <strong>2 to 0.5</strong>. One update did not finish training, but it moved the model in the correct direction.</p></Step>
      </div>
    </section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">How the Chain Rule Connects the Steps</h2><p className="text-lg leading-relaxed">The loss does not use w directly. It depends on the prediction ŷ, and ŷ depends on w. The chain rule connects those dependencies:</p><div className="not-prose my-5 rounded-2xl bg-indigo-950 p-6 text-white"><p className="mb-3 overflow-x-auto text-center font-mono text-xl font-extrabold">∂L/∂w = ∂L/∂ŷ × ∂ŷ/∂w</p><div className="grid gap-3 text-sm md:grid-cols-3"><div className="rounded-lg bg-white/10 p-3 text-center">How loss reacts to prediction</div><div className="rounded-lg bg-white/10 p-3 text-center">× How prediction reacts to weight</div><div className="rounded-lg bg-emerald-400/20 p-3 text-center">= How loss reacts to weight</div></div></div><p className="text-lg leading-relaxed">Why multiply? Imagine a tiny increase of 0.01 in w. Because ∂ŷ/∂w=2, the prediction changes by approximately 2×0.01=0.02. Because ∂L/∂ŷ=−2, that prediction change alters loss by approximately −2×0.02=−0.04. Combining the two effects gives −2×2×0.01=−0.04, so the sensitivity per one unit of w is −4.</p><p className="text-lg leading-relaxed">A real network repeats this idea through many connected operations. Backpropagation reuses intermediate results, making it far more efficient than perturbing and recalculating every parameter separately.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Do Not Confuse Backpropagation, Autodiff, Gradient Descent and the Optimizer</h2><p className="text-lg leading-relaxed">These ideas cooperate, but each has a different responsibility.</p><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Term</th><th className="p-3 text-left">What it means</th><th className="p-3 text-left">Its job during training</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Computation graph", "A record of operations and dependencies", "Remembers how the loss was produced"], ["Automatic differentiation", "A framework mechanism that applies derivative rules to recorded operations", "Evaluates derivatives without hand-coding each one"], ["Backpropagation", "An efficient reverse pass that sends sensitivity through the network", "Computes a gradient for each trainable parameter"], ["Gradient descent", "The basic principle of moving parameters opposite the gradient", "Explains the direction used to reduce a local objective"], ["Optimizer", "The actual update algorithm, such as SGD or Adam", "Combines gradients, learning rates and possible state to change parameters"]].map(([term,meaning,job])=><tr key={term}><td className="p-3 font-extrabold text-indigo-800">{term}</td><td className="p-3 text-slate-700">{meaning}</td><td className="p-3 text-slate-700">{job}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What the Framework Does for You</h2><p className="text-lg leading-relaxed">PyTorch and TensorFlow record the forward operations and compute the gradients automatically. The mathematics is still the same as the hand calculation.</p><div className="not-prose overflow-hidden rounded-xl bg-[#172033] shadow-lg"><div className="flex items-center gap-2 bg-slate-800 px-4 py-2 text-xs font-mono text-slate-300"><span className="h-3 w-3 rounded-full bg-red-400" /><span className="h-3 w-3 rounded-full bg-amber-400" /><span className="h-3 w-3 rounded-full bg-emerald-400" /><span className="ml-2">one_step.py</span></div><pre className="overflow-x-auto p-5 text-sm leading-relaxed text-slate-100"><code>{`import torch

x = torch.tensor(2.0)
y = torch.tensor(4.0)
w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

y_hat = w * x + b          # forward pass
loss = 0.5 * (y_hat - y)**2
loss.backward()             # backward pass

print(w.grad.item())        # -4.0
print(b.grad.item())        # -2.0

with torch.no_grad():
    w -= 0.1 * w.grad
    b -= 0.1 * b.grad

new_y_hat = w * x + b
new_loss = 0.5 * (new_y_hat - y)**2
print(w.item(), b.item())   # about 0.9, 1.2
print(new_y_hat.item())     # about 3.0
print(new_loss.item())      # about 0.5

# PyTorch adds future backward results to .grad, so clear them before
# another independent training step.
w.grad.zero_()
b.grad.zero_()`}</code></pre></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Read the PyTorch Example Line by Line</h2><div className="not-prose grid gap-4 md:grid-cols-2">{[["requires_grad=True","Marks w and b as trainable values whose gradients should be stored."],["y_hat = w * x + b","Runs the same forward prediction calculated by hand."],["loss = 0.5 * ...","Creates one scalar objective from prediction and target."],["loss.backward()","Traverses the recorded operations backward and accumulates gradients in w.grad and b.grad."],["with torch.no_grad()","Changes parameters without recording the update itself as part of the next gradient graph."],["w -= 0.1 * w.grad","Performs the explicit gradient-descent update using the chosen learning rate 0.1."],["new_loss","Runs a second forward calculation and verifies that loss fell from 2 to about 0.5."],["grad.zero_()","Clears accumulated gradients before another independent step; optimizers commonly provide zero_grad() for all parameters."]].map(([code,meaning])=><div key={code} className="rounded-xl border border-slate-200 bg-white p-4"><p className="font-mono font-bold text-indigo-800">{code}</p><p className="mt-2 text-sm leading-relaxed text-slate-600">{meaning}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Common Mistakes and How to Diagnose Them</h2><div className="not-prose grid gap-4 md:grid-cols-2">{[["Forgetting to clear gradients", "Many frameworks accumulate gradients. Clear them before the next backward pass unless accumulation is intentional."], ["Updating during validation", "Validation measures the model; it must not call backward or change parameters."], ["Detached computation", "Converting a needed tensor to a plain number or detaching it can break the path from loss to weight."], ["Exploding or vanishing gradients", "Repeated large derivatives can explode; repeated small derivatives can vanish. Inspect gradient norms."], ["Wrong loss-output pairing", "A mathematically valid gradient can still train the wrong objective. Verify targets, logits and activation expectations."], ["Confusing backprop with the update", "Backprop calculates gradients. SGD, Adam or another optimizer performs the update."]].map(([title,text])=><div key={title} className="rounded-xl border border-slate-200 bg-white p-5"><p className="mb-2 font-extrabold text-slate-900">{title}</p><p className="m-0 text-sm leading-relaxed text-slate-600">{text}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">When Backpropagation Is—and Is Not—the Right Tool</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Situation</th><th className="p-3 text-left">Guidance</th><th className="p-3 text-left">Why</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Differentiable neural network", "Use backpropagation", "It efficiently supplies gradients for millions of parameters"], ["Sequence model", "Use backpropagation through time or an equivalent graph", "The repeated operations are unrolled through sequence positions"], ["Non-differentiable decision or simulator", "Consider a smooth surrogate, policy gradient, search or gradient-free optimization", "Ordinary derivatives may not exist or may not reach the parameters"], ["Need only inference", "Do not run backward", "Prediction needs the forward pass only, saving memory and time"]].map(([situation,guidance,why])=><tr key={situation}><td className="p-3 font-bold text-indigo-800">{situation}</td><td className="p-3 font-semibold text-emerald-800">{guidance}</td><td className="p-3 text-slate-700">{why}</td></tr>)}</tbody></table></div></section>

    <section className="not-prose rounded-2xl bg-gradient-to-br from-indigo-950 to-slate-900 p-6 text-white md:p-8"><h2 className="mb-4 text-2xl font-extrabold">The complete idea in five lines</h2><ol className="m-0 space-y-3 pl-5 text-sm leading-relaxed text-slate-200"><li>A forward pass creates a prediction and a loss.</li><li>The computation graph records which operations produced that loss.</li><li>Backpropagation follows the graph backward and applies the chain rule.</li><li>The result is one gradient for every trainable parameter.</li><li>An optimizer uses those gradients and a learning rate to update the parameters.</li></ol></section>
  </div>;
}
