import React from "react";

function NLPPipelineFigure() {
  const stages = [
    ["Raw language", '“Pump A is not safe.”', "#fef3c7", "#d97706"],
    ["Tokenizer", "[Pump] [A] [is] [not] [safe] [.]", "#dbeafe", "#2563eb"],
    ["Token IDs", "[731, 42, 19, 87, 905, 7]", "#e0e7ff", "#4f46e5"],
    ["Embeddings + model", "contextual vectors", "#ede9fe", "#7c3aed"],
    ["Task head", "unsafe: 0.94", "#dcfce7", "#16a34a"],
  ];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">A deep NLP system turns language into task-specific predictions</p><p className="mt-1 text-sm text-slate-600">Every arrow is a testable part of the data path.</p></div><div className="overflow-x-auto p-5 md:p-6"><div className="flex min-w-[980px] items-stretch gap-3">{stages.map(([title,detail,bg,border],i)=><React.Fragment key={title}><div className="flex-1 rounded-xl border p-4 text-center" style={{backgroundColor:bg,borderColor:border}}><p className="text-sm font-extrabold text-slate-900">{title}</p><p className="mt-3 font-mono text-xs leading-relaxed text-slate-700">{detail}</p></div>{i<stages.length-1&&<div className="flex items-center text-2xl font-black text-slate-400">→</div>}</React.Fragment>)}</div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">The tokenizer does not understand the sentence by itself; it converts text to IDs. The neural model turns those IDs into context-dependent representations, and a task head converts a chosen representation into labels, spans or new tokens.</figcaption></figure>;
}

function TokenizationFigure() {
  const variants = [
    ["Word tokens", "retraining", "one known word—or unknown", "bg-amber-50 border-amber-200 text-amber-900"],
    ["Subword tokens", "re · train · ing", "reuse learned pieces", "bg-blue-50 border-blue-200 text-blue-900"],
    ["Character tokens", "r · e · t · r · a · i · n · i · n · g", "small vocabulary, long sequence", "bg-violet-50 border-violet-200 text-violet-900"],
  ];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">One string can be divided at different levels</p><p className="mt-1 text-sm text-slate-600">The pieces below are illustrative; a real pretrained tokenizer has its own learned vocabulary and boundary markers.</p><div className="mt-5 grid gap-4 md:grid-cols-3">{variants.map(([title,tokens,note,style])=><div key={title} className={`rounded-xl border p-4 ${style}`}><p className="text-xs font-extrabold uppercase tracking-wide">{title}</p><p className="mt-3 min-h-12 font-mono text-sm font-bold">{tokens}</p><p className="mt-3 text-xs leading-relaxed opacity-80">{note}</p></div>)}</div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">Subwords balance vocabulary size and sequence length. They also help represent uncommon names and word forms from familiar pieces, though domain-specific strings can still fragment badly.</figcaption></figure>;
}

function ContextEmbeddingFigure() {
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">The same spelling can need different contextual representations</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50 p-5"><p className="font-mono text-sm text-slate-800">“Deposit cash at the <strong className="text-blue-800">bank</strong>.”</p><div className="mt-4 flex items-center gap-3"><span className="rounded-lg bg-blue-700 p-3 font-mono text-xs font-bold text-white">bank vector A</span><span className="text-sm text-blue-900">financial context</span></div></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-mono text-sm text-slate-800">“Sit on the river <strong className="text-emerald-800">bank</strong>.”</p><div className="mt-4 flex items-center gap-3"><span className="rounded-lg bg-emerald-700 p-3 font-mono text-xs font-bold text-white">bank vector B</span><span className="text-sm text-emerald-900">land/water context</span></div></div></div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">A static word embedding assigns one learned vector to “bank.” A contextual encoder starts from a token embedding, then uses surrounding tokens to produce a different final representation for each occurrence.</figcaption></figure>;
}

function TaskShapesFigure() {
  const tasks = [
    ["Text classification", "whole document", "one or more labels", "complaint → billing"],
    ["Token classification", "each token", "tag per token", "Priya → PERSON"],
    ["Extractive QA", "question + passage", "start/end span", "answer words in passage"],
    ["Semantic similarity", "text pair", "score or class", "duplicate ticket: 0.91"],
    ["Generation", "prompt/source", "new token sequence", "report → summary"],
  ];
  return <figure className="not-prose my-7 overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Task</th><th className="p-3 text-left">Prediction unit</th><th className="p-3 text-left">Model output</th><th className="p-3 text-left">Example</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{tasks.map(([task,unit,output,example])=><tr key={task}><td className="p-3 font-bold text-indigo-800">{task}</td><td className="p-3">{unit}</td><td className="p-3">{output}</td><td className="p-3 text-emerald-800">{example}</td></tr>)}</tbody></table><figcaption className="bg-slate-50 px-5 py-3 text-sm leading-relaxed text-slate-600">The task determines labels, loss, metrics and model head. “Use BERT” is not a complete problem definition.</figcaption></figure>;
}

function SplitLeakageFigure() {
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">Split by the unit that can repeat—not just by rows</p><div className="mt-5 grid gap-3 md:grid-cols-[1fr_auto_1fr]"><div className="rounded-xl border border-rose-200 bg-rose-50 p-4"><p className="text-xs font-bold uppercase text-rose-700">Leaky row split</p><p className="mt-2 text-sm text-rose-950">Ticket 104 sentence A → train<br />Ticket 104 sentence B → test</p><p className="mt-3 text-xs">Near-duplicate context crosses the boundary.</p></div><div className="flex items-center justify-center text-3xl font-black text-slate-400">→</div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-bold uppercase text-emerald-700">Grouped split</p><p className="mt-2 text-sm text-emerald-950">All of Ticket 104 → one split<br />New tickets → held out</p><p className="mt-3 text-xs">Evaluation better matches deployment.</p></div></div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">Users, documents, conversations, time windows and templates can all create leakage. Define the deployment boundary before building the split.</figcaption></figure>;
}

export function DeepLearningNLPContent() {
  return <div className="prose prose-lg max-w-none text-slate-700">
    <section className="not-prose mb-10 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-blue-950 to-indigo-800 px-6 py-10 text-white shadow-xl md:px-10 md:py-12"><p className="mb-3 text-sm font-extrabold uppercase tracking-[0.18em] text-blue-200">Bridge to LLMs</p><h2 className="max-w-4xl text-3xl font-black leading-tight md:text-5xl">Deep Learning for Natural Language Processing</h2><p className="mt-5 max-w-4xl text-lg leading-relaxed text-blue-50 md:text-xl">Natural Language Processing (NLP) turns text or speech into useful predictions and generated language. This lesson follows a message from raw characters to tokens, IDs, embeddings and contextual representations; shows how output design changes across NLP tasks; calculates embedding similarity and classification loss; and explains how to fine-tune and evaluate pretrained models without silently leaking text or changing their expected preprocessing.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why Language Is Difficult for a Neural Network</h2><p className="text-lg leading-relaxed">A photograph arrives as numbers arranged in a grid. A sentence arrives as symbols whose meaning depends on order, surrounding words, speaker, domain and sometimes information outside the sentence. “The service is sick” may be praise in slang or a fault report in engineering. “That was not bad” cannot be classified by counting the word <em>bad</em>.</p><p className="text-lg leading-relaxed">Deep NLP systems learn representations from data so that useful language patterns can support classification, extraction, retrieval, translation or generation. They do not receive strings directly: the first job is a consistent conversion from text to integer IDs.</p><NLPPipelineFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Tokenization Decides the Units the Model Reads</h2><p className="text-lg leading-relaxed">A <strong>token</strong> is one unit produced by a tokenizer. It may be a whole word, part of a word, a character or a byte-level unit. The tokenizer owns a vocabulary that maps each recognized token to an integer ID. Special tokens can mark padding, unknown pieces, sequence boundaries or task-specific roles.</p><TokenizationFigure /><p className="text-lg leading-relaxed">Token IDs are identifiers, not quantities. ID 900 is not “larger in meaning” than ID 12. The numbers [731,42,19,87,905,7] in the opening diagram are illustrative IDs; a real tokenizer returns its own fixed mapping. A model uses each ID only as a row address in an embedding table. When using pretrained weights, use the matching tokenizer: vocabulary, special IDs, casing rules and segmentation are part of the learned system.</p><div className="not-prose rounded-xl border-l-4 border-amber-500 bg-amber-50 p-5"><p className="font-bold text-amber-950">Do not clean text automatically</p><p className="mt-2 text-sm leading-relaxed text-amber-900">Lowercasing, deleting punctuation, removing stop words or stemming can destroy signals and disagree with a pretrained tokenizer. Preserve raw text by default, normalize only for a justified reason, and test the effect on real examples such as negation, emojis, codes and names.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">An Embedding Turns an ID Into a Learnable Vector</h2><p className="text-lg leading-relaxed">A vocabulary of 50,000 tokens could represent each token with a 50,000-position one-hot vector, but that vector is mostly zeros and says nothing about related usage. An <strong>embedding table</strong> stores a shorter dense vector in each vocabulary row. If a developer chooses width 128, the table shape is [50,000,128]; an input with 8 messages and 20 tokens becomes [8,20,128]. The vocabulary size comes from the tokenizer, width is a model-design choice, and the table values are initialized then learned.</p><div className="not-prose rounded-2xl border border-blue-200 bg-blue-50 p-5 md:p-6"><h3 className="text-xl font-bold text-blue-950">Cosine similarity compares vector direction</h3><p className="mt-3 overflow-x-auto whitespace-nowrap font-mono text-base text-blue-950">cos(a,b) = (a · b) / (‖a‖ ‖b‖)</p><p className="mt-3 text-sm text-blue-900">Use manually chosen two-dimensional vectors a=[1,1] and b=[0.8,0.6] so every operation is visible. Real embedding vectors are model-produced and usually much wider.</p><div className="mt-3 grid gap-3 md:grid-cols-3"><p className="rounded-lg bg-white p-4 font-mono text-sm"><strong>Multiply and add</strong><br />a·b = 1×0.8 + 1×0.6<br />= 1.4</p><p className="rounded-lg bg-white p-4 font-mono text-sm"><strong>Measure each length</strong><br />‖a‖=√2≈1.414<br />‖b‖=√(0.64+0.36)=1</p><p className="rounded-lg bg-white p-4 font-mono text-sm"><strong>Divide out length</strong><br />cos(a,b)=1.4/(1.414×1)<br />≈ <strong>0.990</strong></p></div><p className="mt-3 text-sm leading-relaxed text-blue-900"><strong>Why divide?</strong> The dot product grows with vector length as well as alignment. Dividing by both lengths isolates direction, so large-magnitude vectors do not appear similar merely because they are large. A value near 1 means similar direction; 0 means perpendicular; −1 means opposite direction.</p></div><ContextEmbeddingFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Define the Prediction Unit Before Choosing a Model</h2><p className="text-lg leading-relaxed">“Analyze support messages” is not yet a machine-learning task. Do you need one intent per message, one entity tag per token, a similarity score between tickets, or a generated reply? This decision controls the annotation format and the representation passed to the final task head.</p><TaskShapesFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">One Text-Classification Prediction With Numbers</h2><p className="text-lg leading-relaxed">Assume a contextual encoder has read “the motor is overheating.” The developer defined three labels—normal, warning and critical—so the final linear layer must output three numbers. For a transparent example, use model-produced raw scores called <strong>logits</strong>: normal=0.2, warning=1.1, critical=2.0. These logits are illustrative outputs, not probabilities or developer-set thresholds.</p><div className="not-prose rounded-2xl bg-slate-950 p-5 text-white md:p-6"><p className="font-mono text-lg font-bold">p<sub>i</sub> = e<sup>zᵢ</sup> / Σ<sub>j</sub>e<sup>zⱼ</sup></p><p className="mt-3 text-sm leading-relaxed text-slate-200">zᵢ is one logit and pᵢ is its softmax probability. Exponentiation makes every score positive and accentuates differences; dividing by their sum normalizes the results to 1. Subtracting the largest logit first is a numerically safer but mathematically equivalent implementation.</p></div><div className="not-prose mt-5 rounded-2xl border border-indigo-200 bg-indigo-50 p-5 md:p-6"><div className="grid gap-3 md:grid-cols-3"><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>1. Exponentiate</strong><br />e⁰·²=1.221<br />e¹·¹=3.004<br />e²=7.389</p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>2. Normalize</strong><br />sum=11.614<br />p≈[0.105, 0.259, <strong>0.636</strong>]</p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>3. Compare with label</strong><br />true class=critical<br />loss=−ln(0.636)<br />≈ <strong>0.453</strong></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> critical is the most likely class, but 0.636 is not certainty. The true label comes from the dataset; cross-entropy uses its probability and training changes the model weights to lower this loss over many examples. Calibration must be evaluated separately.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Static Embeddings, Recurrent Models and Transformers</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[980px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Approach</th><th className="p-3 text-left">Representation</th><th className="p-3 text-left">Good starting situation</th><th className="p-3 text-left">Limitation</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["TF-IDF + linear model","Sparse word/subword counts","Fast, interpretable baseline on labelled text","Weak handling of order and contextual meaning"],["Static embedding + CNN/RNN","One learned/pretrained vector per token type","Compact custom baseline with moderate data","Same base vector for every occurrence"],["LSTM/GRU","Context evolves sequentially","Streaming or smaller sequence models","Sequential training; long context remains difficult"],["Pretrained Transformer encoder","Contextual vector per occurrence","Classification, retrieval or extraction with transfer learning","Context length, compute and domain mismatch"],["Pretrained generative model","Autoregressive or encoder–decoder tokens","Generation and instruction-based tasks","Hallucination, cost, decoding and safety concerns"]].map(([method,rep,use,limit])=><tr key={method} className="align-top"><td className="p-3 font-bold text-indigo-800">{method}</td><td className="p-3">{rep}</td><td className="p-3 text-emerald-800">{use}</td><td className="p-3 text-rose-800">{limit}</td></tr>)}</tbody></table></div><p className="mt-5 text-lg leading-relaxed">Always establish a simple baseline. A fine-tuned Transformer is not automatically better than TF-IDF for short, domain-specific categories, especially when latency, interpretability or training data is constrained.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Fine-Tuning Reuses Language Representations</h2><p className="text-lg leading-relaxed"><strong>Pretraining</strong> learns broad patterns from a large text objective. <strong>Fine-tuning</strong> continues training on a smaller labelled task. A sequence-classification model usually adds a randomly initialized classification head on top of a pretrained encoder; the tokenizer and encoder start with learned knowledge rather than random weights.</p><div className="not-prose grid gap-4 md:grid-cols-3">{[["1. Match","Choose a checkpoint and its exact tokenizer for language, domain, licence and maximum length."],["2. Adapt","Tokenize examples, dynamically pad batches, add the correct task head and fine-tune with a small learning rate."],["3. Validate","Measure task metrics, subgroup errors, calibration, latency, memory and behavior on shifted/real text."]].map(([title,body])=><div key={title} className="rounded-xl border border-indigo-200 bg-indigo-50 p-5"><p className="font-bold text-indigo-950">{title}</p><p className="mt-2 text-sm leading-relaxed text-indigo-900">{body}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Tokenize and Inspect Before You Train</h2><p className="text-lg leading-relaxed">This compact example prepares two messages for a pretrained sequence classifier. Dynamic padding makes each batch only as long as its longest member. Truncation prevents inputs from exceeding the model limit—but any discarded text is lost, so inspect truncation rates.</p><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">pretrained_text_classification.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(
    checkpoint,
    num_labels=3,
)

texts = [
    "Pump A is not safe to restart.",
    "Routine inspection completed successfully.",
]
batch = tokenizer(
    texts,
    padding=True,       # pad to longest item in this batch
    truncation=True,    # enforce the model input limit
    return_tensors="pt",
)

print(tokenizer.convert_ids_to_tokens(batch["input_ids"][0]))
print(batch["attention_mask"])  # 1=real token, 0=padding here

with torch.no_grad():
    logits = model(**batch).logits
probabilities = logits.softmax(dim=-1)
 print(probabilities)`}</pre></div><div className="not-prose mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold text-blue-950">Which values are choices?</p><p className="mt-2 text-sm leading-relaxed text-blue-900">The checkpoint name selects a pretrained vocabulary, tokenizer rules, encoder width and learned weights. <code>num_labels=3</code> comes from this task&apos;s label set. The two strings are data. Padding and truncation are preprocessing choices that must match the deployment policy.</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold text-emerald-950">What happens inside?</p><p className="mt-2 text-sm leading-relaxed text-emerald-900">The tokenizer returns integer <code>input_ids</code> and an <code>attention_mask</code>. <code>model(**batch)</code> looks up embeddings, builds contextual states and applies the three-output classifier head. <code>no_grad</code> avoids storing training gradients; <code>softmax(dim=-1)</code> normalizes across the three labels for each message.</p></div></div><p className="mt-4 text-sm leading-relaxed text-slate-600">The classifier head above is untrained for your three labels until fine-tuned. Random head probabilities are not useful predictions. Pin a reviewed model revision in production and record tokenizer/model versions together.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Build an Evaluation Split That Matches Reality</h2><SplitLeakageFigure /><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[920px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Task</th><th className="p-3 text-left">Useful metrics</th><th className="p-3 text-left">What an average can hide</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Imbalanced classification","Per-class precision, recall, F1; confusion matrix","Rare but costly class failure"],["Entity extraction","Span/entity-level precision, recall, F1","Partial boundaries and entity types"],["Retrieval/similarity","Recall@k, MRR, task-specific thresholds","Poor performance on hard negatives"],["Generation","Task metrics plus human/factual evaluation","Fluent but unsupported or unsafe output"],["Production classifier","Calibration, abstention coverage, drift slices","Confidence that does not match correctness"]].map(([task,metrics,hidden])=><tr key={task}><td className="p-3 font-bold text-indigo-800">{task}</td><td className="p-3">{metrics}</td><td className="p-3 text-rose-800">{hidden}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Practical NLP Debugging Path</h2><div className="not-prose grid gap-3 md:grid-cols-2">{[["1. Inspect raw examples","Find empty text, encoding damage, label errors, duplicates and sensitive information."],["2. Inspect tokens and masks","Check special tokens, fragmentation, truncation, padding IDs and attention-mask polarity."],["3. Overfit a tiny clean set","If the model cannot memorize it, verify head size, loss, labels, gradients and parameter updates."],["4. Compare a simple baseline","TF-IDF or a compact model can reveal whether the neural pipeline adds value."],["5. Slice errors","Break metrics down by label, language, length, domain, negation and important user groups."],["6. Test realistic shift","Use later time periods, new users/templates and adversarially simple wording changes."]].map(([title,body])=><div key={title} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="font-bold text-indigo-900">{title}</p><p className="mt-2 text-sm leading-relaxed text-slate-700">{body}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Limitations Are Part of the Model Design</h2><p className="text-lg leading-relaxed">Language datasets reproduce errors, stereotypes and exclusions in their sources. Tokenizers can handle languages and domain terminology unevenly. Context windows truncate information; generated text can be unsupported; labels can encode subjective policy rather than objective truth. Larger models also increase latency, cost and deployment complexity.</p><p className="text-lg leading-relaxed">For high-impact systems, document intended use, excluded use, subgroup performance, privacy handling, human escalation and monitoring. A confident language output is still a statistical model result, not proof of correctness.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">From Text to a Reliable NLP System</h2><div className="not-prose rounded-2xl border border-blue-200 bg-blue-50 p-6"><ol className="m-0 space-y-2 pl-5 text-blue-950"><li>Define the prediction unit, deployment boundary and consequences of mistakes.</li><li>Create representative labels and leakage-resistant splits before model tuning.</li><li>Use the tokenizer paired with the pretrained checkpoint; inspect actual tokens, masks and truncation.</li><li>Convert token IDs into embeddings and contextual representations, then attach the task-appropriate head.</li><li>Compare a simple baseline with pretrained and custom neural options under the same evaluation.</li><li>Analyze per-class and subgroup errors, not only one overall score.</li><li>Measure latency, memory, calibration, drift, privacy and human-review needs before deployment.</li></ol></div></section>

    <section><h2 className="mb-4 border-b pb-2 text-2xl font-bold text-indigo-800">Continue Learning</h2><div className="not-prose mb-10 grid gap-4 md:grid-cols-2"><a href="/learn/deep-learning-intro" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Back to Deep Learning</p><p className="m-0 font-bold text-slate-900">Deep Learning Basics and Model Types</p></a><a href="/learn/llm-intro" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Continue to LLMs</p><p className="m-0 font-bold text-slate-900">How Large Language Models Work</p></a></div></section>
  </div>;
}
