import React from "react";

function GraphAnatomyFigure() {
  const nodes = [
    {id:"A",x:110,y:85,detail:"age 18d",color:"#dbeafe",stroke:"#2563eb"},
    {id:"B",x:320,y:155,detail:"age 2y",color:"#fef3c7",stroke:"#d97706"},
    {id:"C",x:135,y:270,detail:"age 8m",color:"#dcfce7",stroke:"#16a34a"},
    {id:"D",x:505,y:270,detail:"age 4y",color:"#ede9fe",stroke:"#7c3aed"},
    {id:"E",x:600,y:85,detail:"age 5d",color:"#fee2e2",stroke:"#dc2626"},
  ];
  const edges = [[0,1,"₹2k"],[2,1,"₹18k"],[1,3,"₹4k"],[4,1,"₹11k"],[4,3,"₹500"]] as const;
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">A graph stores entities and the relationships between them</p><p className="mt-1 text-sm text-slate-600">Example: accounts are nodes; money transfers are directed edges.</p></div><div className="overflow-x-auto p-4 md:p-6"><svg viewBox="0 0 760 360" className="h-auto min-w-[700px] w-full" role="img" aria-labelledby="graph-anatomy-title graph-anatomy-desc"><title id="graph-anatomy-title">Transaction graph with five account nodes and directed edges</title><desc id="graph-anatomy-desc">Account nodes A through E have node features such as account age. Arrows between them represent transfers with amounts as edge features.</desc><defs><marker id="graph-arrow" markerWidth="9" markerHeight="9" refX="8" refY="4.5" orient="auto"><path d="M0 0 L9 4.5 L0 9 Z" fill="#64748b" /></marker></defs><rect width="760" height="360" rx="18" fill="#f8fafc" />{edges.map(([from,to,label],i)=>{const a=nodes[from],b=nodes[to]; const mx=(a.x+b.x)/2,my=(a.y+b.y)/2; return <g key={i}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#64748b" strokeWidth="3" markerEnd="url(#graph-arrow)" /><rect x={mx-26} y={my-15} width="52" height="24" rx="8" fill="white" stroke="#cbd5e1" /><text x={mx} y={my+2} textAnchor="middle" fontSize="11" fontWeight="800" fill="#334155">{label}</text></g>})}{nodes.map(n=><g key={n.id}><circle cx={n.x} cy={n.y} r="45" fill={n.color} stroke={n.stroke} strokeWidth="3" /><text x={n.x} y={n.y-4} textAnchor="middle" fontSize="20" fontWeight="900" fill="#0f172a">{n.id}</text><text x={n.x} y={n.y+17} textAnchor="middle" fontSize="11" fill="#475569">{n.detail}</text></g>)}<rect x="625" y="230" width="110" height="88" rx="14" fill="#fff" stroke="#cbd5e1" /><text x="680" y="254" textAnchor="middle" fontSize="12" fontWeight="800" fill="#0f172a">Graph data</text><text x="680" y="276" textAnchor="middle" fontSize="11" fill="#475569">nodes + features</text><text x="680" y="294" textAnchor="middle" fontSize="11" fill="#475569">edges + features</text><text x="680" y="312" textAnchor="middle" fontSize="11" fill="#475569">optional graph label</text></svg></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">The arrow A→B can differ from B→A, so direction matters. Node features describe an entity; edge features describe a relationship. The graph structure itself is also information.</figcaption></figure>;
}

function MessagePassingFigure() {
  const neighbor = [{name:"A",value:2,x:95,y:85},{name:"C",value:8,x:95,y:245},{name:"D",value:5,x:500,y:85}];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">One message-passing layer updates B from its local neighborhood</p></div><div className="overflow-x-auto p-4 md:p-6"><svg viewBox="0 0 760 350" className="h-auto min-w-[700px] w-full" role="img" aria-labelledby="message-title message-desc"><title id="message-title">Neighbors send features to target node B</title><desc id="message-desc">Nodes A and C have incoming edges to B and send values two and eight. Node D is not an incoming neighbor and sends no message. B combines its own value four with incoming messages.</desc><defs><marker id="msg-arrow" markerWidth="9" markerHeight="9" refX="8" refY="4.5" orient="auto"><path d="M0 0 L9 4.5 L0 9 Z" fill="#4f46e5" /></marker></defs><rect width="760" height="350" rx="18" fill="#f8fafc" />{neighbor.map((n,i)=><g key={n.name}><circle cx={n.x} cy={n.y} r="42" fill={i===2?"#e2e8f0":"#dbeafe"} stroke={i===2?"#94a3b8":"#2563eb"} strokeWidth="2" /><text x={n.x} y={n.y-3} textAnchor="middle" fontSize="18" fontWeight="900" fill="#0f172a">{n.name}</text><text x={n.x} y={n.y+18} textAnchor="middle" fontSize="12" fill="#475569">feature={n.value}</text>{i<2?<><line x1={n.x+45} y1={n.y} x2="285" y2={i===0?"145":"205"} stroke="#4f46e5" strokeWidth="3" markerEnd="url(#msg-arrow)" /><text x="190" y={i===0?"102":"250"} textAnchor="middle" fontSize="12" fontWeight="800" fill="#4338ca">message from {n.name}</text></>:<><line x1="460" y1="115" x2="405" y2="145" stroke="#cbd5e1" strokeWidth="2" strokeDasharray="6 5" /><text x="515" y="150" fontSize="11" fill="#64748b">not B&apos;s incoming neighbor</text></>}</g>)}<circle cx="340" cy="175" r="58" fill="#fef3c7" stroke="#d97706" strokeWidth="3" /><text x="340" y="167" textAnchor="middle" fontSize="22" fontWeight="900" fill="#92400e">B</text><text x="340" y="191" textAnchor="middle" fontSize="12" fill="#92400e">own feature=4</text><line x1="401" y1="175" x2="520" y2="175" stroke="#16a34a" strokeWidth="4" markerEnd="url(#msg-arrow)" /><rect x="545" y="110" width="180" height="130" rx="18" fill="#dcfce7" stroke="#16a34a" strokeWidth="2" /><text x="635" y="140" textAnchor="middle" fontSize="14" fontWeight="900" fill="#166534">AGGREGATE + UPDATE</text><text x="635" y="170" textAnchor="middle" fontSize="13" fill="#166534">mean(2,4,8)=4.67</text><text x="635" y="195" textAnchor="middle" fontSize="13" fill="#166534">ReLU(0.5×4.67+0.1)</text><text x="635" y="220" textAnchor="middle" fontSize="15" fontWeight="900" fill="#166534">new h′B = 2.43</text></svg></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">Aggregation must not depend on arbitrary neighbor ordering. Sum, mean, max and attention-weighted sums are common permutation-invariant choices.</figcaption></figure>;
}

function HopFigure() {
  const levels = [["B","target","#fef3c7","#d97706"],["A, C","1-hop neighbors","#dbeafe","#2563eb"],["E, F, G","2-hop neighbors","#ede9fe","#7c3aed"]];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">Stacking layers expands the receptive field by graph hops</p><div className="mt-5 flex flex-col items-center gap-3">{levels.map(([nodes,label,bg,border],i)=><React.Fragment key={nodes}><div className="w-full max-w-lg rounded-xl border-2 p-4 text-center" style={{backgroundColor:bg,borderColor:border}}><p className="font-mono font-black text-slate-900">{nodes}</p><p className="mt-1 text-xs text-slate-600">{label}</p></div>{i<2&&<span className="text-2xl font-black text-slate-400">↓</span>}</React.Fragment>)}</div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">After one layer, B can use immediate neighbors. After two, information can arrive from neighbors-of-neighbors. More layers do not automatically help: states may become too similar and distant information can be compressed.</figcaption></figure>;
}

function GraphTasksFigure() {
  const tasks = [["Node prediction","one output per node","fraud risk for account B"],["Edge/link prediction","one output per node pair/edge","will A connect to D?"],["Graph prediction","one output for whole graph","is this molecule toxic?"]];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">The readout changes with the prediction target</p><div className="mt-5 grid gap-4 md:grid-cols-3">{tasks.map(([task,unit,example],i)=><div key={task} className="rounded-xl border p-5 text-center" style={{borderColor:["#2563eb","#7c3aed","#16a34a"][i],backgroundColor:["#eff6ff","#f5f3ff","#f0fdf4"][i]}}><p className="font-bold text-slate-900">{task}</p><p className="mt-2 text-xs font-bold text-slate-500">{unit}</p><p className="mt-4 rounded-lg bg-white p-3 text-sm text-slate-700">{example}</p></div>)}</div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">Graph prediction needs a permutation-invariant pooling/readout such as sum, mean or learned attention over node embeddings. Link prediction needs careful negative-edge sampling and time-aware evaluation.</figcaption></figure>;
}

const modelRows = [
  ["GCN", "Degree-normalized sum of transformed neighbors", "Small/medium homophilous graphs and a clear baseline", "Full-neighborhood computation; smoothing assumptions"],
  ["GraphSAGE", "Samples neighbors and aggregates them", "Inductive use and larger graphs", "Sampling adds variance and can miss neighbors"],
  ["GAT", "Learns attention weights over neighbors", "Neighbor importance may vary", "More compute; weights are not guaranteed explanations"],
  ["Relational GNN", "Separate relation-aware transformations", "Knowledge graphs and typed edges", "Parameters/cost grow with relation design"],
  ["Graph Transformer", "Attention with graph/position structure", "Rich long-range interactions", "Potential quadratic cost and structural encoding choices"],
] as const;

export function GraphNeuralNetworksContent() {
  return <div className="prose prose-lg max-w-none text-slate-700">
    <section className="not-prose mb-10 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-cyan-950 to-emerald-800 px-6 py-10 text-white shadow-xl md:px-10 md:py-12"><p className="mb-3 text-sm font-extrabold uppercase tracking-[0.18em] text-emerald-200">Deep Learning · Connected Data</p><h2 className="max-w-4xl text-3xl font-black leading-tight md:text-5xl">Graph Neural Networks: Learning From Entities and Relationships</h2><p className="mt-5 max-w-4xl text-lg leading-relaxed text-cyan-50 md:text-xl">A graph represents entities as nodes and their relationships as edges. A Graph Neural Network (GNN) learns by letting connected nodes exchange information. We will build a transaction graph, calculate one complete message-passing update, connect layers to multi-hop context, distinguish node/link/graph tasks, compare GCN, GraphSAGE and GAT, implement node classification, and diagnose leakage, over-smoothing and scale problems.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">When Relationships Are Part of the Data</h2><p className="text-lg leading-relaxed">Suppose two bank accounts have identical balances and ages. One receives transfers from long-established payroll accounts; the other receives a burst from newly created accounts that also connect to known fraud. A row-by-row model sees the account features but loses this relational evidence.</p><p className="text-lg leading-relaxed">A graph G=(V,E) contains a set of <strong>nodes</strong> V and <strong>edges</strong> E. Nodes may have feature vectors such as account age and transaction count. Edges may be directed, carry an amount or timestamp, and have different types. Graph construction is a modelling decision: an edge must represent a defensible relationship, not merely convenience.</p><GraphAnatomyFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Message Passing: Gather, Combine, Update</h2><p className="text-lg leading-relaxed">A message-passing layer updates each node in three conceptual operations. First, create a message from each relevant neighbor (and optionally the edge). Second, aggregate incoming messages with an order-independent operation because a graph has no natural first or last neighbor. Third, combine the result with the node&apos;s current representation so its own evidence is not automatically erased.</p><div className="not-prose rounded-2xl bg-slate-950 p-5 text-white md:p-6"><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-emerald-300">General message-passing layer</p><div className="mt-3 overflow-x-auto whitespace-nowrap font-mono text-sm leading-8"><p>m<sub>j→i</sub><sup>(k)</sup> = φ<sup>(k)</sup>(h<sub>i</sub><sup>(k−1)</sup>, h<sub>j</sub><sup>(k−1)</sup>, e<sub>j,i</sub>)</p><p>m<sub>i</sub><sup>(k)</sup> = AGG<sub>j∈N(i)</sub> m<sub>j→i</sub><sup>(k)</sup></p><p>h<sub>i</sub><sup>(k)</sup> = γ<sup>(k)</sup>(h<sub>i</sub><sup>(k−1)</sup>, m<sub>i</sub><sup>(k)</sup>)</p></div><p className="mt-3 text-sm leading-relaxed text-slate-200">h<sup>(0)</sup> comes from the node-feature data; later h values are model-produced. Edge feature e comes from data when available. Neighborhood N(i) comes from the graph&apos;s edge list. The functions φ and γ contain shared learned weights; AGG is a developer-selected sum, mean or max rule applied identically at every node.</p></div><MessagePassingFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">One Mean-Aggregation Update With Numbers</h2><p className="text-lg leading-relaxed">For a complete scalar teaching example, use B&apos;s feature 4 and neighbor features A=2 and C=8. These stand in for feature values from graph data. Include B itself, take a chosen mean aggregation, then use illustrative trained parameters W=0.5 and b=0.1 before ReLU. A real model learns W and b across all training nodes; it does not choose them separately for B.</p><div className="not-prose rounded-2xl border border-indigo-200 bg-indigo-50 p-5 md:p-6"><div className="grid gap-3 md:grid-cols-3"><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>1. Include self</strong><br />values = [2,4,8]<br /><span className="font-sans text-xs text-slate-600">keeps B&apos;s own evidence</span></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>2. Aggregate</strong><br />mean=(2+4+8)/3<br />=<strong>4.667</strong><br /><span className="font-sans text-xs text-slate-600">division controls degree scale</span></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>3. Update</strong><br />ReLU(0.5×4.667+0.1)<br />=ReLU(2.433)=<strong>2.433</strong><br /><span className="font-sans text-xs text-slate-600">learned transform, then nonlinearity</span></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> B&apos;s new representation contains its own feature and local-neighbor context. Reordering A and C would not change the mean, which is essential because graph neighbors have no meaningful list order.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A GCN Normalizes Neighbor Contributions</h2><p className="text-lg leading-relaxed">A Graph Convolutional Network (GCN) adds self-loops, transforms node features and sums neighbors with degree normalization. The normalization keeps high-degree nodes from simply accumulating much larger values because they have more edges.</p><div className="not-prose rounded-2xl bg-slate-950 p-5 text-white md:p-6"><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-emerald-300">One GCN layer in matrix form</p><p className="mt-2 overflow-x-auto whitespace-nowrap font-mono text-xl font-bold">H<sup>(k+1)</sup> = σ(D̃<sup>−1/2</sup>ÃD̃<sup>−1/2</sup>H<sup>(k)</sup>W<sup>(k)</sup>)</p><div className="mt-4 grid gap-3 md:grid-cols-4"><p className="rounded-lg bg-slate-800 p-3 text-xs leading-relaxed"><strong className="text-emerald-300">Ã=A+I</strong><br />Graph edges plus one self-edge per node.</p><p className="rounded-lg bg-slate-800 p-3 text-xs leading-relaxed"><strong className="text-emerald-300">D̃<sup>−1/2</sup> on both sides</strong><br />Balances source and destination degree.</p><p className="rounded-lg bg-slate-800 p-3 text-xs leading-relaxed"><strong className="text-emerald-300">H<sup>(k)</sup>W<sup>(k)</sup></strong><br />Learned matrix W mixes input features.</p><p className="rounded-lg bg-slate-800 p-3 text-xs leading-relaxed"><strong className="text-emerald-300">σ</strong><br />Activation adds nonlinearity after aggregation.</p></div><p className="mt-3 text-sm leading-relaxed text-slate-200">A and D are calculated from the provided graph, H<sup>(0)</sup> comes from node features, W is initialized then learned, and σ is chosen with the architecture. This is a common undirected GCN formulation; directed or typed graphs often need different operators.</p></div><HopFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Output Can Belong to a Node, Edge or Whole Graph</h2><GraphTasksFigure /><p className="text-lg leading-relaxed">In semi-supervised node classification, message passing can use the graph and features for all nodes while the loss is calculated only on labelled training nodes. Validation and test labels must remain outside the training loss, and the evaluation protocol must state whether their features/edges were visible.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">GCN, GraphSAGE and GAT Change the Neighborhood Rule</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[1020px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Model family</th><th className="p-3 text-left">How neighbors contribute</th><th className="p-3 text-left">Reasonable starting situation</th><th className="p-3 text-left">Important limitation</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{modelRows.map(([model,rule,use,limit])=><tr key={model} className="align-top"><td className="p-3 font-bold text-indigo-800">{model}</td><td className="p-3">{rule}</td><td className="p-3 text-emerald-800">{use}</td><td className="p-3 text-rose-800">{limit}</td></tr>)}</tbody></table></div><p className="mt-5 text-lg leading-relaxed">Choose from graph properties and deployment. GCN-style smoothing often fits <strong>homophily</strong>, where connected nodes tend to share labels/features. Fraud or biological graphs can be <strong>heterophilous</strong>, where unlike nodes connect; blindly averaging neighbors may erase the distinction you need.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Two-Layer Node Classifier With PyTorch Geometric</h2><p className="text-lg leading-relaxed">x stores one feature vector per node as [num_nodes, num_features]. edge_index stores source and destination node IDs as [2, num_edges]. The model produces one logit vector per node, but cross-entropy is calculated only on the training mask.</p><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">gcn_node_classifier.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`import torch
from torch import nn
from torch_geometric.nn import GCNConv

class NodeClassifier(nn.Module):
    def __init__(self, input_features, hidden, classes):
        super().__init__()
        self.conv1 = GCNConv(input_features, hidden)
        self.conv2 = GCNConv(hidden, classes)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        x = nn.functional.dropout(x, p=0.4, training=self.training)
        return self.conv2(x, edge_index)  # [nodes, classes]

model = NodeClassifier(data.num_features, hidden=32, classes=3)
optimizer = torch.optim.AdamW(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
optimizer.zero_grad()
logits = model(data.x, data.edge_index)
loss = nn.CrossEntropyLoss()(
    logits[data.train_mask],
    data.y[data.train_mask],
)
loss.backward()
optimizer.step()`}</pre></div><div className="not-prose mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold text-blue-950">Where the dimensions come from</p><p className="mt-2 text-sm leading-relaxed text-blue-900"><code>data.num_features</code> is read from the dataset. Hidden width 32, dropout probability 0.4, learning rate 0.01 and weight decay 0.0005 are chosen hyperparameters. Output size 3 comes from the three node labels. If the graph has 1,000 nodes, logits have shape [1000,3].</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold text-emerald-950">What the framework does</p><p className="mt-2 text-sm leading-relaxed text-emerald-900"><code>GCNConv</code> adds normalized neighbor aggregation and a learned feature transform. During <code>model.train()</code>, dropout independently zeros each hidden value with probability 0.4; the actual fraction in one finite batch can be higher or lower than exactly 40%. The boolean training mask selects labelled training nodes before cross-entropy; gradients still flow through graph computations that produced those nodes&apos; logits.</p></div></div><p className="mt-4 text-sm leading-relaxed text-slate-600">This is a transductive full-graph teaching example. Large or changing graphs often require neighbor sampling, subgraph batching and an inductive evaluation plan.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Graph Splits Can Leak Through Structure</h2><div className="not-prose grid gap-4 md:grid-cols-2">{[["Time leakage","A future transfer edge, citation or interaction appears while predicting an earlier event.","Build time-respecting graph snapshots and timestamp every feature/edge."],["Identity leakage","The same user, molecule scaffold or near-duplicate subgraph crosses splits.","Group by deployment identity or scaffold, not random rows."],["Label-derived features","A node feature or edge was constructed from labels that should be unknown.","Audit feature provenance and rebuild using prediction-time information only."],["Negative-edge leakage","Random non-edges include pairs that become positive later or are impossible candidates.","Use time-aware, task-valid negative sampling." ]].map(([title,problem,fix])=><div key={title} className="rounded-xl border border-rose-200 bg-rose-50 p-5"><p className="font-bold text-rose-950">{title}</p><p className="mt-2 text-sm leading-relaxed text-rose-900">{problem}</p><p className="mt-3 text-xs font-bold text-indigo-800">Check: {fix}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why Deeper Is Not Automatically Better</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[960px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Failure</th><th className="p-3 text-left">What happens</th><th className="p-3 text-left">Possible response</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Over-smoothing","Repeated aggregation makes node representations too similar","Use fewer layers, residual/initial connections, normalization or specialized operators"],["Over-squashing","Exponentially many distant signals are compressed through narrow representations","Rewire/augment structure, use positional encodings or architectures for long range"],["Neighbor explosion","Sampling all multi-hop neighbors becomes too expensive","Neighbor/subgraph sampling, caching and distributed graph systems"],["Noisy/adversarial edges","Bad relationships spread misleading information","Edge filtering/weighting, robust training and domain rules"],["Cold-start nodes","New node has few features or connections","Use inductive feature encoders and explicit cold-start evaluation"],["Heterophily","Connected nodes may have different labels","Use operators designed/tested for heterophilous structure; keep feature-only baseline"]].map(([failure,happens,response])=><tr key={failure} className="align-top"><td className="p-3 font-bold text-slate-900">{failure}</td><td className="p-3 text-rose-800">{happens}</td><td className="p-3 text-indigo-800">{response}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Decide Whether You Need a GNN</h2><p className="text-lg leading-relaxed">A GNN is justified when relationships are available at prediction time and add stable signal beyond node features. Start with a feature-only model, then add simple graph statistics, then compare a GNN under the same split. This reveals whether the graph—not just model capacity—is contributing.</p><p className="text-lg leading-relaxed">Graph structure can expose sensitive relationships and amplify network bias. Document how edges were created, who may be excluded, how often the graph changes, and whether a prediction can unfairly propagate one node&apos;s behavior to its neighbors.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The GNN in One Connected Explanation</h2><div className="not-prose rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><ul className="m-0 space-y-2 pl-5 text-emerald-950"><li>A graph represents entities as nodes, relationships as edges, and attributes as features.</li><li>Message passing creates neighbor messages, aggregates them without depending on order, and updates each node.</li><li>One layer uses one-hop context; stacked layers reach farther but can over-smooth or over-squash information.</li><li>GCN normalizes neighbor sums, GraphSAGE samples/aggregates, and GAT learns neighbor weights.</li><li>Node, link and graph tasks require different outputs, losses and split strategies.</li><li>Graph construction, leakage and deployment-time edge availability are part of the model—not preprocessing details.</li></ul></div></section>

    <section><h2 className="mb-4 border-b pb-2 text-2xl font-bold text-indigo-800">Continue Learning</h2><div className="not-prose mb-10 grid gap-4 md:grid-cols-2"><a href="/learn/self-supervised-few-shot-learning" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Previous concept</p><p className="m-0 font-bold text-slate-900">Self-Supervised and Few-Shot Learning</p></a><a href="/learn/saving-deploying-deep-models" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Next concept</p><p className="m-0 font-bold text-slate-900">Saving, Loading &amp; Deploying Deep Models</p></a></div></section>
  </div>;
}
