import React from "react";

function ShapeProgressionFigure() {
  const items = [
    ["Scalar", "7", "shape [ ]", "one value"],
    ["Vector", "[2, 5, 8]", "shape [3]", "three values on one axis"],
    ["Matrix", "[[1,2,3],[4,5,6]]", "shape [2,3]", "two rows × three columns"],
    ["3-D tensor", "2 × 3 × 4", "shape [2,3,4]", "three named axes"],
    ["Batch tensor", "N × C × H × W", "shape [8,3,32,32]", "eight colour images"],
  ];
  return (
    <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">From one number to a batch: each new axis answers another question</p></div>
      <div className="overflow-x-auto p-5 md:p-6">
        <div className="flex min-w-[1000px] items-stretch gap-3">
          {items.map(([name, value, shape, meaning], index) => (
            <React.Fragment key={name}>
              <div className="w-44 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-center">
                <p className="text-xs font-extrabold uppercase tracking-wide text-indigo-700">{name}</p>
                <p className="mt-3 break-words font-mono font-black text-indigo-950">{value}</p>
                <p className="mt-3 rounded-lg bg-white p-2 font-mono text-xs text-emerald-800">{shape}</p>
                <p className="mt-2 text-xs leading-relaxed text-slate-600">{meaning}</p>
              </div>
              {index < items.length - 1 && <span className="flex items-center text-2xl font-black text-slate-400">→</span>}
            </React.Fragment>
          ))}
        </div>
      </div>
      <figcaption className="border-t border-slate-100 px-5 py-3 text-sm text-slate-600">An axis is one direction in which values are arranged. Shape lists the length of every axis in order; the names N, C, H and W are meanings assigned by the data pipeline.</figcaption>
    </figure>
  );
}

function LayerShapeFigure() {
  return (
    <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">Why [4,3] multiplied by [3,2] produces [4,2]</p></div>
      <div className="overflow-x-auto p-5 md:p-7">
        <div className="grid min-w-[760px] grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-4 text-center">
          <div className="rounded-2xl border-2 border-blue-300 bg-blue-50 p-5"><p className="font-mono text-2xl font-black text-blue-950">X [4,3]</p><p className="mt-2 text-sm text-blue-900">4 examples<br />3 features per example</p></div>
          <div><p className="text-3xl font-black text-slate-400">×</p></div>
          <div className="rounded-2xl border-2 border-violet-300 bg-violet-50 p-5"><p className="font-mono text-2xl font-black text-violet-950">W [3,2]</p><p className="mt-2 text-sm text-violet-900">3 incoming features<br />2 neurons</p></div>
          <div><p className="text-3xl font-black text-slate-400">→</p></div>
          <div className="rounded-2xl border-2 border-emerald-300 bg-emerald-50 p-5"><p className="font-mono text-2xl font-black text-emerald-950">Z [4,2]</p><p className="mt-2 text-sm text-emerald-900">4 examples<br />2 neuron scores each</p></div>
        </div>
        <div className="mx-auto mt-5 max-w-2xl rounded-xl bg-slate-900 p-4 text-center text-sm text-white"><strong className="text-amber-300">The inner 3s match</strong> because each example supplies exactly the three features each neuron expects. They are consumed by dot products. The outer 4 and 2 remain.</div>
      </div>
    </figure>
  );
}

function MathJourneyFigure() {
  const steps = [
    ["1", "numbers", "x, w, b", "Represent one example and what the model can change", "#dbeafe", "#2563eb"],
    ["2", "dot product", "z = w·x + b", "Combine inputs with learned importance", "#ede9fe", "#7c3aed"],
    ["3", "function", "ŷ = f(z)", "Turn the score into the required output", "#fef3c7", "#d97706"],
    ["4", "loss", "L(y, ŷ)", "Measure how wrong the prediction is", "#fee2e2", "#dc2626"],
    ["5", "gradient", "∇wL", "Tell each weight how loss changes", "#dcfce7", "#16a34a"],
  ];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">The small set of mathematical ideas used during one learning step</p></div><div className="overflow-x-auto p-5 md:p-7"><div className="flex min-w-[1050px] items-stretch gap-3">{steps.map(([n,title,formula,meaning,bg,border],i)=><React.Fragment key={n}><div className="w-[180px] rounded-xl border-2 p-4 text-center" style={{backgroundColor:bg,borderColor:border}}><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-white font-black" style={{color:border}}>{n}</span><p className="mt-3 font-bold text-slate-950">{title}</p><p className="mt-2 font-mono text-sm text-slate-800">{formula}</p><p className="mt-3 text-xs leading-relaxed text-slate-600">{meaning}</p></div>{i<steps.length-1&&<span className="flex items-center text-2xl font-black text-slate-400">→</span>}</React.Fragment>)}</div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">Linear algebra computes the prediction; functions shape it; calculus measures sensitivity; probability helps interpret uncertain outputs. These ideas reappear throughout the course.</figcaption></figure>;
}

function GradientFigure() {
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">For L(w)=w² at w=3, the derivative is positive</p><div className="overflow-x-auto"><svg viewBox="0 0 760 330" className="min-w-[680px]" role="img" aria-label="The curve L equals w squared with a positive slope at w equals 3 and a gradient-descent update moving left toward the minimum"><defs><marker id="gradArrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#16a34a"/></marker></defs><line x1="75" y1="270" x2="710" y2="270" stroke="#475569" strokeWidth="2"/><line x1="75" y1="270" x2="75" y2="35" stroke="#475569" strokeWidth="2"/><text x="690" y="302" fontSize="14" fill="#334155">weight w</text><text x="30" y="55" fontSize="14" fill="#334155" transform="rotate(-90 30 55)">loss L</text><path d="M115 55 Q380 465 650 55" fill="none" stroke="#4f46e5" strokeWidth="5"/><circle cx="555" cy="175" r="9" fill="#dc2626"/><line x1="490" y1="235" x2="620" y2="115" stroke="#dc2626" strokeWidth="3"/><text x="510" y="92" fontSize="14" fontWeight="700" fill="#991b1b">at w=3, slope dL/dw=+6</text><line x1="555" y1="220" x2="435" y2="260" stroke="#16a34a" strokeWidth="4" markerEnd="url(#gradArrow)"/><text x="465" y="210" fontSize="14" fontWeight="700" fill="#166534">subtract +η·6: move left</text><circle cx="380" cy="270" r="9" fill="#16a34a"/><text x="380" y="318" textAnchor="middle" fontSize="14" fontWeight="700" fill="#166534">minimum at w=0</text></svg></div><figcaption className="text-sm leading-relaxed text-slate-600">The tangent rises from left to right, so its slope is positive. Gradient descent uses w<sub>new</sub>=w−η(6); subtracting a positive number decreases w and moves the point left toward the minimum.</figcaption></figure>;
}

const symbolRows = [
  ["Scalar", "one number", "temperature 24; loss 0.18", "no axes / shape []"],
  ["Vector", "ordered list", "one house: [area, bedrooms, age]", "one axis / shape [3]"],
  ["Matrix", "rows and columns", "four houses × three features", "two axes / shape [4,3]"],
  ["Higher-order tensor", "more axes", "image batch: examples × channels × height × width", "four axes / [N,C,H,W]"],
];

export function MathFoundationsContent() {
  return <div className="prose prose-lg max-w-none text-slate-700">
    <section className="not-prose mb-10 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-blue-950 to-violet-800 px-6 py-10 text-white shadow-xl md:px-10 md:py-12"><p className="mb-3 text-sm font-extrabold uppercase tracking-[0.18em] text-blue-200">Deep Learning · Essential Mathematics</p><h2 className="max-w-4xl text-3xl font-black leading-tight md:text-5xl">The Math a Neural Network Uses to Learn</h2><p className="mt-5 max-w-4xl text-lg leading-relaxed text-blue-50 md:text-xl">You do not need to finish an advanced mathematics textbook before understanding a neural network. This lesson follows one prediction from input numbers to a weight update, introducing vectors, matrices, dot products, functions, derivatives, gradients, probability and logarithms exactly where each idea becomes useful.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why These Mathematical Tools Appear</h2><p className="text-lg leading-relaxed">A neural network must do three things: store many examples compactly, calculate predictions quickly, and discover how its adjustable weights should change. Linear algebra handles structured numbers and repeated calculations. Calculus describes how a tiny weight change affects error. Probability expresses uncertain choices, while logarithms turn probability products into stable sums and strongly penalize confident mistakes.</p><p className="text-lg leading-relaxed">The symbols are not the lesson; they are a shorter language for operations the model performs. Whenever you see a formula below, read the words beside it first, then reproduce the small calculation.</p><MathJourneyFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Scalars, Vectors, Matrices and Tensors Describe the Shape of Data</h2><p className="text-lg leading-relaxed">A <strong>scalar</strong> is one number, such as one loss value. A <strong>vector</strong> is an ordered list, such as the three features of one house. A <strong>matrix</strong> has rows and columns, so it can store several houses as rows and their features as columns. <strong>Tensor</strong> is the general name for an array with any number of axes; scalars, vectors and matrices are lower-rank tensors.</p><ShapeProgressionFigure /><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[800px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Object</th><th className="p-3 text-left">Plain meaning</th><th className="p-3 text-left">Neural-network example</th><th className="p-3 text-left">Shape</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{symbolRows.map(([name,meaning,example,shape])=><tr key={name}><td className="p-3 font-bold text-indigo-800">{name}</td><td className="p-3">{meaning}</td><td className="p-3 text-slate-700">{example}</td><td className="p-3 font-mono text-emerald-800">{shape}</td></tr>)}</tbody></table></div><p className="mt-5 text-lg leading-relaxed"><strong>Shape</strong> records the length of each axis, in order. A 2×3 matrix has 2 rows and 3 columns. If rows are training examples and columns are features, the matrix contains 2 examples with 3 features each. Order matters: [32,3,224,224] commonly means 32 colour images, while [3,32,224,224] assigns entirely different meanings to the first two axes.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Dot Product Performs One Neuron&apos;s Weighted Sum</h2><p className="text-lg leading-relaxed">A neuron pairs each input with one weight. The weight is an adjustable multiplier: a positive value preserves the input&apos;s direction, a negative value reverses it, and a larger magnitude creates a stronger contribution. Multiplication forms each contribution; addition combines all contributions into one score.</p><div className="not-prose rounded-2xl border border-blue-200 bg-blue-50 p-5 md:p-6"><h3 className="text-xl font-bold text-blue-950">Manual dot product</h3><p className="mt-2 text-slate-700">Choose input vector x=[2,3] and weight vector w=[0.5,1.0] as teaching values. The first input pairs with the first weight because both occupy position 1; the second pair occupies position 2.</p><p className="mt-4 rounded-lg bg-white p-4 font-mono text-sm leading-7">x · w = (2 × 0.5) + (3 × 1.0)<br />= 1 + 3<br />= <strong>4</strong></p><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Why add the products?</strong> The neuron needs one score representing the combined evidence from both inputs. A bias can then shift that score: with b=−1, z=x·w+b=4−1=<strong>3</strong>. Here x would come from data; w and b are teaching parameters that training would normally learn.</p></div><p className="mt-5 text-lg leading-relaxed">A layer evaluates several neurons for several examples at once using <strong>matrix multiplication</strong>. Its compact formula is Z=XW+b: X is the batch, W contains one column of weights for each neuron, b contains one bias per neuron, and Z contains the resulting pre-activation scores.</p><LayerShapeFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Functions Map Inputs to Outputs</h2><p className="text-lg leading-relaxed">A <strong>function</strong> is a rule: supply an input and receive an output. A layer is a function of both its data and its parameters. Several layers compose functions, so a small change early in the network can affect every later result.</p><div className="not-prose grid gap-4 md:grid-cols-3">{[["Linear rule","z=w·x+b","combines information"],["Activation","a=f(z)","adds a useful nonlinear response"],["Loss","L(y,ŷ)","compares target y with prediction ŷ"]].map(([title,formula,use])=><div key={title} className="rounded-xl border border-indigo-200 bg-indigo-50 p-5 text-center"><p className="font-bold text-indigo-950">{title}</p><p className="mt-3 font-mono text-lg text-indigo-800">{formula}</p><p className="mt-3 text-sm text-slate-600">{use}</p></div>)}</div><p className="mt-5 text-lg leading-relaxed">Without nonlinear activations, multiplying several linear layers still collapses to one linear transformation. That is why activation functions are not a decorative extra.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Derivative Asks: “If This Weight Moves, What Happens to Loss?”</h2><p className="text-lg leading-relaxed">A <strong>derivative</strong> is a local rate of change. Imagine the simple function L(w)=w². At w=3, L=9. If w increases to 3.01, L becomes 3.01²=9.0601. The loss changed by 0.0601 when the weight changed by 0.01, so the nearby slope is 0.0601÷0.01=6.01—close to the exact derivative 2w=6 at w=3.</p><GradientFigure /><div className="not-prose rounded-2xl border border-violet-200 bg-violet-50 p-5 md:p-6"><h3 className="text-xl font-bold text-violet-950">Partial derivatives hold the other weights still</h3><p className="mt-2 text-sm leading-relaxed text-slate-700">Use prediction ŷ=2w₁+3w₂ and loss L=½(ŷ−10)². Choose w₁=1 and w₂=1 for this teaching point. Then ŷ=2(1)+3(1)=5 and ŷ−10=−5.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7">∂L/∂w₁ = (ŷ−10) × 2<br />= −5 × 2<br />= <strong>−10</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7">∂L/∂w₂ = (ŷ−10) × 3<br />= −5 × 3<br />= <strong>−15</strong></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700">The 2 and 3 come from the input coefficients multiplying w₁ and w₂. The <strong>gradient</strong> collects both answers as ∇L=[−10,−15]. Its negative entries say that a small increase in either weight would locally reduce this loss; the different magnitudes show different sensitivities.</p></div><p className="mt-5 text-lg leading-relaxed">Gradient descent uses w<sub>new</sub>=w−η(∂L/∂w), where η is a developer-chosen learning rate. A zero gradient can mean a flat point; a very large gradient can cause an unstable step. Neither automatically proves that the model has found the best possible solution.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Chain Rule Connects a Weight to the Final Loss</h2><p className="text-lg leading-relaxed">A deep network is a chain of functions. The <strong>chain rule</strong> multiplies local sensitivities along that chain. For a tiny model ŷ=wx and squared loss L=(ŷ−y)²:</p><div className="not-prose rounded-2xl border border-violet-200 bg-violet-50 p-5 md:p-6"><h3 className="text-xl font-bold text-violet-950">One complete weight update</h3><p className="mt-2 text-slate-700">Use x=2, target y=4, current weight w=1.5 and learning rate η=0.1.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>Forward</strong><br />ŷ=wx=1.5×2=3<br />L=(3−4)²=<strong>1</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>Backward</strong><br />∂L/∂ŷ=2(ŷ−y)=−2<br />∂ŷ/∂w=x=2<br />∂L/∂w=(−2)(2)=<strong>−4</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>Update</strong><br />w<sub>new</sub>=1.5−0.1(−4)<br />=<strong>1.9</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>Check</strong><br />new ŷ=1.9×2=3.8<br />new L=(3.8−4)²=<strong>0.04</strong></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Meaning:</strong> multiplying the two local derivatives tells the weight how it influenced loss. This step reduced loss from 1 to 0.04; other examples and learning rates can behave differently.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Probability and Logarithms Explain Classification Confidence</h2><p className="text-lg leading-relaxed">For mutually exclusive classes, a model often converts scores into a <strong>probability distribution</strong>: non-negative values that sum to 1. A probability of 0.8 is a model statement under its assumptions, not a guarantee that eight of every ten individual predictions are correct. Calibration must be measured.</p><p className="text-lg leading-relaxed">Cross-entropy uses −log(p<sub>true</sub>). If the true-class probability is 0.8, loss is about 0.223; at 0.1 it is about 2.303. The logarithm therefore penalizes a confident wrong prediction much more strongly. Expected value, E[X]=Σxp(x), is a probability-weighted average and appears in risk, loss and sampling objectives.</p><div className="not-prose grid gap-4 md:grid-cols-3">{[["Norm ‖x‖","vector length","gradient clipping; distance"],["Cosine similarity","directional similarity","embeddings; contrastive learning"],["Mean and variance","centre and spread","normalization; initialization"]].map(([name,meaning,use])=><div key={name} className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-mono font-bold text-emerald-950">{name}</p><p className="mt-2 text-sm text-slate-700">{meaning}</p><p className="mt-3 text-xs font-bold text-emerald-800">Used in: {use}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Verify the Hand Calculation with Automatic Differentiation</h2><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">one_weight_gradient.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`import torch

x = torch.tensor(2.0)
y = torch.tensor(4.0)
w = torch.tensor(1.5, requires_grad=True)

prediction = w * x
loss = (prediction - y) ** 2
loss.backward()

print(prediction.item())  # 3.0
print(loss.item())        # 1.0
print(w.grad.item())      # -4.0

with torch.no_grad():
    w -= 0.1 * w.grad
print(w.item())           # about 1.9`}</pre></div><p className="mt-4 text-sm leading-relaxed text-slate-600">Automatic differentiation calculates the same chain rule from recorded operations. It saves bookkeeping; it does not remove the need to check shapes, loss definitions and gradient values.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Common Mathematical Mistakes in Neural-Network Code</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[980px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Symptom</th><th className="p-3 text-left">Mathematical cause</th><th className="p-3 text-left">Check</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Matrix multiplication error","Inner dimensions do not match","Write every intermediate shape before coding"],["Code runs but result has unexpected shape","Broadcasting aligned an unintended axis","Inspect operands and result; add dimensions explicitly"],["Loss becomes NaN/∞","Overflow, division/log near zero or exploding values","Check min/max/finite values and use stable library losses"],["No learning","Disconnected graph, zero/saturated derivatives or wrong sign","Inspect gradients and test one manual derivative"],["Update makes loss larger","Step too large or batch gradient differs","Reduce learning rate and test a controlled tiny case"],["High confidence is unreliable","Probabilities are not calibrated","Measure calibration on held-out representative data"]].map(([symptom,cause,check])=><tr key={symptom}><td className="p-3 font-bold text-slate-900">{symptom}</td><td className="p-3 text-rose-800">{cause}</td><td className="p-3 text-indigo-800">{check}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What to Carry into the Next Lessons</h2><div className="not-prose rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><p className="font-bold text-emerald-950">Read every neural-network formula as a story about quantities and shapes.</p><ul className="mt-3 space-y-2 pl-5 text-sm leading-relaxed text-emerald-950"><li>Vectors and matrices organize examples, features and weights.</li><li>A dot product is a weighted sum; layers perform many of them together.</li><li>Functions compose the prediction, and loss turns quality into a number.</li><li>Derivatives describe local sensitivity; the gradient gathers it for all parameters.</li><li>The chain rule carries responsibility backward; the optimizer uses it to update weights.</li><li>Probability describes uncertainty, while logs make probability-based losses practical.</li></ul></div></section>

    <section><h2 className="mb-4 border-b pb-2 text-2xl font-bold text-indigo-800">Continue Learning</h2><div className="not-prose mb-10 grid gap-4 md:grid-cols-2"><a href="/learn/neural-networks" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Previous concept</p><p className="m-0 font-bold text-slate-900">How Neural Networks Learn</p></a><a href="/learn/activation-functions" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Next concept</p><p className="m-0 font-bold text-slate-900">Activation Functions</p></a></div></section>
  </div>;
}
