import React from "react";

function ArtifactFigure() {
  const pieces = [
    ["Architecture", "layers, shapes, forward logic", "#dbeafe", "#2563eb"],
    ["Learned state", "weights + buffers", "#ede9fe", "#7c3aed"],
    ["Preprocessing", "resize, normalize, tokenizer", "#cffafe", "#0891b2"],
    ["Output contract", "class order, thresholds, units", "#dcfce7", "#16a34a"],
    ["Metadata", "versions, metrics, intended use", "#fef3c7", "#d97706"],
  ];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">A deployable model is a versioned bundle—not one weight file</p></div><div className="overflow-x-auto p-5 md:p-6"><div className="flex min-w-[980px] items-stretch gap-3">{pieces.map(([title,detail,bg,border],i)=><React.Fragment key={title}><div className="flex-1 rounded-xl border-2 p-4 text-center" style={{backgroundColor:bg,borderColor:border}}><p className="text-sm font-extrabold text-slate-900">{title}</p><p className="mt-3 text-xs leading-relaxed text-slate-600">{detail}</p></div>{i<pieces.length-1&&<span className="flex items-center text-xl font-black text-slate-400">+</span>}</React.Fragment>)}<span className="flex items-center text-3xl font-black text-indigo-500">→</span><div className="flex items-center rounded-xl bg-slate-900 p-5 text-center font-bold text-white">reproducible<br />prediction</div></div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">If the class order changes from [normal, crack] to [crack, normal], identical logits receive opposite meanings. Version every piece that changes the input or interpretation.</figcaption></figure>;
}

function LifecycleFigure() {
  const steps = [["1","Validate","quality + slices"],["2","Package","model contract"],["3","Equivalence","old vs exported"],["4","Load test","p50/p95 + throughput"],["5","Canary","small live traffic"],["6","Monitor","drift + outcomes"],["7","Rollback","known-good version"]];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">Deployment is a controlled path from offline model to monitored service</p></div><div className="overflow-x-auto p-5 md:p-6"><div className="flex min-w-[1050px] items-stretch gap-2">{steps.map(([n,title,note],i)=><React.Fragment key={n}><div className="flex-1 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-center"><span className="mx-auto flex h-8 w-8 items-center justify-center rounded-full bg-indigo-700 text-sm font-black text-white">{n}</span><p className="mt-3 text-sm font-bold text-indigo-950">{title}</p><p className="mt-1 text-xs text-slate-600">{note}</p></div>{i<steps.length-1&&<span className="flex items-center text-xl font-black text-slate-400">→</span>}</React.Fragment>)}</div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">Rollback is designed before release, not invented after failure. Keep the previous artifact and routing/configuration needed to restore it.</figcaption></figure>;
}

function RequestFlowFigure() {
  const stages = [["Request","image bytes"],["Validate","type + size"],["Preprocess","tensor [1,3,H,W]"],["Model","logits"],["Postprocess","softmax + threshold"],["Response","label + version"]];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">An inference API makes every transformation explicit</p><div className="mt-5 overflow-x-auto"><div className="flex min-w-[900px] items-stretch gap-3">{stages.map(([title,detail],i)=><React.Fragment key={title}><div className="flex-1 rounded-xl border border-slate-200 bg-slate-50 p-4 text-center"><p className="font-bold text-slate-900">{title}</p><p className="mt-2 font-mono text-xs text-slate-600">{detail}</p></div>{i<stages.length-1&&<span className="flex items-center text-2xl font-black text-emerald-500">→</span>}</React.Fragment>)}</div></div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">Validation protects reliability and security. Postprocessing is part of the prediction contract: softmax axis, thresholds and class mapping must match evaluation.</figcaption></figure>;
}

function MonitoringFigure() {
  const signals = [["Service","latency, errors, saturation","Is the system available?"],["Inputs","shape, ranges, missingness, drift","Is traffic still familiar?"],["Outputs","class mix, confidence, abstentions","Has model behavior shifted?"],["Outcomes","delayed labels, false alarms, business cost","Is it still useful and safe?"]];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">Monitoring needs four layers of evidence</p><div className="mt-5 grid gap-4 md:grid-cols-2">{signals.map(([name,signals,question],i)=><div key={name} className="rounded-xl border p-5" style={{borderColor:["#2563eb","#7c3aed","#d97706","#16a34a"][i],backgroundColor:["#eff6ff","#f5f3ff","#fffbeb","#f0fdf4"][i]}}><p className="font-bold text-slate-950">{name}</p><p className="mt-2 text-sm text-slate-700">{signals}</p><p className="mt-3 text-xs font-bold text-slate-600">{question}</p></div>)}</div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">Input drift is a warning, not proof of quality loss. Outcome labels are stronger evidence but may arrive late. Design monitoring and privacy controls together.</figcaption></figure>;
}

const formatRows = [
  ["Framework state dictionary", "Training resume and native-framework inference", "Flexible and easy to inspect", "Requires model code and compatible framework"],
  ["Framework export", "Stable graph/artifact within the framework ecosystem", "Can capture executable computation", "Dynamic control flow and operator support need testing"],
  ["ONNX", "Cross-platform/runtime inference", "Multiple languages and hardware providers", "Export support and numerical parity vary by operator"],
  ["Device-specific runtime", "Mobile, browser or accelerator deployment", "Potential size/latency/energy gains", "Conversion, quantization and device QA add work"],
  ["Remote model service", "Centralized model behind an API", "Simple clients; controlled updates", "Network latency, privacy, availability and cost"],
] as const;

export function ModelDeploymentContent() {
  return <div className="prose prose-lg max-w-none text-slate-700">
    <section className="not-prose mb-10 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-emerald-800 px-6 py-10 text-white shadow-xl md:px-10 md:py-12"><p className="mb-3 text-sm font-extrabold uppercase tracking-[0.18em] text-emerald-200">Deep Learning · Production</p><h2 className="max-w-4xl text-3xl font-black leading-tight md:text-5xl">Saving, Loading and Deploying Deep Models</h2><p className="mt-5 max-w-4xl text-lg leading-relaxed text-indigo-50 md:text-xl">Training produces useful parameters; deployment turns them into a repeatable decision inside a real system. We will distinguish training checkpoints from inference artifacts, save and load PyTorch state safely, prove predictions survive reload/export, define an API contract, calculate latency and model size trade-offs, plan canary rollout and rollback, and monitor both service health and delayed model quality.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Weight File Is Not the Complete Model</h2><p className="text-lg leading-relaxed">Imagine a crack detector whose file loads without error but receives RGB channels in the wrong order. The learned weights are intact, yet predictions are wrong. Or imagine logits [2.1,0.4] evaluated as [normal, crack] but served with reversed labels. Serialization succeeded; deployment failed.</p><p className="text-lg leading-relaxed">A reliable artifact records the model architecture/configuration, learned parameters and buffers, exact preprocessing/tokenizer, output interpretation, relevant dependency versions and validated metrics. Give the bundle an immutable version or content hash.</p><ArtifactFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Checkpoint and Inference Artifact Serve Different Purposes</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Contents</th><th className="p-3 text-left">Resume-training checkpoint</th><th className="p-3 text-left">Inference artifact</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Model parameters and buffers","Required","Required"],["Architecture/configuration","Required to rebuild","Required or captured by export"],["Optimizer state","Required for faithful resume","Not needed"],["Scheduler/scaler state","Required if used","Not needed"],["Epoch/step and random state","Useful/required for reproducibility","Build metadata only"],["Pre/postprocessing + labels","Strongly recommended","Required"],["Validation decision/metrics","Required provenance","Required provenance"]].map(([item,train,infer])=><tr key={item}><td className="p-3 font-bold text-slate-900">{item}</td><td className="p-3 text-blue-800">{train}</td><td className="p-3 text-emerald-800">{infer}</td></tr>)}</tbody></table></div><p className="mt-5 text-lg leading-relaxed">Optimizer state includes momentum/adaptive statistics. Loading only model weights can resume from similar predictions but not from the same training dynamics.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Save State Dictionaries and Rebuild Deliberately</h2><p className="text-lg leading-relaxed">In PyTorch, a state dictionary maps names to tensors for parameters and persistent buffers. Saving it decouples learned state from Python object layout better than pickling an entire model, but the architecture code/configuration is still needed to load it.</p><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">save_and_load_for_inference.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`import json
import torch

# Save learned state and a separate, human-readable contract.
torch.save(model.state_dict(), "crack_detector_v7.pt")
with open("crack_detector_v7.json", "w", encoding="utf-8") as file:
    json.dump({
        "architecture": "SmallCNN-v3",
        "classes": ["normal", "crack"],
        "input_shape": [3, 224, 224],
        "normalization": {"mean": mean, "std": std},
        "decision_threshold": 0.72,
    }, file, indent=2)

# Recreate the exact architecture, then load tensors strictly.
loaded = SmallCNN(num_classes=2)
state = torch.load(
    "crack_detector_v7.pt",
    map_location="cpu",
    weights_only=True,
)
loaded.load_state_dict(state, strict=True)
loaded.eval()  # disables dropout; BatchNorm uses stored statistics

with torch.inference_mode():
    logits = loaded(preprocessed_batch)
    probabilities = logits.softmax(dim=1)`}</pre></div><div className="not-prose mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold text-blue-950">Which values come from the system?</p><p className="mt-2 text-sm leading-relaxed text-blue-900">Two classes and their order come from the labelled task. Shape [3,224,224] comes from the model contract: RGB channels and chosen spatial size. Mean/std come from validated preprocessing. Threshold 0.72 is a developer-selected operating point from validation trade-offs—not a weight learned automatically.</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold text-emerald-950">What loading and inference do</p><p className="mt-2 text-sm leading-relaxed text-emerald-900"><code>strict=True</code> rejects missing or unexpected state names. <code>map_location</code> selects the loading device. <code>eval()</code> changes dropout and BatchNorm behavior; <code>inference_mode</code> avoids gradient storage. The model produces logits and softmax normalizes across the two class positions.</p></div></div><div className="not-prose mt-5 rounded-xl border-l-4 border-rose-500 bg-rose-50 p-5"><p className="font-bold text-rose-950">Serialized models are input files, so trust matters</p><p className="mt-2 text-sm leading-relaxed text-rose-900">Do not load arbitrary untrusted checkpoints. Use safer weight-only loading where supported, verify artifact provenance/checksums, restrict access, scan dependencies and test in an isolated environment.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Prove That Saving and Export Did Not Change Predictions</h2><p className="text-lg leading-relaxed">A successful file write or export only proves that an artifact exists. Build a small golden set containing normal, boundary and awkward inputs; store expected preprocessing outputs and model outputs within tolerances.</p><div className="not-prose rounded-2xl border border-indigo-200 bg-indigo-50 p-5 md:p-6"><h3 className="text-xl font-bold text-indigo-950">Numerical equivalence example</h3><p className="mt-2 text-slate-700">Use illustrative outputs from the same input: native logits [2.0000,0.5000] and exported-runtime logits [1.9998,0.5001]. In a real test both vectors are measured, while tolerance 0.001 is chosen in advance from acceptable numerical and decision risk.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><p className="rounded-lg bg-white p-4 font-mono text-sm"><strong>Subtract pairwise</strong><br />|2.0000−1.9998|=0.0002<br />|0.5000−0.5001|=0.0001</p><p className="rounded-lg bg-white p-4 font-mono text-sm"><strong>Take worst case</strong><br />max(0.0002,0.0001)<br />=<strong>0.0002</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm"><strong>Compare with rule</strong><br />0.0002≤0.001<br /><strong>pass</strong></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> this input passes the chosen numerical tolerance and keeps the same predicted class. Repeat across representative shapes/batches and evaluate end metrics; one vector is not sufficient validation.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Choose a Runtime for the Target Environment</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Artifact/runtime path</th><th className="p-3 text-left">Best fit</th><th className="p-3 text-left">Advantage</th><th className="p-3 text-left">Trade-off to test</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{formatRows.map(([format,fit,advantage,tradeoff])=><tr key={format} className="align-top"><td className="p-3 font-bold text-indigo-800">{format}</td><td className="p-3">{fit}</td><td className="p-3 text-emerald-800">{advantage}</td><td className="p-3 text-rose-800">{tradeoff}</td></tr>)}</tbody></table></div><p className="mt-5 text-lg leading-relaxed">ONNX is an interchange format, not proof of speed or correctness. Export with representative inputs, validate model conformance, compare outputs with the source framework and benchmark on the exact device and execution provider.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">From Validated Artifact to Live Traffic</h2><LifecycleFigure /><RequestFlowFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Small Inference Endpoint</h2><p className="text-lg leading-relaxed">Load the model once when the service starts, not on every request. Validate input before decoding it, use the same transform as evaluation, run inference without gradient recording, and return the model version so a prediction can be traced.</p><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">fastapi_inference_outline.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`from fastapi import FastAPI, HTTPException, UploadFile
import torch

app = FastAPI()
MODEL_VERSION = "crack-detector-v7"
contract = load_validated_contract("crack_detector_v7.json")
CLASSES = contract["classes"]             # saved order: ["normal", "crack"]
DECISION_THRESHOLD = float(contract["decision_threshold"])
NORMAL_CLASS_ID = CLASSES.index("normal")
CRACK_CLASS_ID = CLASSES.index("crack")
model = load_validated_model().eval()  # once at process startup

@app.post("/predict")
async def predict(file: UploadFile):
    raw = await file.read()
    if len(raw) > 5_000_000:
        raise HTTPException(413, "image is too large")

    image = decode_and_validate_rgb_image(raw)
    batch = preprocess(image).unsqueeze(0)

    with torch.inference_mode():
        probabilities = model(batch).softmax(dim=1)[0]

    crack_probability = float(probabilities[CRACK_CLASS_ID])
    class_id = (
        CRACK_CLASS_ID
        if crack_probability >= DECISION_THRESHOLD
        else NORMAL_CLASS_ID
    )
    return {
        "model_version": MODEL_VERSION,
        "label": CLASSES[class_id],
        "confidence": float(probabilities[class_id]),
    }`}</pre></div><div className="not-prose mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold text-blue-950">Trace one request through the endpoint</p><p className="mt-2 text-sm leading-relaxed text-blue-900">Five million bytes is an explicitly chosen abuse/resource limit. Decoding checks that bytes form a valid RGB image; preprocessing applies the saved contract; <code>unsqueeze(0)</code> creates a batch dimension of 1. The saved class order fixes the normal and crack indices. Softmax produces a crack probability, and the saved validation threshold <strong>0.72</strong> selects crack only when that probability reaches the operating point; otherwise the response is normal. Confidence is the probability of the selected class, and the immutable version links the response to its artifact.</p></div><p className="mt-4 text-sm leading-relaxed text-slate-600">A production API also needs authentication/authorization, bounded concurrency, timeouts, health/readiness checks, structured error handling, privacy-safe logging and abuse/resource controls.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Latency, Throughput and Batching Measure Different Things</h2><p className="text-lg leading-relaxed"><strong>Latency</strong> is measured time for one request, often reported at p50 and p95/p99. <strong>Throughput</strong> is calculated completed items per second. Batching can improve device utilization and throughput while making an individual request wait for a batch.</p><div className="not-prose rounded-2xl border border-emerald-200 bg-emerald-50 p-5 md:p-6"><h3 className="text-xl font-bold text-emerald-950">Eight images: individual versus batch</h3><p className="mt-2 text-sm text-slate-700">Assume illustrative benchmark measurements of 20 ms for one image and 45 ms for one batch of eight. Real values must come from load tests on the target device.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>One at a time</strong><br />20 ms × 8 = 160 ms total<br />throughput ≈ 8/0.160<br />=<strong>50 images/s</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>One batch of eight</strong><br />45 ms total<br />throughput ≈ 8/0.045<br />≈<strong>178 images/s</strong></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> divide completed items by elapsed seconds: the example batch gives about 3.6× throughput, but its requests take at least 45 ms plus queue time. Choose batch windows from the service-level latency target, not maximum throughput alone.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Compression Trades Size and Speed Against Quality</h2><p className="text-lg leading-relaxed">Quantization stores or computes with lower-precision values; pruning removes selected parameters/structures; distillation trains a smaller student from a larger teacher. Hardware and runtime determine whether theoretical reductions become real latency gains.</p><div className="not-prose rounded-xl border border-violet-200 bg-violet-50 p-5"><p className="font-bold text-violet-950">Weight-memory estimate</p><p className="mt-2 font-mono text-sm leading-7 text-violet-950">100 million FP32 weights × 4 bytes ≈ <strong>400 MB</strong><br />100 million INT8 weights × 1 byte ≈ <strong>100 MB</strong></p><p className="mt-3 text-sm leading-relaxed text-violet-900">That is roughly 4× less raw weight storage. Actual artifact/runtime memory also includes metadata, activations, workspace, scales/zero-points and framework overhead. Re-evaluate accuracy and latency after conversion.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Roll Out So Failure Is Contained</h2><div className="not-prose grid gap-4 md:grid-cols-3">{[["Shadow","New model receives copied traffic but does not control outcomes. Compare safely, while protecting logged data."],["Canary","Route a small controlled traffic share to the new version. Watch guardrail and quality proxies."],["Rollback","Automatically or manually route back to a known-good version when defined thresholds fail."]].map(([title,body])=><div key={title} className="rounded-xl border border-indigo-200 bg-indigo-50 p-5"><p className="font-bold text-indigo-950">{title}</p><p className="mt-2 text-sm leading-relaxed text-indigo-900">{body}</p></div>)}</div><p className="mt-5 text-lg leading-relaxed">For high-impact decisions, define abstention and human-review paths. A model should not be forced to decide when inputs are invalid, out of scope or confidence/calibration rules require escalation.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Monitor the System After Launch</h2><MonitoringFigure /><p className="text-lg leading-relaxed">Set alerts from expected ranges and operational costs, not arbitrary dashboards. Version dashboards by model and data pipeline; otherwise a stable average can hide one faulty version, region, device or subgroup.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Common Deployment Failures</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[1030px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Symptom</th><th className="p-3 text-left">Likely cause</th><th className="p-3 text-left">Diagnostic</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Same input gives changing predictions","Model left in training mode; dropout/BatchNorm behavior","Call eval(), use inference mode and repeat identical request"],["Offline good, service bad","Preprocessing or label mapping mismatch","Compare tensors/logits at every boundary on golden examples"],["Load reports missing/unexpected keys","Architecture/version differs from checkpoint","Use strict loading; compare config and parameter names; do not hide with strict=False"],["First requests are very slow","Lazy initialization, compilation or cold model download","Load and warm up before readiness; include cold-start tests"],["Median fine, users time out","High tail latency or queue saturation","Measure p95/p99 under realistic concurrency and payloads"],["GPU out of memory under load","Too many workers/batches or unbounded inputs","Bound size/concurrency, profile peak memory and capacity-test"],["Output mix shifts after a release","Version/preprocessing change or input drift","Segment metrics by model version and input source; canary/rollback"],["No one can reproduce a prediction","Missing artifact, code, data-contract or feature version","Log safe trace IDs and immutable version metadata"]].map(([symptom,cause,diagnostic])=><tr key={symptom} className="align-top"><td className="p-3 font-bold text-slate-900">{symptom}</td><td className="p-3 text-rose-800">{cause}</td><td className="p-3 text-indigo-800">{diagnostic}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Deployment Contract</h2><div className="not-prose rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><ul className="m-0 space-y-2 pl-5 text-emerald-950"><li>Save the model state plus the exact architecture, preprocessing, labels, thresholds and provenance.</li><li>Use evaluation mode and gradient-free inference; load only trusted, verified artifacts.</li><li>Compare source and loaded/exported predictions on a representative golden set.</li><li>Choose runtime and compression by measured target-device accuracy, memory and latency.</li><li>Validate every request and return/record the model version that produced the result.</li><li>Load-test throughput and p95/p99 latency, then release by shadow/canary with rollback ready.</li><li>Monitor service, inputs, outputs and delayed outcomes while protecting privacy.</li></ul></div></section>

    <section><h2 className="mb-4 border-b pb-2 text-2xl font-bold text-indigo-800">Continue Learning</h2><div className="not-prose mb-10"><a href="/learn/graph-neural-networks" className="block rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Previous concept</p><p className="m-0 font-bold text-slate-900">Graph Neural Networks</p></a></div></section>
  </div>;
}
