import React from "react";

function FamilyMapFigure() {
  const items = [
    ["Physics-Informed NN", "put governing equations into the loss", "known physics + sparse observations", "#dbeafe", "#2563eb"],
    ["Kolmogorov–Arnold Network", "learn a function on each connection", "function fitting/scientific exploration", "#ede9fe", "#7c3aed"],
    ["Topological Network", "learn on higher-order relationships", "edges, triangles, cells or hyperedges", "#dcfce7", "#16a34a"],
  ];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">Three advanced families answer three different questions</p><div className="mt-5 grid gap-4 md:grid-cols-3">{items.map(([name,idea,data,bg,border])=><div key={name} className="rounded-xl border-2 p-5" style={{backgroundColor:bg,borderColor:border}}><p className="font-bold text-slate-950">{name}</p><p className="mt-3 text-sm leading-relaxed text-slate-700">{idea}</p><p className="mt-4 rounded-lg bg-white p-3 text-xs font-bold text-slate-600">Best clue: {data}</p></div>)}</div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">They are grouped here as research-oriented architectures, not because one evolves into the next. Compare each with a strong conventional baseline.</figcaption></figure>;
}

function PINNFigure() {
  const points = [{x:95,y:245},{x:175,y:194},{x:255,y:157},{x:335,y:132},{x:415,y:112},{x:495,y:97},{x:575,y:87},{x:655,y:80}];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">A PINN is trained at observations, boundaries and physics collocation points</p></div><div className="overflow-x-auto p-4 md:p-6"><svg viewBox="0 0 780 340" className="h-auto min-w-[700px] w-full" role="img" aria-labelledby="pinn-title pinn-desc"><title id="pinn-title">PINN curve with boundary and collocation points</title><desc id="pinn-desc">A neural network approximates a decaying curve. One boundary point enforces u zero equals one, sparse observations constrain the curve, and collocation points evaluate the differential equation residual.</desc><rect width="780" height="340" rx="18" fill="#f8fafc" /><line x1="65" y1="280" x2="725" y2="280" stroke="#475569" strokeWidth="2" /><line x1="65" y1="280" x2="65" y2="45" stroke="#475569" strokeWidth="2" /><text x="730" y="300" fontSize="13" fontWeight="800" fill="#334155">time t</text><text x="35" y="50" fontSize="13" fontWeight="800" fill="#334155">u(t)</text><path d="M75 70 C170 120 250 170 350 205 C470 247 590 262 705 270" fill="none" stroke="#4f46e5" strokeWidth="5" /><circle cx="75" cy="70" r="10" fill="#16a34a" stroke="#166534" strokeWidth="2" /><text x="92" y="62" fontSize="12" fontWeight="800" fill="#166534">boundary u(0)=1</text>{points.map((p,i)=><g key={i}><line x1={p.x} y1={p.y} x2={p.x} y2="280" stroke="#f59e0b" strokeDasharray="4 4" /><circle cx={p.x} cy={p.y} r="7" fill="#fef3c7" stroke="#d97706" strokeWidth="2" /></g>)}{[[245,174],[520,252]].map(([x,y],i)=><g key={i}><rect x={x-8} y={y-8} width="16" height="16" fill="#fecdd3" stroke="#e11d48" strokeWidth="2" /><text x={x+12} y={y-10} fontSize="11" fontWeight="800" fill="#be123c">observed</text></g>)}<rect x="445" y="20" width="275" height="78" rx="14" fill="#fff" stroke="#cbd5e1" /><text x="582" y="45" textAnchor="middle" fontSize="12" fontWeight="800" fill="#0f172a">At every gold collocation point</text><text x="582" y="68" textAnchor="middle" fontSize="13" fontWeight="800" fill="#4f46e5">autodiff computes duθ/dt</text><text x="582" y="88" textAnchor="middle" fontSize="12" fill="#475569">residual r(t)=duθ/dt+uθ(t)</text></svg></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">Collocation points do not require measured targets. They are coordinates where the model&apos;s derivatives are inserted into the governing equation; nonzero residual becomes loss.</figcaption></figure>;
}

function KANFigure() {
  const edges = [["x₁","φ₁₁","y₁"],["x₂","φ₁₂","y₁"],["x₁","φ₂₁","y₂"],["x₂","φ₂₂","y₂"]];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">In a KAN, each connection applies a learned one-dimensional function</p></div><div className="overflow-x-auto p-5 md:p-6"><div className="flex min-w-[760px] items-center gap-8"><div className="space-y-10">{["x₁","x₂"].map(x=><div key={x} className="rounded-full bg-blue-100 p-5 font-mono font-black text-blue-950">{x}</div>)}</div><div className="grid flex-1 grid-cols-2 gap-4">{edges.map(([from,fn,to])=><div key={`${from}-${fn}-${to}`} className="rounded-xl border border-violet-200 bg-violet-50 p-4 text-center"><p className="text-xs text-slate-500">{from} → {to}</p><svg viewBox="0 0 140 60" className="mt-2 h-14 w-full" aria-hidden="true"><path d="M5 48 C30 45 45 12 70 30 C95 48 110 10 135 14" fill="none" stroke="#7c3aed" strokeWidth="4" /></svg><p className="font-mono text-sm font-bold text-violet-900">{fn}({from})</p></div>)}</div><div className="space-y-10">{["y₁=Σφ₁ᵢ","y₂=Σφ₂ᵢ"].map(y=><div key={y} className="rounded-full bg-emerald-100 p-5 font-mono font-black text-emerald-950">{y}</div>)}</div></div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">The curves are illustrative. Practical KAN implementations parameterize edge functions with splines or other bases and learn their coefficients. A node sums incoming transformed values.</figcaption></figure>;
}

function TopologyFigure() {
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">A graph triangle and a filled triangle do not encode the same relation</p><div className="mt-5 grid gap-6 md:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50 p-5"><p className="text-center text-xs font-bold uppercase text-blue-700">pairwise graph</p><svg viewBox="0 0 260 190" className="mx-auto h-48 w-full" role="img" aria-label="Hollow triangle graph"><path d="M130 28 L45 150 L215 150 Z" fill="none" stroke="#2563eb" strokeWidth="6" />{[[130,28,"A"],[45,150,"B"],[215,150,"C"]].map(([x,y,t])=><g key={String(t)}><circle cx={Number(x)} cy={Number(y)} r="23" fill="#fff" stroke="#1d4ed8" strokeWidth="3" /><text x={Number(x)} y={Number(y)+6} textAnchor="middle" fontSize="18" fontWeight="900" fill="#1e3a8a">{t}</text></g>)}</svg><p className="text-center font-mono text-sm font-bold text-blue-950">V=3, E=3, F=0<br />χ=V−E+F=0</p><p className="mt-2 text-center text-xs text-blue-900">three pairwise relationships; central hole</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-center text-xs font-bold uppercase text-emerald-700">2-simplex / filled face</p><svg viewBox="0 0 260 190" className="mx-auto h-48 w-full" role="img" aria-label="Filled triangle simplicial complex"><path d="M130 28 L45 150 L215 150 Z" fill="#86efac" stroke="#16a34a" strokeWidth="6" />{[[130,28,"A"],[45,150,"B"],[215,150,"C"]].map(([x,y,t])=><g key={String(t)}><circle cx={Number(x)} cy={Number(y)} r="23" fill="#fff" stroke="#15803d" strokeWidth="3" /><text x={Number(x)} y={Number(y)+6} textAnchor="middle" fontSize="18" fontWeight="900" fill="#14532d">{t}</text></g>)}</svg><p className="text-center font-mono text-sm font-bold text-emerald-950">V=3, E=3, F=1<br />χ=V−E+F=1</p><p className="mt-2 text-center text-xs text-emerald-900">one explicit three-way relation; no central hole</p></div></div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">Both have the same three nodes and edges, but the right structure says the triple itself forms a 2-dimensional cell. The Euler characteristic χ is a simple topological summary; full topological learning uses richer incidence and message-passing operators.</figcaption></figure>;
}

const choiceRows = [
  ["Known ODE/PDE; sparse measurements", "PINN or another physics-informed method", "Equation residual supplies supervision between observations", "Compare numerical solvers and hybrid/surrogate methods"],
  ["Small scientific function-fitting problem", "KAN and MLP baselines", "Edge functions may provide inspectable fitted curves", "Do not infer universal superiority from toy results"],
  ["Pairwise entity relationships", "GNN", "Graph structure already matches the data", "Higher-order complex may add needless complexity"],
  ["Meaningful group/face/cell relationships", "Topological/hypergraph network", "Preserves interactions a pairwise graph can collapse", "Construction and tooling are less mature"],
] as const;

export function ScientificNetworksContent() {
  return <div className="prose prose-lg max-w-none text-slate-700">
    <section className="not-prose mb-10 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-cyan-950 to-violet-900 px-6 py-10 text-white shadow-xl md:px-10 md:py-12"><p className="mb-3 text-sm font-extrabold uppercase tracking-[0.18em] text-cyan-200">Deep Learning · Emerging Scientific Architectures</p><h2 className="max-w-5xl text-3xl font-black leading-tight md:text-5xl">Physics-Informed, Kolmogorov–Arnold and Topological Networks</h2><p className="mt-5 max-w-4xl text-lg leading-relaxed text-cyan-50 md:text-xl">These are three distinct ways to give a neural model more structure than a standard dense network: enforce known equations through a loss, learn flexible functions on connections, or represent higher-order relationships beyond pairwise edges. We will build each idea from a small calculation, identify where it may help, and keep the limitations visible because all three require careful comparison with mature baselines.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why These Methods Exist</h2><p className="text-lg leading-relaxed">A normal supervised network learns from input–target examples and an architecture&apos;s built-in assumptions. Scientific and relational problems often offer additional knowledge: a differential equation that every solution should approximately satisfy, a low-dimensional function whose shape scientists want to inspect, or a three-way interaction that cannot be distinguished from three independent pairwise edges.</p><p className="text-lg leading-relaxed">The methods in this lesson place that knowledge in different parts of the learning system. They are not drop-in upgrades for every neural network.</p><FamilyMapFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Physics-Informed Neural Networks Put Equations Into the Loss</h2><p className="text-lg leading-relaxed">Suppose u(t) describes a cooling quantity and should follow the ordinary differential equation du/dt+u=0 with initial condition u(0)=1. The equation and initial value come from scientific knowledge, while a Physics-Informed Neural Network represents the unknown solution with a differentiable neural function u<sub>θ</sub>(t). Automatic differentiation calculates du<sub>θ</sub>/dt from the network graph at chosen coordinates.</p><p className="text-lg leading-relaxed">The equation residual r(t)=du<sub>θ</sub>/dt+u<sub>θ</sub>(t) should be zero for a valid solution. The loss combines boundary/initial conditions, optional observations, and mean squared residual at <strong>collocation points</strong>—developer-sampled coordinates inside the domain that do not need target solution values.</p><PINNFigure /><div className="not-prose rounded-2xl bg-slate-950 p-5 text-white md:p-6"><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-cyan-300">A simple PINN objective</p><p className="mt-2 overflow-x-auto whitespace-nowrap font-mono text-lg font-bold">L = λ<sub>bc</sub>[u<sub>θ</sub>(0)−1]² + λ<sub>phys</sub>(1/N)Σ<sub>i</sub>r(t<sub>i</sub>)² + λ<sub>data</sub>L<sub>observed</sub></p><p className="mt-3 text-sm leading-relaxed text-slate-200">Subtracting known targets creates residuals, squaring prevents positive and negative violations from cancelling, averaging summarizes N collocation points, and adding combines all requirements into one optimizer target. The λ terms are developer-chosen weights for components with different scales—not physical constants or learned solution values.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Calculate One Physics Residual by Hand</h2><p className="text-lg leading-relaxed">To show the check without hiding it inside a network, manually choose the imperfect candidate u(t)=1−0.8t and collocation point t=0.5. The coefficient −0.8 and point 0.5 are teaching choices. In training, u comes from the current neural network and collocation points are sampled across the domain. This candidate satisfies the boundary at t=0, but its derivative is du/dt=−0.8.</p><div className="not-prose rounded-2xl border border-blue-200 bg-blue-50 p-5 md:p-6"><div className="grid gap-3 md:grid-cols-3"><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>1. Candidate value</strong><br />u(0.5)=1−0.8×0.5<br />=<strong>0.6</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>2. Equation residual</strong><br />r=du/dt+u<br />=−0.8+0.6=<strong>−0.2</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>3. Physics loss</strong><br />r²=(−0.2)²<br />=<strong>0.04</strong></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> the boundary term is zero but the physics term is not, so training receives a signal to change the function inside the domain. The exact solution e<sup>−t</sup> has derivative −e<sup>−t</sup>, making this residual zero everywhere.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Minimal PINN for the Cooling Equation</h2><p className="text-lg leading-relaxed">The code samples t values, asks PyTorch for du/dt, constructs the residual and combines it with the initial-condition loss. The optimizer adjusts network parameters—not the coordinates.</p><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">pinn_cooling_ode.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`import torch
from torch import nn

model = nn.Sequential(
    nn.Linear(1, 32), nn.Tanh(),
    nn.Linear(32, 32), nn.Tanh(),
    nn.Linear(32, 1),
)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

for step in range(5000):
    # Collocation coordinates need gradients so du/dt can be computed.
    t = torch.rand(128, 1, requires_grad=True)
    u = model(t)
    du_dt = torch.autograd.grad(
        u, t,
        grad_outputs=torch.ones_like(u),
        create_graph=True,
    )[0]

    residual = du_dt + u                 # target residual is zero
    physics_loss = (residual ** 2).mean()

    u_zero = model(torch.zeros(1, 1))
    boundary_loss = (u_zero - 1.0).pow(2).mean()
    loss = physics_loss + boundary_loss

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()`}</pre></div><div className="not-prose mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold text-blue-950">Where the values come from</p><p className="mt-2 text-sm leading-relaxed text-blue-900">One input and one output follow from t→u. Two hidden layers of width 32, 5,000 steps, batch 128 and learning rate 0.001 are chosen training hyperparameters. <code>rand</code> samples t in [0,1); zero and target 1.0 come from the initial condition u(0)=1.</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold text-emerald-950">Why create a derivative graph?</p><p className="mt-2 text-sm leading-relaxed text-emerald-900"><code>requires_grad=True</code> lets autograd differentiate u with respect to t. <code>create_graph=True</code> keeps that derivative differentiable so <code>loss.backward()</code> can determine how the physics residual depends on model weights. Coordinates receive temporary gradients; only parameters passed to Adam are updated.</p></div></div><p className="mt-4 text-sm leading-relaxed text-slate-600">After training, validate against an analytical solution when one exists or a trusted numerical solver—not only the training residual. Check error across the complete domain and conservation/units relevant to the real system.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">PINNs Are Optimization Methods, Not Automatic Solver Replacements</h2><div className="not-prose grid gap-4 md:grid-cols-2">{[["Forward problem","Known equation/parameters; approximate the state u across the domain."],["Inverse problem","Use observations plus physics to infer unknown parameters or fields."],["Potential advantage","Softly combine sparse/noisy data and differentiable governing knowledge."],["Common difficulty","Stiff, multiscale, chaotic or high-dimensional problems can be very hard to optimize."],["Loss imbalance","Boundary and residual terms may differ greatly in scale; one can improve while another is ignored."],["Baseline requirement","Compare accuracy, runtime and robustness with finite-difference/finite-element/spectral and hybrid methods."]].map(([title,body])=><div key={title} className="rounded-xl border border-blue-200 bg-blue-50 p-5"><p className="font-bold text-blue-950">{title}</p><p className="mt-2 text-sm leading-relaxed text-blue-900">{body}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">KANs Move Learnable Nonlinearity Onto Connections</h2><p className="text-lg leading-relaxed">A standard dense layer multiplies inputs by scalar weights, sums them, then applies a fixed activation such as ReLU at a node. A Kolmogorov–Arnold Network (KAN), inspired by the Kolmogorov–Arnold representation theorem, instead places a learnable one-variable function φ on each edge and sums incoming edge outputs at a node.</p><KANFigure /><div className="not-prose rounded-2xl bg-slate-950 p-5 text-white md:p-6"><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-cyan-300">One KAN-style layer</p><p className="mt-2 overflow-x-auto whitespace-nowrap font-mono text-xl font-bold">x<sub>l+1,j</sub> = Σ<sub>i=1</sub><sup>n<sub>l</sub></sup> φ<sub>l,j,i</sub>(x<sub>l,i</sub>)</p><p className="mt-3 text-sm leading-relaxed text-slate-200">x<sub>l,i</sub> is the i-th model-produced value entering layer l; n<sub>l</sub> is that layer&apos;s chosen width; φ<sub>l,j,i</sub> is a learned one-variable edge function. The sum is necessary to combine all incoming transformed values without inventing an ordering. Implementations choose a function basis, grid and parameterization as architecture hyperparameters.</p></div><div className="not-prose mt-5 rounded-2xl border border-violet-200 bg-violet-50 p-5"><p className="font-bold text-violet-950">A two-edge numerical example</p><p className="mt-2 text-slate-700">Manually choose two readable edge functions φ₁(x)=x² and φ₂(x)=2x, and teaching inputs x₁=2 and x₂=3. Real inputs come from data or the previous layer, while training learns the edge curves.</p><p className="mt-3 rounded-lg bg-white p-4 font-mono text-sm leading-7">φ₁(2)=2²=4<br />φ₂(3)=2×3=6<br />y=φ₁(x₁)+φ₂(x₂)=4+6=<strong>10</strong></p><p className="mt-3 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> each connection transforms its scalar input with its own curve, then the node adds the two results. This illustrates a KAN-style layer; it is not a fitted scientific law.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">When to Treat KANs as an Experiment</h2><p className="text-lg leading-relaxed">KAN edge curves can be inspected, simplified and visualized, which is attractive for low-dimensional scientific discovery. But “interpretable” is not automatic: many layers and edges can still produce a complex coupled system, and a fitted curve may reflect correlations or extrapolate poorly.</p><div className="not-prose rounded-xl border-l-4 border-amber-500 bg-amber-50 p-5"><p className="font-bold text-amber-950">Benchmark against an MLP under equal conditions</p><p className="mt-2 text-sm leading-relaxed text-amber-900">Match data splits, parameter/compute budget, tuning effort and seeds. Measure training/inference cost and out-of-range behavior. KAN tooling and hardware optimization are newer than standard dense layers, so a paper result does not guarantee an advantage on your task.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Topological Networks Go Beyond Pairwise Edges</h2><p className="text-lg leading-relaxed">A graph records pairwise relationships. Some systems have meaningful multi-way units: three atoms can form a face, multiple authors can participate in one collaboration, and flow may live on edges or surfaces rather than nodes. A <strong>simplicial complex</strong> can include vertices (0-simplices), edges (1-simplices), filled triangles (2-simplices) and higher-dimensional simplices, together with their faces.</p><TopologyFigure /><p className="text-lg leading-relaxed">Topological neural networks pass information between cells of the same or different ranks using incidence/neighborhood structure. Other domains include cell complexes, hypergraphs and combinatorial complexes. Choosing the domain is part of modelling: a filled triangle should mean a real three-way relation, not be added merely because three pairwise edges form a cycle.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Choose the Structure From Knowledge You Truly Have</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Evidence in the problem</th><th className="p-3 text-left">Reasonable model to test</th><th className="p-3 text-left">Why</th><th className="p-3 text-left">Required comparison</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{choiceRows.map(([evidence,model,why,compare])=><tr key={evidence} className="align-top"><td className="p-3 font-bold text-slate-900">{evidence}</td><td className="p-3 text-indigo-800">{model}</td><td className="p-3 text-emerald-800">{why}</td><td className="p-3 text-rose-800">{compare}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Diagnostics for Research-Oriented Models</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[1020px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Observation</th><th className="p-3 text-left">Possible cause</th><th className="p-3 text-left">Check</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["PINN residual low but boundary wrong","Loss imbalance or poor boundary sampling","Report every loss term and domain-wise error separately"],["PINN fits points but violates conservation","Equation/units/derivatives implemented incorrectly","Use manufactured solutions and dimensional/unit tests"],["KAN train fit is excellent; extrapolation unstable","Flexible splines unsupported outside training range","Plot each relevant edge function and test out-of-range inputs"],["KAN beats one untuned MLP","Unequal tuning or parameter/compute budget","Run matched baselines across seeds"],["Topological model adds no value","Higher-order cells are artificial or features dominate","Compare graph-only, topology-only and feature-only ablations"],["Result changes under harmless reindexing/orientation","Broken invariance/equivariance handling","Run permutation/orientation transformation tests"]].map(([obs,cause,check])=><tr key={obs} className="align-top"><td className="p-3 font-bold text-slate-900">{obs}</td><td className="p-3 text-rose-800">{cause}</td><td className="p-3 text-indigo-800">{check}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What to Remember</h2><div className="not-prose rounded-2xl border border-cyan-200 bg-cyan-50 p-6"><ul className="m-0 space-y-2 pl-5 text-cyan-950"><li>A PINN differentiates a neural approximation and penalizes equation residuals plus boundaries and observations.</li><li>Low residual is not enough; validate domain error, constraints and performance against trusted solvers.</li><li>A KAN sums learned one-dimensional edge functions instead of scalar-weighted inputs followed by fixed node activations.</li><li>KAN curves may aid inspection, but matched MLP benchmarks and extrapolation tests remain necessary.</li><li>Topological networks represent meaningful higher-order cells that pairwise graphs cannot distinguish.</li><li>These are specialized, evolving tools. Use them because the problem supplies matching structure—not because the names are new.</li></ul></div></section>

    <section><h2 className="mb-4 border-b pb-2 text-2xl font-bold text-indigo-800">Related Learning</h2><div className="not-prose mb-10 grid gap-4 md:grid-cols-2"><a href="/learn/deep-learning-intro" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Back to Deep Learning</p><p className="m-0 font-bold text-slate-900">Deep Learning Basics and Model Types</p></a><a href="/learn/state-space-models" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Related Advanced Topic</p><p className="m-0 font-bold text-slate-900">State-Space Models</p></a></div></section>
  </div>;
}
