import React from "react";

function TensorProgressionFigure() {
  const stages = [
    ["Scalar", "7", "one number", "loss = 7"],
    ["Vector", "[2, 5, 8]", "one axis", "3 features"],
    ["Matrix", "[[1,2],[3,4]]", "rows × columns", "2 examples × 2 features"],
    ["3-D tensor", "3 × 4 × 4", "channels × height × width", "one small RGB image"],
    ["Batch tensor", "8 × 3 × 4 × 4", "examples × channels × height × width", "8 small RGB images"],
  ];
  return (
    <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">A tensor grows by adding named axes</p></div>
      <div className="overflow-x-auto p-5 md:p-6"><div className="flex min-w-[1040px] items-stretch gap-3">{stages.map(([name, value, axes, example], index) => <React.Fragment key={name}><div className="w-44 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-center"><p className="text-xs font-extrabold uppercase text-indigo-700">{name}</p><p className="mt-3 break-words font-mono font-black text-indigo-950">{value}</p><p className="mt-3 text-xs font-bold text-slate-700">{axes}</p><p className="mt-2 text-xs text-slate-500">{example}</p></div>{index < stages.length - 1 && <span className="flex items-center text-2xl font-black text-slate-400">→</span>}</React.Fragment>)}</div></div>
      <figcaption className="border-t border-slate-100 px-5 py-3 text-sm text-slate-600">“Dimension” or “axis” means one direction in the array. “Rank” means how many axes exist. “Shape” lists the length of each axis.</figcaption>
    </figure>
  );
}

function RGBPixelFigure() {
  return (
    <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6">
      <p className="font-bold text-slate-900">One colour pixel stores three channel values</p>
      <div className="mt-5 grid gap-4 sm:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1.2fr] sm:items-center">
        <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-center"><p className="font-bold text-red-800">Red</p><p className="mt-2 font-mono text-xl">R = 240</p></div><span className="hidden text-2xl font-black text-slate-400 sm:block">+</span>
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-center"><p className="font-bold text-emerald-800">Green</p><p className="mt-2 font-mono text-xl">G = 120</p></div><span className="hidden text-2xl font-black text-slate-400 sm:block">+</span>
        <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-center"><p className="font-bold text-blue-800">Blue</p><p className="mt-2 font-mono text-xl">B = 30</p></div><span className="hidden text-2xl font-black text-slate-400 sm:block">→</span>
        <div className="rounded-xl bg-slate-900 p-4 text-center text-white"><p className="text-xs font-bold uppercase text-slate-300">pixel vector</p><p className="mt-2 font-mono text-xl font-black">[240,120,30]</p></div>
      </div>
      <figcaption className="mt-4 text-sm leading-relaxed text-slate-600">The numbers are manually chosen 8-bit teaching values from 0 to 255. They describe colour intensity; they are not class labels or learned weights.</figcaption>
    </figure>
  );
}

function TensorShapeFigure() {
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">An image batch is one tensor with four named axes</p></div><div className="overflow-x-auto p-5 md:p-7"><div className="min-w-[900px]"><div className="grid grid-cols-[160px_1fr] items-center gap-6"><div className="rounded-2xl border-2 border-indigo-400 bg-indigo-50 p-5 text-center"><p className="font-mono text-2xl font-black text-indigo-950">[32, 3, 64, 64]</p><p className="mt-2 text-sm text-indigo-800">shape, in NCHW order</p></div><div className="grid grid-cols-4 gap-3">{[["N = 32","batch","32 photographs","#dbeafe","#2563eb"],["C = 3","channels","red, green, blue","#ede9fe","#7c3aed"],["H = 64","height","64 pixel rows","#fef3c7","#d97706"],["W = 64","width","64 pixel columns","#dcfce7","#16a34a"]].map(([v,name,detail,bg,border])=><div key={name} className="rounded-xl border-2 p-4 text-center" style={{backgroundColor:bg,borderColor:border}}><p className="font-mono font-black text-slate-950">{v}</p><p className="mt-2 text-sm font-bold text-slate-800">{name}</p><p className="mt-2 text-xs text-slate-600">{detail}</p></div>)}</div></div><div className="mt-6 rounded-xl bg-slate-900 p-4 text-center font-mono text-sm text-white">32 × 3 × 64 × 64 = <strong className="text-emerald-300">393,216 stored values</strong></div></div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">A dimension&apos;s position changes its meaning. Some libraries or data pipelines use NHWC instead; confirm the convention expected by every layer.</figcaption></figure>;
}

function GPUFlowFigure() {
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">The operation can only run where all required tensors live</p></div><div className="overflow-x-auto p-5 md:p-7"><div className="grid min-w-[900px] grid-cols-[250px_90px_1fr] items-center gap-5"><div className="rounded-2xl border border-slate-300 bg-slate-50 p-5 text-center"><p className="text-3xl">🧠</p><p className="mt-2 font-bold text-slate-950">CPU memory</p><p className="mt-3 rounded-lg bg-white p-3 font-mono text-xs">batch from data loader</p></div><div className="text-center"><p className="text-3xl font-black text-indigo-500">→</p><p className="mt-2 text-xs font-bold text-slate-500">explicit transfer</p></div><div className="rounded-2xl border-2 border-emerald-400 bg-emerald-50 p-5"><p className="text-center text-3xl">⚡</p><p className="mt-2 text-center font-bold text-emerald-950">GPU memory</p><div className="mt-4 grid grid-cols-3 gap-3">{[["input batch","x.to(device)"],["model weights","model.to(device)"],["operations","matmul / conv"]].map(([title,code])=><div key={title} className="rounded-lg bg-white p-3 text-center"><p className="text-sm font-bold text-slate-900">{title}</p><p className="mt-2 font-mono text-xs text-emerald-700">{code}</p></div>)}</div><p className="mt-4 text-center text-xs text-emerald-800">output stays on the GPU until copied or consumed there</p></div></div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">Repeated CPU↔GPU copies can erase acceleration. Move batches in reasonably large chunks and keep connected operations on the same device.</figcaption></figure>;
}

const rankRows = [
  ["Scalar", "0", "[]", "one loss value: 0.24"],
  ["Vector", "1", "[4]", "four features"],
  ["Matrix", "2", "[8,4]", "eight examples × four features"],
  ["3-D tensor", "3", "[10,20,64]", "batch × tokens × embedding features"],
  ["4-D tensor", "4", "[32,3,64,64]", "batch of colour images"],
];

export function TensorsFrameworksGPUsContent() {
  return <div className="prose prose-lg max-w-none text-slate-700">
    <section className="not-prose mb-10 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-cyan-950 to-indigo-800 px-6 py-10 text-white shadow-xl md:px-10 md:py-12"><p className="mb-3 text-sm font-extrabold uppercase tracking-[0.18em] text-cyan-200">Deep Learning · Practical Foundations</p><h2 className="max-w-4xl text-3xl font-black leading-tight md:text-5xl">Tensors, Frameworks and GPUs</h2><p className="mt-5 max-w-4xl text-lg leading-relaxed text-cyan-50 md:text-xl">Deep-learning code turns examples and model parameters into tensors, applies a recorded sequence of operations, and often runs those operations on a GPU. This lesson makes tensor shapes, axes, data types, broadcasting, matrix multiplication, device movement and framework responsibilities visible before they become confusing error messages.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What a Tensor Actually Is</h2><p className="text-lg leading-relaxed">A <strong>tensor</strong> is an organized collection of values used by a deep-learning framework. Besides the values themselves, the framework tracks its <strong>shape</strong> (axis lengths), <strong>data type</strong> or dtype (how each value is stored), and <strong>device</strong> (where it lives, such as CPU or GPU memory).</p><p className="text-lg leading-relaxed">“Rank” here means the number of axes, not matrix rank. A scalar has no axes, a vector has one, a matrix has two, and an image batch commonly has four. Names such as batch, channel, height and width are meanings supplied by the programmer and data pipeline; the tensor itself mainly records their ordered sizes.</p><TensorProgressionFigure /><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Object</th><th className="p-3 text-left">Rank</th><th className="p-3 text-left">Example shape</th><th className="p-3 text-left">Possible meaning</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{rankRows.map(([name,rank,shape,meaning])=><tr key={name}><td className="p-3 font-bold text-indigo-800">{name}</td><td className="p-3">{rank}</td><td className="p-3 font-mono text-emerald-800">{shape}</td><td className="p-3">{meaning}</td></tr>)}</tbody></table></div><RGBPixelFigure /><TensorShapeFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Axes Explain Almost Every Shape Operation</h2><p className="text-lg leading-relaxed"><strong>Indexing</strong> selects values. <strong>Reshape</strong> groups the same number of values into different axis lengths. <strong>Transpose</strong> swaps two axes; <strong>permute</strong> can reorder several. <strong>Unsqueeze</strong> inserts a length-1 axis, often to create a batch or channel position, while <strong>squeeze</strong> removes a length-1 axis.</p><div className="not-prose grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><h3 className="text-lg font-bold text-violet-950">Tiny values: shape [2,3]</h3><p className="mt-3 rounded-lg bg-white p-4 font-mono text-sm leading-7">A = [[1,2,3],<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[4,5,6]]</p><p className="mt-3 text-sm text-slate-700">There are 2 rows and 3 columns, so 2×3=6 stored values.</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h3 className="text-lg font-bold text-emerald-950">Same values, different arrangements</h3><p className="mt-3 font-mono text-sm leading-7">reshape(3,2) → [[1,2],[3,4],[5,6]]<br />transpose(0,1) → [[1,4],[2,5],[3,6]]<br />unsqueeze(0) → shape [1,2,3]</p><p className="mt-3 text-sm text-slate-700">Reshape changes grouping; transpose changes which axis comes first; unsqueeze adds a one-example batch axis.</p></div></div><div className="not-prose mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-5 md:p-6"><h3 className="text-xl font-bold text-blue-950">Follow one image batch</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7">x.shape = [32,3,64,64]<br />x[0].shape = <strong>[3,64,64]</strong><br /><span className="text-slate-600">select first image; batch axis disappears</span></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7">x[:,0].shape = <strong>[32,64,64]</strong><br /><span className="text-slate-600">select red channel from every image</span></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7">x.permute(0,2,3,1)<br />shape = <strong>[32,64,64,3]</strong><br /><span className="text-slate-600">NCHW → NHWC; values stay attached to their pixel</span></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7">x.flatten(1).shape<br />= <strong>[32,12288]</strong><br /><span className="text-slate-600">3×64×64=12,288 features per image</span></p></div></div><p className="mt-5 text-lg leading-relaxed">These operations may return a view that shares memory or may require copying, depending on layout and framework rules. The beginner&apos;s first responsibility is semantic: after every change, write what each axis means and confirm the element count when reshaping.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Elementwise Operations and Matrix Multiplication Are Not the Same</h2><p className="text-lg leading-relaxed">Elementwise multiplication pairs values at matching positions. Matrix multiplication combines rows with columns using dot products. Confusing <code>*</code> with <code>@</code> can produce an error—or worse, a valid but unintended result.</p><div className="not-prose grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-amber-200 bg-amber-50 p-5"><p className="font-bold text-amber-950">Elementwise</p><p className="mt-3 font-mono text-sm leading-7">[1,2] * [3,4]<br />= <strong>[3,8]</strong></p><p className="mt-3 text-sm text-slate-700">same positions multiply</p></div><div className="rounded-xl border border-violet-200 bg-violet-50 p-5"><p className="font-bold text-violet-950">Dot product</p><p className="mt-3 font-mono text-sm leading-7">[1,2] · [3,4]<br />= 1×3 + 2×4<br />= <strong>11</strong></p><p className="mt-3 text-sm text-slate-700">products are summed</p></div></div><p className="mt-5 text-lg leading-relaxed">For matrix multiplication [B,F] @ [F,O] → [B,O]. B is batch size, F is input features and O is output features. The shared F dimensions are consumed by the dot products.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Broadcasting Reuses Smaller Tensors Without Manual Copies</h2><p className="text-lg leading-relaxed"><strong>Broadcasting</strong> allows compatible shapes to participate in an elementwise operation. Compare axes from the right: lengths must match, one must be 1, or an axis may be absent. The smaller tensor behaves as if expanded, usually without physically copying every value.</p><div className="not-prose rounded-2xl border border-emerald-200 bg-emerald-50 p-5 md:p-6"><h3 className="text-xl font-bold text-emerald-950">Add one feature bias to two examples</h3><p className="mt-4 rounded-lg bg-white p-4 font-mono text-sm leading-7">X = [[1,2,3],       b = [10,20,30]<br />     [4,5,6]]<br /><br />X + b = [[11,22,33],<br />         [14,25,36]]</p><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Why it works:</strong> X has shape [2,3] and b has shape [3]. The trailing dimension 3 matches, so b is reused for both rows. Beware: [4,1] + [4] produces [4,4], which may run successfully while violating your intent.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What a Deep-Learning Framework Does for You</h2><p className="text-lg leading-relaxed">A framework such as PyTorch or TensorFlow is more than an array library. It supplies tensor operations implemented for different devices, neural-network layers, automatic differentiation, optimizers, data pipelines, serialization and deployment/export tools. Keras provides a higher-level model-building interface integrated with its supported backend ecosystem.</p><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[960px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Responsibility</th><th className="p-3 text-left">Framework helps with</th><th className="p-3 text-left">You still decide/check</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Tensor computation","fast kernels, broadcasting and device support","shapes, dtypes and semantic axes"],["Model definition","reusable layers and parameter registration","architecture and output meaning"],["Gradient calculation","records operations and applies chain rule","correct loss, graph connectivity and gradient scale"],["Optimization","standard update algorithms and schedulers","learning rate, parameter groups and validation"],["Data input","batching, transforms and parallel loading","split integrity, labels and preprocessing"],["Saving/export","state and runtime conversion tools","versioned contract and equivalence tests"]].map(([area,helps,owner])=><tr key={area}><td className="p-3 font-bold text-slate-900">{area}</td><td className="p-3 text-indigo-800">{helps}</td><td className="p-3 text-emerald-800">{owner}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why GPUs Can Accelerate Deep Learning</h2><p className="text-lg leading-relaxed">A CPU is excellent for varied sequential work and system tasks. A GPU contains many execution units designed to perform large numbers of similar numerical operations in parallel. Matrix multiplications and convolutions contain abundant parallel work, so sufficiently large neural-network workloads can benefit.</p><p className="text-lg leading-relaxed">The GPU has separate memory. Moving a model to the GPU does not automatically move an input batch, and mixing devices raises an error. Small workloads may be slower after transfer and launch overhead. Always benchmark the full input pipeline on the actual hardware.</p><GPUFlowFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Memory Is Often the First GPU Limit</h2><p className="text-lg leading-relaxed">Training stores parameters, gradients, optimizer state and intermediate activations needed for backpropagation. A raw tensor&apos;s approximate storage is number of values × bytes per value.</p><div className="not-prose rounded-2xl border border-violet-200 bg-violet-50 p-5 md:p-6"><h3 className="text-xl font-bold text-violet-950">Estimate one FP32 image batch</h3><p className="mt-2 text-slate-700">For shape [32,3,224,224], there are 32×3×224×224=4,816,896 values. FP32 uses 4 bytes per value.</p><p className="mt-4 rounded-lg bg-white p-4 font-mono text-sm leading-7">4,816,896 × 4 = 19,267,584 bytes<br />≈ <strong>18.4 MiB</strong> (divide by 1,048,576)</p><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> this is only the input tensor. Activations across layers, gradients and optimizer state can require far more. Halving batch size may reduce activation memory but does not halve fixed model/optimizer storage.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Data Types Trade Precision, Range, Memory and Speed</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">dtype</th><th className="p-3 text-left">Typical role</th><th className="p-3 text-left">Benefit</th><th className="p-3 text-left">Caution</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["float32","default model computation","wide practical compatibility","more memory than 16-bit formats"],["float16","mixed-precision acceleration on supported hardware","smaller/faster operations","limited range; gradients may underflow without scaling"],["bfloat16","mixed precision on supported accelerators","float32-like exponent range","fewer fraction bits; hardware support varies"],["int64 / long","class indices and token IDs","exact integer indexing","not a normal neural-network weight dtype"],["bool","masks","clear binary semantics","cannot represent scores"]].map(([dtype,role,benefit,caution])=><tr key={dtype}><td className="p-3 font-mono font-bold text-indigo-800">{dtype}</td><td className="p-3">{role}</td><td className="p-3 text-emerald-800">{benefit}</td><td className="p-3 text-rose-800">{caution}</td></tr>)}</tbody></table></div><p className="mt-5 text-lg leading-relaxed"><strong>Automatic mixed precision</strong> lets a framework choose lower precision for suitable operations while keeping sensitive reductions or updates in safer precision. It is a controlled execution policy, not simply converting every tensor to half precision.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Device-Safe PyTorch Example</h2><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">tensor_device_basics.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Two examples, each with three input features.
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]], device=device)       # [2, 3]
w = torch.tensor([[0.1, 0.4],
                  [0.2, 0.5],
                  [0.3, 0.6]], device=device)         # [3, 2]
b = torch.tensor([1.0, -1.0], device=device)          # [2]

scores = x @ w + b  # [2,3] @ [3,2] -> [2,2]; b broadcasts

print("device:", scores.device)
print("shape:", scores.shape)
print(scores)
assert scores.shape == (2, 2)
assert torch.isfinite(scores).all()`}</pre></div><p className="mt-4 text-sm leading-relaxed text-slate-600">Expected scores are [[2.4, 2.2], [4.2, 6.7]]. Print shape, dtype and device at boundaries before debugging the model&apos;s mathematics.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Shape and Device Errors Become Easier to Diagnose</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Symptom</th><th className="p-3 text-left">Likely reason</th><th className="p-3 text-left">First inspection</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["matmul shape error","feature dimension and weight input dimension differ","print the two shapes and write [B,F]@[F,O]"],["expected 4-D input","batch or channel axis missing","print shape after the data loader and transform"],["tensors on different devices","input/target/model were moved inconsistently","print .device for each tensor and first parameter"],["wrong target type for classification","class indices are floating point or one-hot for the chosen loss","check target shape/dtype against the loss contract"],["silent [B,B] output","a [B,1] value broadcast with a [B] value","make singleton axes intentional; assert result shape"],["GPU slower than CPU","workload too small or copies/input pipeline dominate","benchmark after warm-up and profile transfers"],["CUDA out of memory","batch/activation/model state exceeds device memory","measure peak memory; reduce batch/shape or use checkpointing/mixed precision"]].map(([symptom,cause,check])=><tr key={symptom}><td className="p-3 font-bold text-slate-900">{symptom}</td><td className="p-3 text-rose-800">{cause}</td><td className="p-3 text-indigo-800">{check}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Practical Tensor Checklist</h2><div className="not-prose rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><ul className="m-0 space-y-2 pl-5 text-emerald-950"><li>Name every axis in words before writing a complex shape.</li><li>Check shape, dtype, device and finite values at data/model/loss boundaries.</li><li>Use <code>@</code> for matrix multiplication and understand when broadcasting occurs.</li><li>Move the model, inputs and targets to the same device; avoid repeated transfers.</li><li>Estimate memory from element count, then remember training needs activations and optimizer state too.</li><li>Use mixed precision through the framework&apos;s supported mechanism and verify numerical quality.</li><li>Benchmark real batches on the target hardware; a GPU is an accelerator, not a promise.</li></ul></div></section>

    <section><h2 className="mb-4 border-b pb-2 text-2xl font-bold text-indigo-800">Continue Learning</h2><div className="not-prose mb-10 grid gap-4 md:grid-cols-2"><a href="/learn/activation-functions" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Previous concept</p><p className="m-0 font-bold text-slate-900">Activation Functions</p></a><a href="/learn/loss-functions-deep-learning" className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Next concept</p><p className="m-0 font-bold text-slate-900">Loss Functions</p></a></div></section>
  </div>;
}
