import React from "react";

function TrainingCycleDiagram() {
  const steps = [
    [25, "1", "Load a batch", "images + correct labels", "#2563eb"],
    [178, "2", "Clear gradients", "remove values from last batch", "#7c3aed"],
    [331, "3", "Forward pass", "model makes predictions", "#0891b2"],
    [484, "4", "Calculate loss", "measure this batch’s mistakes", "#e11d48"],
    [637, "5", "Backward pass", "calculate every gradient", "#d97706"],
    [790, "6", "Update weights", "optimizer takes one step", "#059669"],
  ] as const;
  return <figure className="not-prose my-7"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><svg viewBox="0 0 950 270" className="w-full min-w-[850px]" role="img" aria-labelledby="cycle-title cycle-desc"><title id="cycle-title">The six operations repeated for every training batch</title><desc id="cycle-desc">Load a batch, clear old gradients, perform the forward pass, calculate the loss, perform the backward pass, and update the weights. Then repeat with the next batch.</desc><rect x="2" y="2" width="946" height="266" rx="18" fill="#f8fafc" />
    <defs><marker id="train-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#64748b" /></marker><marker id="repeat-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#4f46e5" /></marker></defs>
    {steps.slice(0,-1).map(([x],i)=><line key={i} x1={Number(x)+125} y1="113" x2={Number(steps[i+1][0])-10} y2="113" stroke="#64748b" strokeWidth="3" markerEnd="url(#train-arrow)" />)}
    {steps.map(([x,n,label,detail,color])=><g key={n}><rect x={x} y="65" width="125" height="98" rx="16" fill="white" stroke={color} strokeWidth="2.5" /><circle cx={Number(x)+18} cy="82" r="16" fill={color} /><text x={Number(x)+18} y="87" textAnchor="middle" fontSize="12" fontWeight="800" fill="white">{n}</text><text x={Number(x)+62.5} y="113" textAnchor="middle" fontSize="14" fontWeight="800" fill="#0f172a">{label}</text><text x={Number(x)+62.5} y="135" textAnchor="middle" fontSize="9.5" fill="#64748b">{detail}</text></g>)}
    <path d="M852 175 C850 237 95 240 86 177" fill="none" stroke="#4f46e5" strokeWidth="3" strokeDasharray="8 5" markerEnd="url(#repeat-arrow)" /><text x="474" y="230" textAnchor="middle" fontSize="13" fontWeight="800" fill="#3730a3">repeat with the next batch until the epoch is complete</text>
  </svg></div><figcaption className="mt-3 text-center text-sm text-slate-600">Figure 1: One training step is a six-part correction cycle performed on one batch.</figcaption></figure>;
}

function EpochBatchDiagram() {
  const batches = [[65,"Batch 1","16 examples"],[195,"Batch 2","16 examples"],[325,"Batch 3","16 examples"],[455,"Batch 4","16 examples"],[585,"Batch 5","16 examples"],[715,"Batch 6","16 examples"],[845,"Batch 7","4 examples"]] as const;
  return <figure className="not-prose my-7"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><svg viewBox="0 0 990 235" className="w-full min-w-[880px]" role="img" aria-label="One hundred examples divided into seven training batches"><rect x="2" y="2" width="986" height="231" rx="18" fill="#eff6ff" /><text x="495" y="31" textAnchor="middle" fontSize="17" fontWeight="800" fill="#1e3a8a">ONE EPOCH = every training example is visited once</text><line x1="65" y1="68" x2="910" y2="68" stroke="#93c5fd" strokeWidth="4" />{batches.map(([x,label,detail],i)=><g key={label}><circle cx={x} cy="68" r="9" fill="#2563eb" /><rect x={Number(x)-52} y="88" width="104" height="74" rx="13" fill="white" stroke="#60a5fa" strokeWidth="2" /><text x={x} y="116" textAnchor="middle" fontSize="13" fontWeight="800" fill="#1e40af">{label}</text><text x={x} y="138" textAnchor="middle" fontSize="11" fill="#475569">{detail}</text><text x={x} y="184" textAnchor="middle" fontSize="11" fontWeight="700" fill="#047857">update {i+1}</text></g>)}<text x="495" y="216" textAnchor="middle" fontSize="12" fontWeight="700" fill="#475569">100 examples ÷ batch size 16 = 6 full batches + 1 smaller final batch = 7 updates</text></svg></div><figcaption className="mt-3 text-center text-sm text-slate-600">Figure 2: Batch size determines how often the model updates during one epoch.</figcaption></figure>;
}

function TrainValidationDiagram() {
  return <figure className="not-prose my-7"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><svg viewBox="0 0 820 360" className="w-full" role="img" aria-labelledby="tv-title tv-desc"><title id="tv-title">Training and validation are separate passes</title><desc id="tv-desc">Training data follows forward, loss, backward and update steps. Validation data follows forward, loss and metrics only, with no gradient or weight update.</desc><rect x="2" y="2" width="816" height="356" rx="18" fill="#f8fafc" /><defs><marker id="tv-blue" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#2563eb" /></marker><marker id="tv-green" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#059669" /></marker></defs>
    <rect x="30" y="45" width="760" height="116" rx="16" fill="#eff6ff" stroke="#93c5fd" strokeWidth="2" /><text x="55" y="72" fontSize="15" fontWeight="800" fill="#1e40af">TRAINING PASS — learning is ON</text>{[[60,"Training batch"],[220,"Forward + loss"],[380,"Backward"],[540,"Update weights"]].map(([x,label],i)=><g key={String(label)}><rect x={Number(x)} y="92" width="120" height="45" rx="11" fill="white" stroke="#2563eb" /><text x={Number(x)+60} y="119" textAnchor="middle" fontSize="12" fontWeight="700" fill="#1e3a8a">{label}</text>{i<3&&<line x1={Number(x)+123} y1="114" x2={Number(x)+153} y2="114" stroke="#2563eb" strokeWidth="2.5" markerEnd="url(#tv-blue)" />}</g>)}<rect x="680" y="92" width="85" height="45" rx="11" fill="#dbeafe" stroke="#2563eb" /><text x="722" y="111" textAnchor="middle" fontSize="10" fontWeight="700" fill="#1e40af">weights</text><text x="722" y="126" textAnchor="middle" fontSize="10" fontWeight="700" fill="#1e40af">changed</text>
    <rect x="30" y="195" width="760" height="116" rx="16" fill="#ecfdf5" stroke="#6ee7b7" strokeWidth="2" /><text x="55" y="222" fontSize="15" fontWeight="800" fill="#065f46">VALIDATION PASS — learning is OFF</text>{[[80,"Validation batch"],[270,"Forward + loss"],[460,"Metrics"],[650,"Record result"]].map(([x,label],i)=><g key={String(label)}><rect x={Number(x)} y="242" width="120" height="45" rx="11" fill="white" stroke="#059669" /><text x={Number(x)+60} y="269" textAnchor="middle" fontSize="12" fontWeight="700" fill="#065f46">{label}</text>{i<3&&<line x1={Number(x)+123} y1="264" x2={Number(x)+183} y2="264" stroke="#059669" strokeWidth="2.5" markerEnd="url(#tv-green)" />}</g>)}<text x="410" y="338" textAnchor="middle" fontSize="12" fontWeight="800" fill="#9f1239">No backward pass · No optimizer step · No information leaks back into training</text>
  </svg></div><figcaption className="mt-3 text-center text-sm text-slate-600">Figure 3: Training changes the model; validation only measures the current model.</figcaption></figure>;
}

type CurveMode = "healthy" | "overfit" | "stalled";
function TrainingCurve({ mode }: { mode: CurveMode }) {
  const specs = {
    healthy: { title: "Healthy learning", train: [0.95,0.72,0.55,0.43,0.35,0.30], val: [1.02,0.82,0.68,0.59,0.54,0.51], note: "Both losses fall; validation remains a little higher." },
    overfit: { title: "Overfitting", train: [0.95,0.70,0.49,0.34,0.24,0.17], val: [1.02,0.80,0.66,0.69,0.82,1.01], note: "Training improves while validation gets worse after epoch 3." },
    stalled: { title: "Learning has stalled", train: [0.95,0.94,0.95,0.93,0.94,0.93], val: [1.02,1.01,1.02,1.00,1.01,1.00], note: "Both curves stay almost flat; investigate the pipeline." },
  }[mode];
  const left=38,right=305,top=28,bottom=165;
  const toX=(i:number)=>left+(i/5)*(right-left);
  const toY=(v:number)=>bottom-((1.1-v)/1.0)*(bottom-top);
  const makePath=(values:number[])=>values.map((v,i)=>`${i?"L":"M"} ${toX(i)} ${toY(v)}`).join(" ");
  return <figure className="not-prose m-0 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p className="mb-2 text-center font-extrabold text-slate-900">{specs.title}</p><svg viewBox="0 0 335 210" className="w-full" role="img" aria-label={`${specs.title} training and validation loss graph`}><rect x="1" y="1" width="333" height="208" rx="12" fill="#f8fafc" />{[0.2,0.5,0.8,1.1].map(v=><g key={v}><line x1={left} y1={toY(v)} x2={right} y2={toY(v)} stroke="#e2e8f0" /><text x={left-6} y={toY(v)+3} textAnchor="end" fontSize="8" fill="#64748b">{v}</text></g>)}<line x1={left} y1={bottom} x2={right} y2={bottom} stroke="#64748b" /><line x1={left} y1={top} x2={left} y2={bottom} stroke="#64748b" /><path d={makePath(specs.train)} fill="none" stroke="#4f46e5" strokeWidth="3.5" /><path d={makePath(specs.val)} fill="none" stroke="#f97316" strokeWidth="3.5" />{[0,1,2,3,4,5].map(i=><text key={i} x={toX(i)} y={bottom+15} textAnchor="middle" fontSize="8" fill="#64748b">{i+1}</text>)}<line x1="170" y1="18" x2="187" y2="18" stroke="#4f46e5" strokeWidth="3" /><text x="191" y="21" fontSize="8" fill="#475569">training</text><line x1="235" y1="18" x2="252" y2="18" stroke="#f97316" strokeWidth="3" /><text x="256" y="21" fontSize="8" fill="#475569">validation</text><text x="171" y="192" textAnchor="middle" fontSize="9" fontWeight="700" fill="#475569">epoch</text><text x="11" y="102" textAnchor="middle" transform="rotate(-90 11 102)" fontSize="9" fontWeight="700" fill="#475569">loss</text></svg><figcaption className="px-2 pb-2 text-center text-xs leading-relaxed text-slate-600">{specs.note}</figcaption></figure>;
}

function TermCard({ term, children }: { term: string; children: React.ReactNode }) {
  return <div className="not-prose rounded-xl border border-slate-200 bg-white p-4"><p className="mb-1 font-mono font-extrabold text-indigo-800">{term}</p><p className="m-0 text-sm leading-relaxed text-slate-600">{children}</p></div>;
}

function NumberStep({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return <div className="not-prose grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-[42px_1fr]"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-600 font-extrabold text-white">{n}</span><div><p className="mb-1 font-extrabold text-slate-900">{title}</p><div className="text-sm leading-relaxed text-slate-700">{children}</div></div></div>;
}

export function TrainingLoopContent() {
  return <div className="space-y-10">
    <header className="mb-8"><p className="mb-2 text-sm font-bold uppercase tracking-widest text-indigo-600">Deep Learning · Beginner Lesson</p><h2 className="mb-3 text-4xl font-extrabold text-slate-900">Training a Neural Network: The Complete Loop From Data to Better Predictions</h2><p className="mb-0 text-lg leading-relaxed text-slate-600">Creating a neural network only gives us a collection of layers with untrained weights. A <strong>training loop</strong> is the repeated procedure that shows the network examples, measures its mistakes, corrects its weights and checks whether those corrections also help on unseen data. This lesson follows one batch through every operation and explains what should happen at the end of an epoch.</p></header>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What Does “Training” Actually Mean?</h2><p className="text-lg leading-relaxed">Imagine a factory camera that must label a product as <strong>acceptable</strong> or <strong>defective</strong>. At first, its weights are random, so its answers are poor. Training does not give the camera one long instruction. It performs thousands of small correction cycles:</p><div className="not-prose my-5 rounded-2xl border border-indigo-200 bg-indigo-50 p-5 text-center"><p className="m-0 font-mono text-base font-extrabold text-indigo-950 md:text-xl">examples → predictions → measured mistakes → gradients → corrected weights</p></div><p className="text-lg leading-relaxed">The word <strong>loop</strong> matters because the same operations are repeated. One repetition for one batch is a <strong>training step</strong>. Repeating steps until the complete training set has been used once creates an <strong>epoch</strong>. Repeating epochs gives the weights many opportunities to improve.</p><TrainingCycleDiagram /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Essential Terms Before We Build the Loop</h2><div className="not-prose grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><TermCard term="Training example">One input together with its correct target, such as one product image and its defect label.</TermCard><TermCard term="Batch">A small group of examples processed together before one weight update.</TermCard><TermCard term="Training step / iteration">One complete batch cycle: predict, calculate loss, backpropagate and update.</TermCard><TermCard term="Epoch">One pass through all examples in the training set.</TermCard><TermCard term="Validation set">Separate examples used to measure the current model without changing its weights.</TermCard><TermCard term="Metric">A human-readable measurement such as accuracy or MAE, reported alongside the training loss.</TermCard></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">What Happens to One Batch?</h2><p className="text-lg leading-relaxed">Suppose a batch contains 16 product images and 16 correct labels. The six operations below form one meaningful unit. Each step exists because the next one depends on it.</p><div className="space-y-4">
      <NumberStep n={1} title="Load inputs and targets"><p className="m-0">The data loader supplies image tensors and their correct labels. Inspect their shape, value range and labels before trusting the loop.</p></NumberStep>
      <NumberStep n={2} title="Clear gradients from the previous batch"><p className="m-0">PyTorch normally <strong>adds</strong> new gradients to existing ones. <code>optimizer.zero_grad()</code> removes the old values so this batch produces a fresh correction.</p></NumberStep>
      <NumberStep n={3} title="Run the forward pass"><p className="m-0">The batch travels through the current network. The model produces raw output scores called <strong>logits</strong>. No weights change yet.</p></NumberStep>
      <NumberStep n={4} title="Calculate the batch loss"><p className="m-0">The loss function compares the logits with the correct labels and returns one average penalty for this batch.</p></NumberStep>
      <NumberStep n={5} title="Run the backward pass"><p className="m-0"><code>loss.backward()</code> calculates a gradient for every trainable weight. A gradient tells how that weight influenced the loss.</p></NumberStep>
      <NumberStep n={6} title="Update the weights"><p className="m-0"><code>optimizer.step()</code> uses the gradients and learning rate to change the weights. This is the only step in this cycle that actually changes the model.</p></NumberStep>
    </div><div className="not-prose mt-5 rounded-xl border-l-4 border-amber-400 bg-amber-50 p-5"><p className="m-0 text-sm leading-relaxed text-amber-950"><strong>Why the order matters:</strong> loss cannot be calculated before a prediction exists; gradients cannot be calculated before a loss exists; and the optimizer cannot make an informed update before gradients exist.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">How Batches Form an Epoch</h2><p className="text-lg leading-relaxed">Processing the entire dataset at once may not fit in memory. Instead, the data loader divides it into batches. For <strong>N</strong> examples and batch size <strong>B</strong>:</p><div className="not-prose my-5 rounded-2xl bg-indigo-950 p-5 text-white"><p className="mb-2 text-xs font-extrabold uppercase tracking-widest text-indigo-300">Formula</p><p className="m-0 font-mono text-xl font-extrabold">updates per epoch = ⌈N ÷ B⌉</p><p className="mt-3 mb-0 text-sm text-indigo-100">The ceiling brackets ⌈ ⌉ mean round upward because a smaller final batch still needs to be processed.</p></div><EpochBatchDiagram /><div className="not-prose grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="mb-1 font-bold text-slate-900">Small batch</p><p className="m-0 text-sm text-slate-600">Frequent, noisier updates and lower memory use.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="mb-1 font-bold text-slate-900">Large batch</p><p className="m-0 text-sm text-slate-600">Smoother gradient estimate but more memory and fewer updates per epoch.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="mb-1 font-bold text-slate-900">One epoch</p><p className="m-0 text-sm text-slate-600">A unit for scheduling validation, checkpoints and learning-rate changes.</p></div></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Complete Weight Update With Small Numbers</h2><p className="text-lg leading-relaxed">To see what the loop accomplishes, use the one-weight model <strong>ŷ = wx</strong>. It receives input x = 2 and should produce target y = 4. Start with w = 0.5, learning rate η = 0.1 and loss L = ½(ŷ − y)².</p><div className="not-prose my-5 grid gap-3 sm:grid-cols-4">{[["Input x","2"],["Target y","4"],["Starting w","0.5"],["Learning rate η","0.1"]].map(([label,value])=><div key={label} className="rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-center"><p className="mb-1 text-xs font-bold text-indigo-700">{label}</p><p className="m-0 font-mono text-xl font-extrabold text-indigo-950">{value}</p></div>)}</div><div className="space-y-3"><NumberStep n={1} title="Forward"><p className="m-0 font-mono">ŷ = wx = 0.5 × 2 = <strong>1</strong></p></NumberStep><NumberStep n={2} title="Loss"><p className="m-0 font-mono">L = ½(1 − 4)² = <strong>4.5</strong></p></NumberStep><NumberStep n={3} title="Backward"><p className="m-0 font-mono">∂L/∂w = (ŷ − y)x = (1 − 4) × 2 = <strong>−6</strong></p></NumberStep><NumberStep n={4} title="Update"><p className="m-0 font-mono">w_new = w − η(∂L/∂w) = 0.5 − 0.1(−6) = <strong>1.1</strong></p></NumberStep><NumberStep n={5} title="Verify the next step"><p className="m-0 font-mono">ŷ_new = 1.1 × 2 = 2.2; L_new = ½(2.2 − 4)² = <strong>1.62</strong></p></NumberStep></div><div className="not-prose mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="mb-1 font-extrabold text-emerald-950">What changed?</p><p className="m-0 text-sm leading-relaxed text-slate-700">One batch update moved w from 0.5 to 1.1 and reduced loss from 4.5 to 1.62. The next batch repeats the same six operations using the new weight. Training is many small improvements like this.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Training and Validation Have Different Jobs</h2><p className="text-lg leading-relaxed">Training performance answers, “Is the optimizer fitting the examples it is allowed to learn from?” Validation performance answers, “Do those learned patterns also work on separate examples?” If validation examples update the weights, they are no longer an honest test of generalization.</p><TrainValidationDiagram /><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Question</th><th className="p-3 text-left">Training pass</th><th className="p-3 text-left">Validation pass</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Which data?","Training batches","Held-out validation batches"],["Model mode?","model.train()","model.eval()"],["Calculate gradients?","Yes","No"],["Update weights?","Yes","Never"],["Random augmentation?","Usually yes","No; use deterministic preprocessing"],["Main purpose","Learn parameters","Measure and choose checkpoints/settings"]].map(([q,a,b])=><tr key={q}><td className="p-3 font-bold text-indigo-800">{q}</td><td className="p-3 text-slate-700">{a}</td><td className="p-3 text-slate-700">{b}</td></tr>)}</tbody></table></div><p className="mt-4 text-lg leading-relaxed"><code>model.eval()</code> does not calculate accuracy and does not disable gradients by itself. It changes the behaviour of layers such as dropout and batch normalization. <code>torch.no_grad()</code> separately prevents gradient recording, saving memory and computation.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">How to Read Training Curves</h2><p className="text-lg leading-relaxed">At the end of each epoch, record average training loss and validation loss. A single point cannot show a trend, but the shape across several epochs can reveal whether learning is useful, overfitting or stalled.</p><div className="not-prose grid gap-5 lg:grid-cols-3"><TrainingCurve mode="healthy" /><TrainingCurve mode="overfit" /><TrainingCurve mode="stalled" /></div><div className="not-prose mt-5 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[800px] text-sm"><thead className="bg-indigo-950 text-white"><tr><th className="p-3 text-left">Pattern</th><th className="p-3 text-left">Likely meaning</th><th className="p-3 text-left">What to check next</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white"><tr><td className="p-3 font-bold text-emerald-800">Both losses fall</td><td className="p-3">The model is learning patterns that transfer.</td><td className="p-3">Continue while validation improves; save the best checkpoint.</td></tr><tr><td className="p-3 font-bold text-amber-800">Training falls, validation rises</td><td className="p-3">The model is increasingly memorizing training-specific details.</td><td className="p-3">Use early stopping, data augmentation, weight decay, dropout or more representative data.</td></tr><tr><td className="p-3 font-bold text-rose-800">Both remain flat</td><td className="p-3">The learning signal may be ineffective or the pipeline may be broken.</td><td className="p-3">Check labels, gradients, learning rate, frozen parameters and loss/output compatibility.</td></tr><tr><td className="p-3 font-bold text-rose-800">Loss becomes NaN or explodes</td><td className="p-3">Numerical instability or excessively large updates.</td><td className="p-3">Inspect input scale, learning rate, loss math and gradient norms.</td></tr></tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Tiny-Data Test: Check the Loop Before Tuning the Model</h2><p className="text-lg leading-relaxed">Before a long training run, take perhaps 10–20 clean examples and deliberately ask the model to memorize them. This is not the final goal. It is a diagnostic test: a sufficiently capable network should be able to drive training loss very low on such a tiny set.</p><div className="not-prose grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-5"><p className="mb-2 font-extrabold text-indigo-950">1. Create the test</p><p className="m-0 text-sm leading-relaxed text-slate-700">Use a fixed tiny batch with verified inputs and labels. Temporarily reduce augmentation and regularization.</p></div><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-5"><p className="mb-2 font-extrabold text-indigo-950">2. Try to memorize</p><p className="m-0 text-sm leading-relaxed text-slate-700">Train repeatedly on only those examples and watch training loss and accuracy.</p></div><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-5"><p className="mb-2 font-extrabold text-indigo-950">3. Interpret</p><p className="m-0 text-sm leading-relaxed text-slate-700">If loss cannot become very small, fix the data, model, gradients or loop before tuning generalization.</p></div></div><div className="not-prose mt-5 rounded-xl border-l-4 border-rose-400 bg-rose-50 p-5"><p className="m-0 text-sm leading-relaxed text-rose-950"><strong>What the test does not prove:</strong> memorizing 20 examples only shows that the training path can fit them. It does not prove the model will generalize to new factory images.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Complete PyTorch Training and Validation Loop</h2><p className="text-lg leading-relaxed">This code mirrors the diagrams exactly. The inner loop performs one correction per training batch. The second loop measures validation batches without gradients or updates.</p><div className="not-prose overflow-hidden rounded-xl bg-[#172033] shadow-lg"><div className="flex items-center gap-2 bg-slate-800 px-4 py-2 text-xs font-mono text-slate-300"><span className="h-3 w-3 rounded-full bg-red-400" /><span className="h-3 w-3 rounded-full bg-amber-400" /><span className="h-3 w-3 rounded-full bg-emerald-400" /><span className="ml-2">training_loop.py</span></div><pre className="overflow-x-auto p-5 text-sm leading-relaxed text-slate-100"><code>{`for epoch in range(num_epochs):
    # ----- TRAIN: weights change -----
    model.train()
    train_loss_sum = 0.0

    for inputs, targets in train_loader:       # 1. load batch
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()                   # 2. clear old gradients
        logits = model(inputs)                  # 3. forward pass
        loss = loss_fn(logits, targets)         # 4. calculate loss
        loss.backward()                         # 5. backward pass
        optimizer.step()                        # 6. update weights
        train_loss_sum += loss.item() * inputs.size(0)

    train_loss = train_loss_sum / len(train_loader.dataset)

    # ----- VALIDATE: weights do not change -----
    model.eval()
    val_loss_sum = 0.0
    correct = 0

    with torch.no_grad():
        for inputs, targets in val_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            logits = model(inputs)
            val_loss_sum += loss_fn(logits, targets).item() * inputs.size(0)
            correct += (logits.argmax(dim=1) == targets).sum().item()

    val_loss = val_loss_sum / len(val_loader.dataset)
    val_accuracy = correct / len(val_loader.dataset)
    print(epoch + 1, train_loss, val_loss, val_accuracy)`}</code></pre></div><div className="not-prose mt-5 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[800px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Code</th><th className="p-3 text-left">Plain meaning</th><th className="p-3 text-left">Common mistake it prevents</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["model.train()","Turn on training behaviour","Accidentally leaving dropout disabled"],["optimizer.zero_grad()","Remove gradients from the previous batch","Unwanted gradient accumulation"],["loss.backward()","Calculate current gradients","Optimizer stepping with no new direction"],["optimizer.step()","Change the weights","Thinking backward itself updates parameters"],["model.eval()","Use inference behaviour","Validation changing with dropout/BatchNorm mode"],["torch.no_grad()","Do not record a backward graph","Wasting validation memory and computation"]].map(([code,meaning,mistake])=><tr key={code}><td className="p-3 font-mono font-bold text-indigo-800">{code}</td><td className="p-3 text-slate-700">{meaning}</td><td className="p-3 text-amber-800">{mistake}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Built-In Training or a Custom Loop?</h2><p className="text-lg leading-relaxed">A custom loop is valuable for understanding and unusual training logic, but it also creates more opportunities for mistakes. Use the simplest interface that supports the actual experiment.</p><div className="not-prose overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Situation</th><th className="p-3 text-left">Recommended approach</th><th className="p-3 text-left">Why</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Ordinary classification or regression","Built-in fit/trainer","Less boilerplate; callbacks and metrics are already integrated"],["Learn how training works","Small explicit loop","Every operation remains visible"],["Several losses or optimizers","Custom step or custom loop","You control exactly what updates and when"],["GANs, reinforcement learning, gradient accumulation","Custom loop","The algorithm does not fit one standard forward-loss-update cycle"],["Production experiment tracking","Framework loop plus callbacks when possible","Reduces custom state and resuming errors"]].map(([situation,choice,why])=><tr key={situation}><td className="p-3 font-bold text-indigo-800">{situation}</td><td className="p-3 font-semibold text-emerald-800">{choice}</td><td className="p-3 text-slate-700">{why}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Debugging Order That Saves Time</h2><p className="text-lg leading-relaxed">When training fails, changing the architecture first usually hides the real problem. Check the pipeline from the earliest input to the final update.</p><div className="not-prose grid gap-3 md:grid-cols-2">{[["1. Inspect one batch","Print shapes, data type, minimum, maximum and several labels. Display images after preprocessing."],["2. Check the forward output","Confirm output shape, finite values and the expected logits/probabilities for the loss."],["3. Check loss on known cases","A better hand-made prediction should receive lower loss than a worse one."],["4. Check gradients","Verify important parameters have non-None, finite gradient values and sensible norms."],["5. Check the update","Compare one weight before and after optimizer.step(); it should change during training only."],["6. Run the tiny-data test","Prove the model can fit 10–20 examples before adding regularization or more layers."]].map(([title,text])=><div key={title} className="rounded-xl border border-slate-200 bg-white p-5"><p className="mb-2 font-extrabold text-slate-900">{title}</p><p className="m-0 text-sm leading-relaxed text-slate-600">{text}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Common Mistakes</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[800px] text-sm"><thead className="bg-rose-900 text-white"><tr><th className="p-3 text-left">Mistake</th><th className="p-3 text-left">What goes wrong</th><th className="p-3 text-left">Correction</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Do not clear gradients","Current and earlier batch gradients are added","Call zero_grad each step unless accumulation is intentional"],["Validate in training mode","Dropout and BatchNorm behave incorrectly for evaluation","Call model.eval() before validation"],["Update on validation data","Validation stops being independent","Never call backward or optimizer.step in validation"],["Average batch means incorrectly","Small final batch can receive too much influence","Accumulate loss × batch size, then divide by example count"],["Watch accuracy only","Confidence and loss problems remain hidden","Track task metrics and loss together"],["Use the test set every epoch","Model choices indirectly overfit the test set","Tune on validation; evaluate test once choices are frozen"]].map(([mistake,effect,fix])=><tr key={mistake}><td className="p-3 font-bold text-rose-800">{mistake}</td><td className="p-3 text-slate-700">{effect}</td><td className="p-3 text-emerald-800">{fix}</td></tr>)}</tbody></table></div></section>

    <section className="not-prose rounded-2xl bg-gradient-to-br from-indigo-950 to-slate-900 p-6 text-white md:p-8"><h2 className="mb-4 text-2xl font-extrabold">What to remember</h2><div className="grid gap-4 md:grid-cols-2">{[["One batch creates one correction","Load → clear → forward → loss → backward → update."],["One epoch visits the training set once","Batch size determines the number of updates per epoch."],["Validation measures; it never teaches","Use evaluation mode, no gradients and no weight updates."],["Curves are diagnostic evidence","Compare training and validation trends, then investigate causes in order." ]].map(([title,text])=><div key={title} className="rounded-xl border border-white/15 bg-white/10 p-4"><p className="mb-1 font-bold text-indigo-200">{title}</p><p className="m-0 text-sm leading-relaxed text-slate-200">{text}</p></div>)}</div></section>
  </div>;
}
