import React from "react";

function TransferJourneyFigure() {
  const features = ["edges", "textures", "parts", "shapes"];
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">Transfer learning keeps useful representations and replaces the old decision</p></div><div className="overflow-x-auto p-5 md:p-7"><div className="flex min-w-[900px] items-center gap-5"><div className="w-48 rounded-2xl border border-blue-200 bg-blue-50 p-5 text-center"><p className="text-xs font-bold uppercase text-blue-700">source pretraining</p><p className="mt-3 font-bold text-blue-950">many general images</p><p className="mt-2 text-xs text-slate-600">old labels: 1,000 classes</p></div><span className="text-3xl font-black text-slate-400">→</span><div className="flex-1 rounded-2xl border-2 border-indigo-500 bg-indigo-50 p-5"><p className="text-center text-xs font-bold uppercase text-indigo-700">pretrained backbone</p><div className="mt-4 grid grid-cols-4 gap-2">{features.map((f,i)=><div key={f} className="rounded-lg bg-white p-3 text-center"><p className="font-mono text-xs font-bold text-indigo-900">block {i+1}</p><p className="mt-1 text-xs text-slate-600">{f}</p></div>)}</div><p className="mt-4 text-center text-xs text-indigo-800">reusable weights</p></div><span className="text-3xl font-black text-slate-400">→</span><div className="w-48 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-center"><p className="text-xs font-bold uppercase text-emerald-700">new task head</p><p className="mt-3 font-bold text-emerald-950">normal / scratch / crack</p><p className="mt-2 text-xs text-slate-600">target factory data</p></div></div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">The old classifier is task-specific and is replaced. Earlier representations may transfer because visual edges and shapes remain useful, but usefulness depends on similarity between source and target data.</figcaption></figure>;
}

function TrainingStagesFigure() {
  const rows = [
    ["Stage 1 · establish baseline", "frozen", "train", "Learn the new head without disturbing pretrained features"],
    ["Stage 2 · partial fine-tuning", "early blocks frozen; later blocks train", "train", "Adapt higher-level features with a smaller learning rate"],
    ["Stage 3 · optional full fine-tuning", "all train, often at very small rates", "train", "Attempt deeper domain adaptation only if validation supports it"],
  ];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">Fine-tuning is a controlled sequence, not one switch</p><div className="mt-5 space-y-3">{rows.map(([stage,backbone,head,why],i)=><div key={stage} className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-[210px_1fr_120px_1.5fr] md:items-center"><p className="font-bold text-indigo-900">{stage}</p><p className={`rounded-lg p-3 text-center text-xs font-bold ${i===0?"bg-slate-200 text-slate-600":"bg-violet-100 text-violet-800"}`}>backbone: {backbone}</p><p className="rounded-lg bg-emerald-100 p-3 text-center text-xs font-bold text-emerald-800">head: {head}</p><p className="text-sm text-slate-700">{why}</p></div>)}</div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">Stop at whichever stage gives the best held-out result under your compute budget. Full fine-tuning is optional, not the definition of success.</figcaption></figure>;
}

function DomainSimilarityFigure() {
  const cells = [
    ["Similar data · few labels", "Freeze most layers; train a small head", "bg-emerald-50 border-emerald-300 text-emerald-950"],
    ["Similar data · many labels", "Fine-tune later blocks, then compare full fine-tuning", "bg-blue-50 border-blue-300 text-blue-950"],
    ["Different data · few labels", "Transfer may be weak; use augmentation/self-supervision and cautious fine-tuning", "bg-amber-50 border-amber-300 text-amber-950"],
    ["Different data · many labels", "Compare pretrained initialization with training from scratch", "bg-violet-50 border-violet-300 text-violet-950"],
  ];
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">Target size and domain similarity guide the first experiment</p><div className="mt-5 grid gap-3 md:grid-cols-2">{cells.map(([title,advice,style])=><div key={title} className={`rounded-xl border p-5 ${style}`}><p className="font-bold">{title}</p><p className="mt-2 text-sm leading-relaxed">{advice}</p></div>)}</div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">This is a starting heuristic. Measure on the actual target split: negative transfer can occur when pretrained features or normalization assumptions do not fit the new domain.</figcaption></figure>;
}

function LearningRateFigure() {
  return <figure className="not-prose my-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><p className="font-bold text-slate-900">Discriminative learning rates protect general features</p><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-center"><p className="text-xs font-bold uppercase text-blue-700">early backbone</p><p className="mt-2 font-mono font-bold text-blue-950">η = 0 or 10⁻⁵</p><p className="mt-2 text-xs text-slate-600">general features</p></div><div className="rounded-xl border border-violet-200 bg-violet-50 p-4 text-center"><p className="text-xs font-bold uppercase text-violet-700">late backbone</p><p className="mt-2 font-mono font-bold text-violet-950">η = 10⁻⁴</p><p className="mt-2 text-xs text-slate-600">adaptable task features</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-center"><p className="text-xs font-bold uppercase text-emerald-700">new head</p><p className="mt-2 font-mono font-bold text-emerald-950">η = 10⁻³</p><p className="mt-2 text-xs text-slate-600">randomly initialized</p></div></div><figcaption className="mt-5 text-sm leading-relaxed text-slate-600">These rates are illustrative, not universal defaults. A newer random head often needs larger movement; pretrained layers usually need smaller updates.</figcaption></figure>;
}

function ContrastiveLearningFigure() {
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">Self-supervision creates its own training signal from an unlabelled image</p></div><div className="overflow-x-auto p-5 md:p-7"><div className="grid min-w-[900px] grid-cols-[170px_1fr_210px] items-center gap-5"><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-center"><p className="text-4xl">🚲</p><p className="mt-2 font-bold text-blue-950">one unlabelled image</p></div><div className="space-y-4"><div className="flex items-center gap-3"><span className="text-2xl text-slate-400">→</span><div className="flex-1 rounded-xl border border-violet-200 bg-violet-50 p-4 text-center"><p className="font-bold text-violet-950">random crop + colour change</p><p className="mt-1 text-xs text-slate-600">view A → shared encoder → vector z₁</p></div><span className="text-2xl text-emerald-600">↘</span></div><div className="flex items-center gap-3"><span className="text-2xl text-slate-400">→</span><div className="flex-1 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-center"><p className="font-bold text-indigo-950">different crop + blur</p><p className="mt-1 text-xs text-slate-600">view B → same encoder → vector z₂</p></div><span className="text-2xl text-emerald-600">↗</span></div></div><div className="rounded-2xl border-2 border-emerald-400 bg-emerald-50 p-5 text-center"><p className="font-bold text-emerald-950">pull z₁ and z₂ together</p><p className="mt-2 text-sm text-emerald-800">same source image = positive pair</p><div className="my-3 border-t border-emerald-200" /><p className="font-bold text-rose-900">separate other images</p><p className="mt-2 text-sm text-rose-700">different sources = negatives</p></div></div></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600">The labels come from how the views were created, not from a person naming the object. The chosen augmentations define which changes the representation should ignore.</figcaption></figure>;
}

function FewShotFigure() {
  const point = (x:number,y:number,fill:string,label:string) => <g><circle cx={x} cy={y} r="15" fill={fill} stroke="#334155" strokeWidth="2"/><text x={x} y={y+4} textAnchor="middle" fontSize="11" fontWeight="700" fill="#0f172a">{label}</text></g>;
  return <figure className="not-prose my-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><p className="font-bold text-slate-900">A 2-way 2-shot episode: classify the query by the nearest class prototype</p></div><div className="overflow-x-auto p-5 md:p-6"><svg viewBox="0 0 920 330" className="min-w-[760px]" role="img" aria-label="Two support examples per class are averaged into prototypes, and a query is assigned to the nearer prototype"><defs><marker id="fewArrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker></defs><rect x="20" y="35" width="240" height="250" rx="18" fill="#f8fafc" stroke="#cbd5e1"/><text x="140" y="65" textAnchor="middle" fontSize="15" fontWeight="700" fill="#0f172a">support set (labelled)</text>{point(85,120,"#bfdbfe","C1")}{point(180,135,"#bfdbfe","C1")}{point(85,220,"#fde68a","C2")}{point(180,235,"#fde68a","C2")}<text x="140" y="270" textAnchor="middle" fontSize="12" fill="#475569">2 classes × 2 examples</text><line x1="270" y1="160" x2="380" y2="160" stroke="#64748b" strokeWidth="3" markerEnd="url(#fewArrow)"/><text x="325" y="145" textAnchor="middle" fontSize="12" fill="#475569">average each</text><rect x="395" y="35" width="220" height="250" rx="18" fill="#eef2ff" stroke="#a5b4fc"/><text x="505" y="65" textAnchor="middle" fontSize="15" fontWeight="700" fill="#312e81">embedding space</text>{point(470,125,"#60a5fa","P1")}{point(540,225,"#fbbf24","P2")}{point(500,155,"#fda4af","?")}<line x1="500" y1="155" x2="470" y2="125" stroke="#16a34a" strokeWidth="4"/><line x1="500" y1="155" x2="540" y2="225" stroke="#dc2626" strokeWidth="2" strokeDasharray="7 5"/><text x="475" y="180" fontSize="12" fontWeight="700" fill="#166534">distance 1</text><text x="530" y="195" fontSize="12" fontWeight="700" fill="#991b1b">distance 3</text><line x1="625" y1="160" x2="735" y2="160" stroke="#64748b" strokeWidth="3" markerEnd="url(#fewArrow)"/><rect x="750" y="85" width="145" height="150" rx="18" fill="#ecfdf5" stroke="#6ee7b7" strokeWidth="2"/><text x="822" y="125" textAnchor="middle" fontSize="13" fontWeight="700" fill="#065f46">query prediction</text><text x="822" y="170" textAnchor="middle" fontSize="28" fontWeight="800" fill="#1d4ed8">class 1</text><text x="822" y="200" textAnchor="middle" fontSize="12" fill="#475569">nearest prototype</text></svg></div><figcaption className="border-t border-slate-100 px-5 py-3 text-sm leading-relaxed text-slate-600"><strong>Way</strong> is the number of classes in an episode; <strong>shot</strong> is the labelled support examples per class. The unlabelled item being classified is the <strong>query</strong>.</figcaption></figure>;
}

export function TransferLearningContent({ focus = "transfer" }: { focus?: "transfer" | "limited-label" } = {}) {
  return <div className="prose prose-lg max-w-none text-slate-700">
    <section className="not-prose mb-10 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-emerald-800 px-6 py-10 text-white shadow-xl md:px-10 md:py-12"><p className="mb-3 text-sm font-extrabold uppercase tracking-[0.18em] text-emerald-200">{focus === "limited-label" ? "Deep Learning · Learning with Limited Labels" : "Deep Learning · Transfer Learning"}</p><p className="mt-5 max-w-4xl text-lg leading-relaxed text-indigo-50 md:text-xl">{focus === "limited-label" ? "Learn how a model can pretrain representations from unlabelled data, then adapt those representations when only a small labelled support set is available. Self-supervised and few-shot learning are connected, but they solve different parts of the limited-label problem." : "Learn how to reuse a pretrained model, replace its old task-specific head, freeze or unfreeze layers deliberately, and fine-tune with learning rates that protect useful representations."}</p></section>

    {focus === "transfer" && <>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why Reuse a Model?</h2><p className="text-lg leading-relaxed">A factory may have only 800 labelled product images—far too few to teach a large vision model every useful edge, texture and shape from scratch. A model pretrained on a much larger image collection already contains weights that respond to many visual structures. Transfer learning asks whether those representations can help the factory task.</p><p className="text-lg leading-relaxed">The pretrained model is the <strong>source model</strong>; your new labelled problem is the <strong>target task</strong>. The reusable part is usually called a <strong>backbone</strong> or encoder. Its old classifier head is removed because its labels do not match yours.</p><TransferJourneyFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Feature Extraction and Fine-Tuning Are Different</h2><div className="not-prose grid gap-4 md:grid-cols-3">{[["Train from scratch","Initialize backbone and head randomly; update everything.","Useful comparison when target data is large or unlike pretraining."],["Fixed feature extractor","Freeze the backbone; train only the new head.","Fast, memory-efficient baseline for small similar datasets."],["Fine-tuning","Start from pretrained weights; update some or all backbone layers.","Adapts features, but increases overfitting and forgetting risk."]].map(([title,body,use])=><div key={title} className="rounded-xl border border-indigo-200 bg-indigo-50 p-5"><p className="font-bold text-indigo-950">{title}</p><p className="mt-2 text-sm leading-relaxed text-indigo-900">{body}</p><p className="mt-3 text-xs font-bold text-emerald-700">{use}</p></div>)}</div><p className="mt-5 text-lg leading-relaxed"><strong>Freezing</strong> means a parameter is excluded from gradient updates. It does not delete the parameter, and it does not necessarily control every layer&apos;s train/evaluation behavior. Dropout and normalization state still require deliberate mode handling.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Use a Staged Training Plan</h2><p className="text-lg leading-relaxed">First train the new random head while the backbone stays stable. Once the head maps pretrained features to target labels reasonably, unfreeze later blocks and continue at a smaller rate. This avoids sending large, noisy gradients from an untrained head through useful pretrained layers on the first update.</p><TrainingStagesFigure /><DomainSimilarityFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Why the Backbone Usually Needs a Smaller Learning Rate</h2><p className="text-lg leading-relaxed">Every trainable weight still follows the optimizer&apos;s update rule. For plain SGD, w<sub>new</sub>=w−ηg. The gradient g is calculated by backpropagation from the current batch; learning rate η is chosen by the developer. Multiplying them gives the update size, and subtracting moves the weight in the direction that locally reduces loss. Different parameter groups can use different η values.</p><div className="not-prose rounded-2xl border border-violet-200 bg-violet-50 p-5 md:p-6"><h3 className="text-xl font-bold text-violet-950">Same gradient, different movement</h3><p className="mt-2 text-slate-700">For comparison, manually use the same illustrative gradient g=0.2 for one pretrained backbone weight and one new head weight. The two learning rates are example hyperparameters, not prescriptions.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>Backbone η=0.00001</strong><br />change = ηg<br />= 0.00001×0.2<br />= <strong>0.000002</strong></p><p className="rounded-lg bg-white p-4 font-mono text-sm leading-7"><strong>New head η=0.001</strong><br />change = ηg<br />= 0.001×0.2<br />= <strong>0.0002</strong></p></div><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Interpretation:</strong> the new head moves 100 times farther in this example. The backbone can adapt gradually instead of immediately overwriting its features.</p></div><LearningRateFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Preprocessing Is Part of the Pretrained Model</h2><p className="text-lg leading-relaxed">Pretrained weights expect the channel order, resize/crop policy and normalization used during source training. A model may compile with incorrect preprocessing yet receive a distribution unlike anything it learned. Use the transform bundled with the weight object and save it with deployment code.</p><div className="not-prose rounded-xl border-l-4 border-amber-500 bg-amber-50 p-5"><p className="font-bold text-amber-950">BatchNorm needs special attention</p><p className="mt-2 text-sm leading-relaxed text-amber-900">BatchNorm has learned affine parameters and running statistics. Freezing parameters does not make every framework&apos;s training/evaluation semantics identical. With small target batches, updating running statistics can damage predictions. Keep the intended mode explicit and verify running-stat behavior when unfreezing.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Two-Stage PyTorch Workflow</h2><p className="text-lg leading-relaxed">This example adapts a pretrained ResNet-18 to three defect classes. The weight object supplies matching image transforms. Stage 1 trains only the replacement head. Stage 2 unfreezes the last residual block and rebuilds the optimizer with smaller backbone learning rate.</p><div className="not-prose overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="bg-slate-800 px-4 py-2 font-mono text-xs text-slate-300">staged_transfer_learning.py</div><pre className="overflow-x-auto bg-[#1e1e1e] p-5 font-mono text-sm leading-relaxed text-[#d4d4d4]">{`import torch
from torch import nn
from torchvision.models import resnet18, ResNet18_Weights

weights = ResNet18_Weights.DEFAULT
preprocess = weights.transforms()  # use for train/validation input baseline
model = resnet18(weights=weights)

# Replace the 1,000-class ImageNet head with three target classes.
in_features = model.fc.in_features
model.fc = nn.Linear(in_features, 3)

# Stage 1: freeze backbone, train the new head.
for parameter in model.parameters():
    parameter.requires_grad = False
for parameter in model.fc.parameters():
    parameter.requires_grad = True

optimizer = torch.optim.AdamW(model.fc.parameters(), lr=1e-3)
# ... run training/validation epochs here ...

# Stage 2: adapt the final backbone block carefully.
for parameter in model.layer4.parameters():
    parameter.requires_grad = True

# Rebuild optimizer so newly unfrozen parameters are included.
optimizer = torch.optim.AdamW([
    {"params": model.layer4.parameters(), "lr": 1e-5},
    {"params": model.fc.parameters(), "lr": 1e-4},
], weight_decay=1e-4)

# Confirm exactly what can update.
trainable = [name for name, p in model.named_parameters() if p.requires_grad]
print("trainable parameter tensors:", len(trainable))
print(trainable[:5])`}</pre></div><div className="not-prose mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold text-blue-950">What is reused and what is new?</p><p className="mt-2 text-sm leading-relaxed text-blue-900"><code>DEFAULT</code> selects a versioned pretrained-weight recipe; <code>weights.transforms()</code> returns its expected resizing and normalization. <code>in_features</code> is read from ResNet&apos;s existing head, while output size 3 comes from the target labels. PyTorch randomly initializes that replacement head.</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold text-emerald-950">Why rebuild the optimizer?</p><p className="mt-2 text-sm leading-relaxed text-emerald-900"><code>requires_grad=False</code> prevents backbone gradients and updates in stage 1. After <code>layer4</code> is unfrozen, the old optimizer still contains only head parameters; rebuilding it includes the newly trainable tensors and gives backbone and head separate, chosen learning rates.</p></div></div><p className="mt-4 text-sm leading-relaxed text-slate-600">Training augmentation can be added around the required normalization while validation remains deterministic. Evaluate the frozen-head baseline before stage 2; continue only if target validation improves.</p></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">How Much Should You Unfreeze?</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[960px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Situation</th><th className="p-3 text-left">First experiment</th><th className="p-3 text-left">What to compare next</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Very small target set, similar images","Freeze backbone; regularized linear head","Unfreeze only last block with early stopping"],["Moderate target set, noticeable domain shift","Head first, then later blocks","Gradual/full fine-tuning at smaller rates"],["Large target set, related domain","Pretrained full fine-tuning","Scratch baseline under equal compute"],["Medical/satellite/thermal data unlike source","Test transfer, but expect mismatch","Domain-specific/self-supervised pretraining"],["Latency-constrained deployment","Pretrained compact backbone","Distillation, pruning/quantization and device benchmarks"],["Text task with large language model","Head, adapters or low-rank updates","Full fine-tuning only with sufficient data/compute"]].map(([s,first,next])=><tr key={s} className="align-top"><td className="p-3 font-bold text-slate-900">{s}</td><td className="p-3 text-indigo-800">{first}</td><td className="p-3 text-emerald-800">{next}</td></tr>)}</tbody></table></div></section>
    </>}

    {focus === "limited-label" && <>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Problem: Useful Data, Very Few Labels</h2><p className="text-lg leading-relaxed">Many projects can collect images, recordings or documents cheaply, but trustworthy labels require scarce expert time. Two ideas address different parts of this problem. <strong>Self-supervised learning</strong> first learns representations from unlabelled data by creating supervision from the data itself. <strong>Few-shot learning</strong> asks a trained system to recognize a new task or new classes from only a tiny labelled support set.</p><p className="text-lg leading-relaxed">They can be used separately or together: an encoder may learn from a large unlabelled collection, then support a few-shot classifier when only one to five examples of a new class arrive.</p></section>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Self-Supervised Learning: Learn from Data Before Adding Labels</h2><p className="text-lg leading-relaxed">Suppose a hospital owns one million unlabelled scans but radiologists have labelled only 2,000. Throwing away the unlabelled scans wastes information about common shapes and textures. <strong>Self-supervised learning</strong> creates a learning target from the data itself, so an encoder can learn useful representations before the smaller labelled task begins.</p><p className="text-lg leading-relaxed">One family is <strong>contrastive learning</strong>. It treats two changed views of the same item as a <strong>positive pair</strong> and views from other items as <strong>negative examples</strong>. A <strong>projection head</strong> temporarily maps encoder features into the space where the contrastive loss is calculated. After pretraining, that projection head is commonly discarded and the encoder is transferred to a labelled task.</p><ContrastiveLearningFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Small Contrastive-Loss Calculation</h2><p className="text-lg leading-relaxed">A simplified InfoNCE-style objective turns similarities into a probability. For anchor i and its positive view j:</p><div className="not-prose rounded-xl border border-indigo-200 bg-indigo-50 p-5 md:p-6"><p className="overflow-x-auto text-center font-mono text-base font-bold text-indigo-950">Lᵢ = −log [ exp(sᵢⱼ/τ) / Σₖ exp(sᵢₖ/τ) ]</p><p className="mt-3 text-sm leading-relaxed text-slate-700"><strong>sᵢₖ</strong> is a model-produced similarity between the anchor and candidate k. <strong>τ</strong> is a positive developer-chosen temperature: dividing by a smaller τ spreads the softmax scores more sharply. Exponentiation makes comparison weights positive, normalization makes them sum to 1, and −log penalizes low positive probability.</p></div><div className="not-prose mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 md:p-6"><h3 className="text-xl font-bold text-emerald-950">One positive and two negatives</h3><p className="mt-2 text-slate-700">For a transparent demonstration, use already temperature-scaled scores 2 for the positive and 0 and 1 for two negatives. These three numbers are manually chosen; a real encoder and temperature produce them.</p><p className="mt-4 rounded-lg bg-white p-4 font-mono text-sm leading-7">positive probability = e² / (e² + e⁰ + e¹)<br />= 7.389 / (7.389 + 1 + 2.718)<br />≈ <strong>0.665</strong><br /><br />loss = −ln(0.665) ≈ <strong>0.408</strong></p><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Meaning:</strong> increasing positive similarity relative to the negatives raises that probability and lowers loss. Production implementations must handle both directions, masking and numerical stability.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Augmentations Define What “Same” Means</h2><p className="text-lg leading-relaxed">Contrastive learning is not automatically correct simply because labels are absent. If colour determines whether fruit is ripe, aggressive colour removal may teach the encoder to ignore the very evidence needed downstream. If left and right have different medical meaning, a horizontal flip can create a false positive pair.</p><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[920px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Decision</th><th className="p-3 text-left">Question to ask</th><th className="p-3 text-left">Failure if wrong</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["View generation","Should prediction remain unchanged after this crop, blur, flip or colour shift?","False positive pairs erase useful information"],["Negative sampling","Could two different records actually mean the same thing?","False negatives push related examples apart"],["Data split","Were near-duplicates/patients/users separated before pretraining evaluation?","Leakage overstates transfer quality"],["Evaluation","Does a linear probe or fine-tuned target model beat simple baselines?","Low pretext loss may not mean useful features"]].map(([d,q,f])=><tr key={d}><td className="p-3 font-bold text-slate-900">{d}</td><td className="p-3 text-indigo-800">{q}</td><td className="p-3 text-rose-800">{f}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Evaluate the Representation, Not Only the Pretraining Loss</h2><p className="text-lg leading-relaxed">A low contrastive or reconstruction loss does not prove that the encoder learned features useful for the real task. Freeze the encoder and train a simple linear classifier on top: this <strong>linear probe</strong> tests how accessible the target information already is. Then compare controlled fine-tuning, a generic pretrained encoder and a scratch baseline using the same splits and metrics.</p><div className="not-prose rounded-xl border border-blue-200 bg-blue-50 p-5 text-sm leading-relaxed text-blue-950"><strong>Keep the test honest:</strong> separate patients, users, documents or time periods before pretraining evaluation, report performance across label budgets, and inspect class-level failures. Otherwise duplicates or selection effects can make an unhelpful representation look strong.</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Few-Shot Learning: Adapt from a Tiny Support Set</h2><p className="text-lg leading-relaxed"><strong>Few-shot learning</strong> evaluates whether a system can handle a new task or new classes from very few labelled examples. In a 5-way 1-shot image episode, the support set contains one labelled example for each of five classes. The model must classify separate query examples from those same episode classes.</p><p className="text-lg leading-relaxed">This is different from ordinary fine-tuning on a small dataset: few-shot methods are commonly trained across many episodes so the learning procedure matches how the model will be tested. <strong>Meta-learning</strong> is the broader idea of learning across tasks so adaptation to a new task becomes faster; metric-based prototypes are one approach, while optimization-based methods such as MAML learn an initialization that can adapt in a few gradient steps.</p><FewShotFigure /></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Worked Example: Classify with Two Prototypes</h2><p className="text-lg leading-relaxed">A prototypical classifier embeds each support example, averages embeddings within a class, then assigns a query to the nearest class average (the <strong>prototype</strong>). The two-dimensional coordinates below are manually chosen teaching embeddings. In a real episode the encoder produces them from labelled support items and an unlabelled query.</p><div className="not-prose rounded-2xl border border-violet-200 bg-violet-50 p-5 md:p-6"><p className="font-mono text-sm leading-7 text-violet-950">class 1 supports: (1,1), (1,3)<br />prototype c₁ = ((1+1)/2, (1+3)/2) = <strong>(1,2)</strong><br /><br />class 2 supports: (5,1), (5,3)<br />prototype c₂ = <strong>(5,2)</strong><br /><br />query q = (2,2)<br />d(q,c₁) = √[(2−1)²+(2−2)²] = <strong>1</strong><br />d(q,c₂) = √[(2−5)²+(2−2)²] = <strong>3</strong></p><p className="mt-4 text-sm leading-relaxed text-slate-700"><strong>Why average and measure distance?</strong> Averaging creates one representative centre per class; Euclidean distance measures how far the query lies from each centre. The result is class 1 because distance 1 is smaller than distance 3. Real performance depends on whether the encoder learned a space where semantic classes form useful clusters.</p></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Choose the Strategy That Matches the Data You Actually Have</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Situation</th><th className="p-3 text-left">Strong first approach</th><th className="p-3 text-left">Why</th><th className="p-3 text-left">Main check</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Related public checkpoint + modest labelled target set","Transfer learning","Reuse broad features and train a target head","Compare frozen and fine-tuned validation results"],["Large in-domain unlabelled collection + few labels","Self-supervised pretraining, then transfer","Learn domain representations before using scarce labels","Probe/fine-tune against generic pretrained and scratch baselines"],["New classes arrive with 1–5 examples each","Few-shot metric/meta-learning","Make support/query adaptation part of training","Evaluate on genuinely unseen classes/tasks"],["Enough representative labels and compute","Supervised pretraining or training from scratch as a baseline","Direct objective may be simplest","Match compute, split and selection fairly"],["Different domain and weak source match","In-domain self-supervision or closer source model","Reduces source-target mismatch","Watch negative transfer and augmentation validity"]].map(([s,a,w,c])=><tr key={s} className="align-top"><td className="p-3 font-bold text-slate-900">{s}</td><td className="p-3 text-indigo-800">{a}</td><td className="p-3">{w}</td><td className="p-3 text-emerald-800">{c}</td></tr>)}</tbody></table></div><p className="mt-5 text-lg leading-relaxed">These methods can form one pipeline: self-supervise an encoder on unlabelled in-domain data, transfer it to episodic training, then classify new classes from a few support examples.</p></section>
    </>}

    {focus === "transfer" && <>
    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Negative Transfer: When Reuse Hurts</h2><p className="text-lg leading-relaxed"><strong>Negative transfer</strong> means pretrained initialization performs worse than a reasonable alternative because source features or biases do not match the target. Natural-image pretraining may still help medical images, but it is not guaranteed; text pretraining in one language or domain may tokenize and represent another poorly.</p><div className="not-prose grid gap-4 md:grid-cols-3">{[["Run a scratch baseline","Use the same split, augmentation, budget and selection rule."],["Inspect the domain gap","Compare channels, resolution, vocabulary, label meaning and data collection."],["Try closer pretraining","In-domain supervised or self-supervised pretraining may transfer better than a famous generic checkpoint."]].map(([title,body])=><div key={title} className="rounded-xl border border-rose-200 bg-rose-50 p-5"><p className="font-bold text-rose-950">{title}</p><p className="mt-2 text-sm leading-relaxed text-rose-900">{body}</p></div>)}</div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">Common Transfer-Learning Mistakes</h2><div className="not-prose overflow-x-auto rounded-xl border border-slate-200 shadow-sm"><table className="w-full min-w-[980px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Symptom</th><th className="p-3 text-left">Likely mistake</th><th className="p-3 text-left">Correction</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{[["Accuracy collapses when fine-tuning begins","Learning rate too high or random head destabilizes backbone","Train head first; reduce backbone rate; unfreeze gradually"],["Unfrozen layer never changes","Optimizer was created before unfreezing and excludes it","Rebuild optimizer or add a parameter group; compare weights before/after"],["Validation changes when batch size changes","Normalization statistics/mode are unstable","Control train/eval mode; inspect BatchNorm running statistics"],["Model compiles but performs poorly","Wrong resize, channel order or normalization","Use transforms paired with exact weight version"],["Great random-split score, poor production score","Duplicate/user/time leakage","Split by deployment unit and remove near duplicates"],["Large model overfits within a few epochs","Too much capacity for target labels","Freeze more, regularize head, augment and stop earlier"],["Checkpoint cannot be reproduced","Model, weights, tokenizer/transform and labels not versioned","Save exact identifiers, preprocessing, class map and configuration"]].map(([symptom,cause,fix])=><tr key={symptom} className="align-top"><td className="p-3 font-bold text-slate-900">{symptom}</td><td className="p-3 text-rose-800">{cause}</td><td className="p-3 text-indigo-800">{fix}</td></tr>)}</tbody></table></div></section>

    <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Transfer Experiment Must Answer More Than Accuracy</h2><p className="text-lg leading-relaxed">Compare validation quality, per-class errors, calibration, training time, memory and inference latency. Record the best checkpoint by a target metric rather than the last epoch. If labels are scarce, repeat across seeds or folds where appropriate because a single split can make one strategy look better by chance.</p><p className="text-lg leading-relaxed">Also review the source model&apos;s licence, training-data documentation and intended use. Transfer carries source biases and limitations along with useful features.</p></section>
    </>}

    {focus === "transfer" ? <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">A Reliable Transfer-Learning Checklist</h2><div className="not-prose rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><ol className="m-0 space-y-2 pl-5 text-emerald-950"><li>Check whether source data and the target domain are related enough to make reuse plausible.</li><li>Use the exact preprocessing paired with the selected checkpoint.</li><li>Measure a frozen-backbone baseline before gradually unfreezing later blocks.</li><li>Use a smaller learning rate for pretrained weights than for the new head.</li><li>Compare against a fair scratch baseline and inspect negative transfer.</li><li>Save the class map, preprocessing, weight version and best validation checkpoint.</li></ol></div><div className="not-prose mt-5 rounded-xl border-l-4 border-indigo-500 bg-indigo-50 p-5 text-indigo-950"><strong>Next step:</strong> transfer learning starts from existing labelled pretraining. The next lesson asks what to do when your own domain contains abundant unlabelled data or a new class arrives with only a few labelled examples.</div></section> : <section><h2 className="mb-4 text-2xl font-bold text-indigo-800">The Limited-Label Learning Checklist</h2><div className="not-prose rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><ol className="m-0 space-y-2 pl-5 text-emerald-950"><li>Define the unlabelled collection, target task and label budget before selecting a method.</li><li>Design self-supervised views around transformations that should preserve downstream meaning.</li><li>Evaluate representations with a linear probe or controlled fine-tuning baseline.</li><li>For few-shot claims, separate support and query examples and test on genuinely unseen classes or tasks.</li><li>State the N-way K-shot episode design and compare prototypes with simple nearest-neighbour baselines.</li><li>Report variation across episodes, domain shift, compute and failure cases—not one average accuracy alone.</li></ol></div></section>}

    <section><h2 className="mb-4 border-b pb-2 text-2xl font-bold text-indigo-800">Continue Learning</h2><div className="not-prose mb-10 grid gap-4 md:grid-cols-2"><a href={focus === "limited-label" ? "/learn/transfer-learning" : "/learn/autoencoders"} className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Previous concept</p><p className="m-0 font-bold text-slate-900">{focus === "limited-label" ? "Transfer Learning and Fine-Tuning" : "Autoencoders and Their Variants"}</p></a><a href={focus === "limited-label" ? "/learn/graph-neural-networks" : "/learn/self-supervised-few-shot-learning"} className="rounded-xl border border-slate-200 p-4 no-underline transition-colors hover:border-indigo-300 hover:bg-indigo-50"><p className="mb-1 text-xs font-bold uppercase text-indigo-600">Next concept</p><p className="m-0 font-bold text-slate-900">{focus === "limited-label" ? "Graph Neural Networks" : "Self-Supervised and Few-Shot Learning"}</p></a></div></section>
  </div>;
}

export function SelfSupervisedFewShotContent() {
  return <TransferLearningContent focus="limited-label" />;
}
